### ISSUE TITLE
64-bit Centos 7.2 running 1.4.1.7 doesn't have window decorations on GatherDebugInfo panel

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#126] opened 2016-08-28 03:18 UTC
This is a weird one.  Only way I found to close it was to right-click the titlebar and choose close.  Working in a VM I couldn't figure out the Fn keystroke to close the window (Maybe Ctrl-F4?)

Probably need to change the planet to have an explicit close that will work on all platforms.  And we need a loading screen anyway, since it can take a few seconds to run the cmd lines needed and to scan for IGDs when there aren't any, meaning the panel takes 8s-10s to populate and display.

**Comment by emmebi** [comment] 2020-02-17 07:40
Two issues:
- dialog without decorations when opened on CentOS 7.2 (will need to setup one instance to test and see what is the possible fix);
- the gathering of the information is done in the same thread as the one opening the dialog; since this can take a long time, the menu entry remains selected while the information is  gathered.

If no one else is working, assign it to me and I will work on this in the next week or so.

**Comment by JamzTheMan** [comment] 2020-02-17 13:04
Done.

**Comment by emmebi** [comment] 2020-02-19 07:18
@Azhrei Regarding the window decorations, I am trying to reproduce this on CentOS 8.x in a VM on Virtual Box with a Windows host, but a minimal decoration is shown.

Questions:
- What Window Manager are you using for this? 
- Can you reproduce it on latest release/develop?

Regarding the second point, I have a quick fix, but I am trying to write in a clean way. Hopefully by the end of the week I will post a PR.

**Comment by Azhrei** [comment] 2020-02-21 21:37
I've had to pull a CentOS VM from backups and getting it up and running has been... painful.  Lots of VM-related stuff to fix, but also the JDK I grabbed from Oracle for 10.0.2 doesn't contain JFX so the MT JAR won't run.  I'll get back to this over the weekend.

**Comment by emmebi** [comment] 2020-02-23 15:17
The above PR addresses the second point; not sure how to proceed for the first one.

**Comment by Phergus** [comment] 2020-02-23 15:34
Going to open a separate issue for the refactoring of SysInfo.

**Comment by emmebi** [comment] 2020-02-23 15:49
So, this issue will remain open only for the lack of decorations, and the pull request is going to go on #1313, right?

**Comment by Phergus** [comment] 2020-02-23 15:51
Will probably close this one unless someone can reproduce it with a current release.

**Comment by Phergus** [comment] 2020-02-23 16:01
Closing issue.  Reopen if it can be reproduced with a current MT release and CentOS build.

**Closed by Phergus** 2020-02-23 16:01 UTC
Labels: bug
