### ISSUE TITLE
Macro Function to Pull an Array of X/Y Pairs Defining the Area from a Drawing

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#407] opened 2019-03-30 12:04 UTC
**Is your feature request related to a problem? Please describe.**
The ability to pull the  X/Y pairs defining the polygon which defines the area of a drawing would be useful when used in conjunction with other MTScript functions like movedOverPoints() to help define macro triggers for crossing the boundary of a drawing.  

**Describe the solution you'd like**
Add a menu option to the Draw Explorer that would grab the X/Y pairs of a drawing or drawing group that are copied to the text copy buffer. Also the ability to get these X/Y pairs from a drawing or drawing group that has been named via the Draw Explorer.

**Describe alternatives you've considered**
You have to guesstimate the boundary now for input into your macros.

**Additional context**
[movedOverPoints wiki entry](http://lmwcs.com/rptools/wiki/movedOverPoints) The output of the new feature should match the input to this function.

**Comment by Jaggeroth** [comment] 2019-03-30 21:19
I think I will build a getDrawingInfo function that will return a full description of the drawing.
One of the attributes with be the path, which could be passed into the moveOverPoints function.

**Comment by Phergus** [comment] 2019-03-30 21:25
That would be very nice.

**Comment by Jaggeroth** [comment] 2019-03-31 15:46
I have a working getDrawingInfo() function _BUT_ after some thought I think what you actually need is a
movedOverDrawing(map, drawingId, lastPath) function.

**Comment by rkathey** [comment] 2019-03-31 17:59
That would be outstanding.

**Comment by JamzTheMan** [comment] 2019-03-31 18:27
Can we pass a tokenID as well to save the trouble of getting and passing lastPath?

Also, is the getDrawingInfo returning a json that is also compatible with get/set vbl functions? I have no use case other than it could be useful?

**Comment by Phergus** [comment] 2019-03-31 19:03
> I have a working getDrawingInfo() function _BUT_ after some thought I think what you actually need is a
> movedOverDrawing(map, drawingId, lastPath) function.

While that is certainly useful, and a more direct resolution to the original target, I do think that the getDrawingInfo() will turn out to be helpful in other ways.

**Comment by JamzTheMan** [comment] 2019-03-31 19:07
So we need both?

We have, what, a movedOverPoints or something now?  Do we need another function? Or rather, one function that can check if a token is moved over tokens/drawing/vbl/mbl/etc?

**Comment by Phergus** [comment] 2019-03-31 19:23
So an overloaded function that can handle pretty much anything in MT which has a defined area?

movedOver(map, myPoints) - passed a json array of pixel coordinates, current movedOverPoints
movedOver(map, token) - token name or ID,  already have this as movedOverToken
movedOver(map, drawingID?) - ???
movedOver(map, vbl) - ??? how to call out VBL except as an array of points?

BTW,  you can already generate/remove VBL from a drawing via the Drawing Explorer.

**Comment by Jaggeroth** [comment] 2019-03-31 22:08
Voting no on the overloaded function. Pain in the rear for script functions ;)

You want a separate function for "movedOverDrawing" because calculating the area of a drawing is not always simple and cannot always be reduced to a set of points.

**Comment by Phergus** [comment] 2019-03-31 23:23
Okay.  No overloaded function.  You take all the fun out of it.  ;)   Sorry @JamzTheMan.

The currentMovedOverPoints handles odd shaped areas like below.  The issue is just that if the array of points for the drawing was accessible it would be so much easier to pass those to the function instead of calculating those points by hand.

![Screenshot 2019-03-31 17 17 30](https://user-images.githubusercontent.com/34379254/55296628-558fb200-53d9-11e9-945a-d326c3926746.png)

**Comment by Jaggeroth** [comment] 2019-04-01 08:09
The getDrawingInfo() function I have produced so far will provide that information.
What you won't get is path info for Ovals or for the accumulated shape of drawing groups.
For that you will need a movedOverDrawing() "hopefully" ;)

**Comment by Phergus** [comment] 2019-04-01 13:23
> The getDrawingInfo() function I have produced so far will provide that information.
Awesome.  That alone should be a big boost in usability for movedOverPoints().

> What you won't get is path info for Ovals or for the accumulated shape of drawing groups.
I don't see those as being significant issues.  Both cases can be handled fairly simply.

> For that you will need a movedOverDrawing() "hopefully" ;)
Bonus points!

**Comment by Jaggeroth** [comment] 2019-04-02 07:50
Since @JamzTheMan has merged my PR for the getDrawingInfo() function, I think this can be moved to done. But will leave that to the people who organise the release schedule :)

**Comment by JamzTheMan** [comment] 2019-04-02 12:00
Yea, not sure why GitHub isn't autoclosing these...

**Closed by JamzTheMan** 2019-04-02 12:00 UTC
Labels: 3, feature, in progress, macro changes
