### ISSUE TITLE
[Bug]: Light sources default to black color rather than no color

### ISSUE THREAD

**Issue by shondoa** [RPTools/maptool#4253] opened 2023-08-17 00:32 UTC
### Describe the Bug

Light sources, including personal light sources from vision, act as if they are colored black (hex #000000) rather than having no color.

### To Reproduce

Create a light source with no color value and see how it dims the area it illuminates.

### Expected Behaviour

Light sources with no color attached should not change the color of the area they illuminate.

### Screenshots

![image](https://github.com/RPTools/maptool/assets/1754184/d6a6dbe0-9867-4eac-b256-ada37f5d937f)

### MapTool Info

1.13.2, 1.14.0-alpha3

### Desktop

Windows 10

**Comment by kwvanderlinde** [comment] 2023-08-17 02:23
Duplicate of #4213. The fix is already in and will be released as part of 1.14!

**Closed as completed by kwvanderlinde** 2023-08-17 02:23 UTC
Labels: bug
