### ISSUE TITLE
[Bug]: Specific arrangement of on-token topology + PC vision causes infinite loop of error dialogs

### ISSUE THREAD

**Issue by henczati** [RPTools/maptool#3626] opened 2022-09-13 23:09 UTC
### Describe the Bug

I was trying to create vision blocking for a ship's sails for a movable ship, so topology was saved on-token.

Procedure of topology creation, for each sail (on the same image):
1. Long Wall VBL line.
2. Filled oval Hill VBL intersecting 1.
3. Erase oval Wall VBL of exactly the same size as 2, to remove the segment of 1 where it intersects with 2.
The order of 1 and 2 might have been switched.

If I put a token next to this sails token and set it from NPC to PC (turning on token vision), a seemingly constantly-repeating error dialog (infinite loop?) pops up.

The error in the dialog (without backtrace) is:
```
org.locationtech.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 208.0 -137.0, 208.0 134.66667 ) and LINESTRING ( 208.0 134.66667, 208.0 134.666667 ) [ (208.0, 134.66667, NaN) ]
```
**Note the `NaN` in the last position at the end.**
Full error details text with the 65 line backtrace in the `error.txt` attachment.
Note that this was produced with a "reduced" scene.  One of the early occurrences in a more complicated scene had 815 lines of backtrace.

WARNING:  If I close the error dialog, there is another of the same underneath it.  I was unable to close all error dialogs, I have to kill the MapTool process when the error occurs to escape it.  While an error dialog is present, the MT window is not re-rendered: moving the error dialog "smears" MT window colors.

Then -- if I did not kill MT yet -- after cca. a minute another error dialog pops-up with:
```
While creating snapshot
java.lang.reflect.InvocationTargetException
```
IMHO, MT probably ran out of some resource and cannot create new instances of the first error dialog anymore.

AFAICT, for the error-loop to occur, I need to have at least 2 such (separate) sail topology definitions on the token, and the PC token has to be (or be moved) into somewhere on the "plane-stripe" between 2 such sail topology definitions.  See the 2 sets of instructions for reproducing the error.  The PC token can be on or off the problematic (sails) token, but as long as it's in the mentioned "plane-stripe", the error occurs.

### To Reproduce

Attached images of steps (in `reproduce-A `[...]`.zip` and `reproduce-B `[...]`.zip`) were made with the "reduced" token (having only 2 separate sail topology definitions).
I also attached the original token with all 3 sails on the image having topology defined to play around with---there are more positions/areas for the PC token which invoke the error with this one.

*Note that step numbering is a little weird because it coincides with the names of step images and I reused some of the images in both alternative step progressions.*

A)  Invoke error on NPC to PC change (if token already in "bad" position):

    1. Move in attached sails token.
    2. Add-or-move a new token in the "plane-stripe" between sail topology definitions.
    3.0. Set new token from NPC to PC, then click OK.
    4. Observe error.
    5. Observe moving the error dialog smearing MT window colors (no redraw).
    6. Observe another error dialog after cca. a minute time.

B)  Invoke error on PC token moved to "bad" position (if new token was not placed in the "plane-stripe" between the sail topology defs):

    1. Move in attached sails token.
    2b. Add-or-move a new token NOT in the "plane-stripe" between sail topology definitions.
    3.0. Set new token from NPC to PC, then click OK.
    3.1b. Move PC token in between sail topology definitions.
    4. Observe error.
    5. Observe moving the error dialog smearing MT window colors (no redraw).
    6. Observe another error dialog after cca. a minute time.

### Expected Behaviour

NOT freezing the program up with uncountable error dialogs.
Ideally, not producing an error at all and drawing view according to the topology correctly, like when the PC token is not in a "bad" position.

### Screenshots

[reproduce-A Invoke error on NPC-to-PC change.zip](https://github.com/RPTools/maptool/files/9561271/reproduce-A.Invoke.error.on.NPC-to-PC.change.zip)
[reproduce-B Invoke error when PC token moves into bad position.zip](https://github.com/RPTools/maptool/files/9561274/reproduce-B.Invoke.error.when.PC.token.moves.into.bad.position.zip)

### MapTool Info

Version: 1.12.0-beta.3  Install type: New

### Desktop

OS: Linux [LUbuntu 18.04]

### Additional Context

[error.txt](https://github.com/RPTools/maptool/files/9561348/error.txt)
[big sailingship sails - w problematic MT 1.12.0b3 topology (all 3 sails defined).rptok.renamed_to.zip](https://github.com/RPTools/maptool/files/9561349/big.sailingship.sails.-.w.problematic.MT.1.12.0b3.topology.all.3.sails.defined.rptok.renamed_to.zip)
[big sailingship sails - w problematic MT 1.12.0b3 topology (reduced - 2 sails defined).rptok.renamed_to.zip](https://github.com/RPTools/maptool/files/9561350/big.sailingship.sails.-.w.problematic.MT.1.12.0b3.topology.reduced.-.2.sails.defined.rptok.renamed_to.zip)

**Comment by kwvanderlinde** [comment] 2022-09-14 08:46
This error isn't specific to token topology. I transferred the topology to a map and then reduced it so that it is a little quicker and simpler to test:
[Broken Vision.zip](https://github.com/RPTools/maptool/files/9564351/Broken.Vision.zip)

Reproduction steps with this map are:
1. Import the map
2. Change "Hero" to PC.
3. See breakage

Unlike the other topology issues we've been seeing, the example in this case has completely sane topology. The issue is just that one of the diagonal edges of Wall VBL lies exactly on top of an edge of Hill VBL. JTS is supposed to handle this for us, but this case is very susceptible to the tiniest precision errors, so JTS isn't reliable in this case. I'm looking at options but will likely change vision blocking to handle each topology type separately as that should avoid these sorts of pathological cases.

**Comment by Phergus** [comment] 2022-09-15 22:57
Tested.  No longer causes infinite loop.

**Closed by Phergus** 2022-09-15 22:57 UTC
Labels: bug, tested
