### ISSUE TITLE
[Bug]:  playStream not working with execFunction

### ISSUE THREAD

**Issue by Arthur-WhiteCorp** [RPTools/maptool#3895] opened 2023-04-01 23:04 UTC
### Describe the Bug

When i try to use playStream with execFunction to play audio it does not work.

### To Reproduce

my code:
[playStream(macro.args)]
[H: songUrl = json.append("[]","https://dl.dropboxusercontent.com/s/ir0f5tr3fkdefxs/rainforest_ambience3.mp3")]
[H: execFunction("playStream", songUrl, 0, "all")]

### Expected Behaviour

Audio should play.

### Screenshots

![bug](https://user-images.githubusercontent.com/76797238/229319862-971c2a34-9460-4d7e-b1de-f77f677e473b.png)

### MapTool Info

I am using version 1.12.2

### Desktop

Windows 10 Pro 22H2

**Comment by emmebi** [comment] 2023-04-02 11:49
Remove the
```
 [playStream(macro.args)]
```
at the beginning of your macro.

**Comment by Jmr3366** [comment] 2023-04-07 18:05
I've attempted a few times and this isn't failing for me (LAN connection between two laptops, tested on 1.11.5, 1.12.2, and 1.13.1beta)
Stop Macro:
`[h: execFunction("stopSound",json.append("","*"),0,"all")]`
Play macro: 
`[H: songUrl = json.append("[]","https://dl.dropboxusercontent.com/s/ir0f5tr3fkdefxs/rainforest_ambience3.mp3")]`
`[H: execFunction("playStream", songUrl, 0, "all")]`

**Comment by Jmr3366** [comment] 2023-04-17 11:34
@Phergus  I'm not able to duplicate this issue and I believe it was more syntax related.  I believe this should be closed.

**Comment by FullBleed** [comment] 2023-04-17 12:04
I believe that @bubblobill has mentioned this being an issue... even going so far as to creating a custom execFunction to work with his music and sound mixer.

https://discord.com/channels/296230822262865920/1009374846788046869/1076418154873487380

**Comment by Jmr3366** [comment] 2023-04-17 22:26
I'm not sure where the root cause is but if you `string` the JSON it works:
`[h: execFunction("playStream", json.append("[]","https://dl.dropboxusercontent.com/s/ir0f5tr3fkdefxs/rainforest_ambience3.mp3","1","0.2","0","-1"), 0, "all")]`
The json being passed into `execFunction` that is then being parsed for the function `execFunction` will to run, may not be handling a value correctly.

**Comment by FullBleed** [comment] 2023-04-18 03:12
> I'm not sure where the root cause is but if you `string` the JSON it works: `[h: execFunction("playStream", json.append("[]","https://dl.dropboxusercontent.com/s/ir0f5tr3fkdefxs/rainforest_ambience3.mp3","1","0.2","0","-1"), 0, "all")]` The json being passed into `execFunction` that is then being parsed for the function `execFunction` will to run, may not be handling a value correctly.

I know you're working this one out... but I wonder if this, perchance, is related to this issue with execFunction: https://github.com/RPTools/maptool/issues/3382

Pinging @kwvanderlinde since he found the other execFunction issue (which may or may not be fixed in 1.12+) ...

**Comment by kwvanderlinde** [comment] 2023-04-18 04:12
Alas it has nothing to do with it and the other issue only applies to 1.11.

I'll start by echoing what Jmr said - I can't reproduce the original issue with only a URL, nor do I see any reason in code for that to be an issue.

As for the issue when other parameters exist, that is due to the second parameter (`cycleCount`) being required to be an integer. But we aren't careful to keep the integer-ness when sending the arguments to the client, so the `1` gets turned into `1.0` and gets rejected on the client.  This should be an easy fix, assuming we don't have any code expected that particular behaviour for some reason...

**Comment by kwvanderlinde** [comment] 2023-04-18 04:15
I'll put up a fix, we should be able to get this into 1.13 yet.

**Closed** 2023-04-18 05:50 UTC
Labels: bug
