### ISSUE TITLE
Add parser comments

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#1146] opened 2020-01-18 08:07 UTC
When testing it's just nice to be able to comment out a section for testing without having to rewrite that section of code. Also, I would like to use examples in comments that may look like code and not have it run.

May I suggest . This is what coldfusion uses and most IDE text editors still treat the color coding as a regular comment. It would also limit the blank output to chat when commenting code.

I think this was discussed before and not sure why there wasn't a follow through. I think someone wanted to make the regular  also parser comments, but that would likely break older code.

**Comment by Merudo** [comment] 2020-03-21 17:52
Is this a duplicate of #730 ?

**Comment by Phergus** [comment] 2020-03-22 16:38
Yup.  It's a duplicate.

**Closed by Phergus** 2020-03-22 16:38 UTC
Labels: duplicate, feature
