### ISSUE TITLE
Offset grid: pasted tokens no longer go in the cell we want

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#2260] opened 2020-10-12 17:59 UTC
**Describe the bug**
If I adjust the grid, specifically moving the offset of it, pasted tokens will not go where they should.

**To Reproduce**
- Create a new map. Use defaults, doesn't matter.
- Adjust Grid. No need to change the size of the grid, just move the grid offset around some.
- Paste a token. It no longer goes in the cell you are pointing at.

**Expected behavior**
pasted items should always go into the cell your mouse is currently pointing at.

**MapTool Info**
- Version: 1.7.0 (EXE)
[edit] Notice it also happens with 1.5.6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [10 1909]

**Comment by Phergus** [comment] 2020-10-13 19:59
I thought this was fixed in 1.8 but it's still there.

**Comment by Phergus** [comment] 2021-06-11 18:56
Still present in 1.9.0

**Comment by kwvanderlinde** [comment] 2023-03-15 22:38
This bug should be fixed since 1.10.

**Comment by Phergus** [comment] 2023-03-16 17:44
It is except for one weird case.  If you have tokens on the map, select one and hit Copy, then adjust the grid so that the offsets are both negative some amount and now paste a token it is offset by one cell from the mouse pointer.

Also weird, I can set the offset manually to positive values but dragging the grid only results in negative offsets.  When I manually set the offset to a positive value and pasted a previously copied token it went where I pointed.

**Comment by kwvanderlinde** [comment] 2023-03-16 19:12
> It is except for one weird case. If you have tokens on the map, select one and hit Copy, then adjust the grid so that the offsets are both negative some amount and now paste a token it is offset by one cell from the mouse pointer.
> 
> Also weird, I can set the offset manually to positive values but dragging the grid only results in negative offsets. When I manually set the offset to a positive value and pasted a previously copied token it went where I pointed.

It also effects positive offsets, we just get lucky and those tend to land in the same cell anyways. But crank it to be larger than the grid size and tokens will be pasted the lower-right of the cursor.

**Comment by kwvanderlinde** [comment] 2023-03-16 19:48
There's one more odd thing I found, though it might be by design.

Tokens that are snap-to-grid will use their cell offset from the top-left token when pasted. This means if we adjust the grid size between copying and pasting, the tokens will spread out or be pulled in accordingly, keeping the number of cells between them constant. But we don't scale other token positions, so the relative positioning between snap-to-grid and non-snap-to-grid can be surprisingly changed.

E.g., I start with a 50x50 grid with one non-snap-to-grid token:
![image](https://user-images.githubusercontent.com/7492219/225734818-51a00790-9bb6-4638-9a32-b0a574c82c2f.png)

I select them all and copy. Then set the grid size to 200x200. When pasting they now look like this (don't be fooled, these tokens are 4x bigger than the previous screenshot):
![image](https://user-images.githubusercontent.com/7492219/225734965-389d8449-b176-46fb-be79-b5012a59561d.png)

**Closed** 2023-03-28 06:01 UTC
Labels: bug
