### ISSUE TITLE
GM tokens FOW revealed to the players on auto reveal 

### ISSUE THREAD

**Issue by bobifle** [RPTools/maptool#187] opened 2018-05-03 01:26 UTC
Full history
http://forums.rptools.net/viewtopic.php?f=3&p=269873#p269873

Maptool 1.4.1.8

a/ start a server with "auto reveal on move" option selected, connect a client to it
b/ empty map (visible to player) with FOW enabled and one token assigned to server/GM ownership
c/ hit CTRL+e CTRL+f and move the token around from the server

FOW is revealed to the player.

**Comment by Azhrei** [comment] 2018-10-01 23:34
Hm.  If you're not using individual views and the token is a PC, isn't this the right thing to do?

If the token is NPC, then this is the wrong thing to do unless the player is also an owner.

And if you're using IV, this is the wrong thing to do unless the player is also an owner.

**Comment by n2ash** [comment] 2018-10-02 05:46
Seems to happen regardless of PC/NPC setting, individual view, strict ownership, token ownership, and even the sighted token's visibility altogether as long as individual FOW is off and auto-reveal on movement is on.

Here's a quick test campaign. Recommended to use two clients, one for GM, one to confirm sight as player. Critical settings are reveal on movement on, individual FOW off.

[fowbug.zip](https://github.com/RPTools/maptool/files/2436587/fowbug.zip)

**Comment by Azhrei** [comment] 2018-10-02 15:10
Hm.  If Individual FOW is off, and IV is off, it seems to me that GM token movement affecting FOW should depend on only the PC/NPC flag — If the token is a PC, then it should contribute to shared FOW, otherwise it should not.

Does anyone else see a reason it should work the way it currently does?

**Comment by Phergus** [comment] 2018-10-02 16:40
What if the NPC is with the party but none of  the players have control of the token because you don't want them looking at it's stats or other information?

Or maybe it would be normally controlled by a player but that player isn't there so the GM is moving both the missing players PC and NPC hireling.

The problem is that the game mechanics terms PC & NPC are being used to control when exposure happens instead of an internal MT distinction between GM-owned and Player-owned.

Kayila's suggestion that tokens should have a flag/checkbox on them to determine if they expose when moved by the GM may be part of a solution.

**Comment by Jaggeroth** [comment] 2018-10-02 16:43
Not sure I want more flags.
Also not sure why "having vision" isn't enough to determine if something should effect FOW

**Comment by Phergus** [comment] 2018-10-02 16:47
Because users want their NPC tokens to Have Sight so they can determine what they can see.  They just don't want those tokens to expose when moved.

I hear you about more flags.  There are already sooo many options here, there and everywhere.  Hard to keep track of what impacts what.

**Comment by Azhrei** [comment] 2018-10-02 16:48
I think we've always expected that NPCs owned by players would react like PCs in most cases, including FOW.  But if players don't own the NPC, they can't move it.  So the GM has to move it.  But we _don't_ want that to expose FOW because the GM moves every other NPC token that isn't owned by players and those certainly should _not_ expose FOW!  So in your first case, I'd say it shouldn't expose FOW and the GM has to right-click and choose "Expose Last Path" (or whatever the menu option says).

Your second scenario is the one that occurred to me immediately — the player isn't there so the GM is playing the character (the GM always plays the NPC hirelings).  In this case, the token would be a PC so it should expose FOW.  The NPC is likely owned by the player as well, so it should expose FOW.

It does seem like using a single flag to turn this on/off would be better than having a plethora of options that have to be checked with various IF statements everywhere in the code. :(  @Jaggeroth says he doesn't want "another flag", but this wouldn't be "another", it'd be a replacement for all of the ugly logic that we currently have.  You know, "one flag to rule them all."

The only question is who has the authority to set that flag?  We don't want players to be able to set the flag on NPCs when the GM decides that for their campaign NPCs shouldn't expose FOW, even when owned by players.

**Comment by Phergus** [comment] 2018-10-02 18:02
I would agree that, given the current state of MT, it would be more correct for NPCs not owned by Players and moved by the GM to not expose even if they do have sight.

> ...the player isn't there so the GM is playing the character (the GM always plays the NPC hirelings). In this case, the token would be a PC so it should expose FOW. The NPC is likely owned by the player as well, so it should expose FOW.
That is a DnD mindset.  There is no universal law that says only a GM can control NPCs.  Plenty of game systems have different mechanics for PCs and NPCs so a way to detect this is needed.  If it was supposed to mean GM-Controlled and Player-Controlled than that is what it should have said.

> The only question is who has the authority to set that flag? We don't want players to be able to set the flag on NPCs when the GM decides that for their campaign NPCs shouldn't expose FOW, even when owned by players.

Yeah, with no current ability to lock players out of the Edit Token dialog putting a flag there is an issue.  The right-click menu isn't going to work for the same reason.  When don't have a top Token menu so no obvious place there.  Would obviously need macro function to set/clear but having that as the only way is a bit rude.

**Comment by Azhrei** [comment] 2018-10-02 18:14
> There is no universal law that says only a GM can control NPCs.

Except the name:  NPC = **non**-player-character.  By definition, NPCs are not controlled by players.  If they were, they'd be PCs. ;)

It may be true that different game systems have different techniques and I wouldn't argue that.  But the definitions are pretty clear and much shorter than "GM controlled" and "Player controlled".

> with no current ability to lock players out of the Edit Token dialog putting a flag there is an issue

Perhaps it's good enough to say that tokens dragged to the map by the GM have the flag turned off, and tokens dragged to the map by a player have it turned on?  There will be exceptions where that won't be true, of course, but it should cover 99% of the cases, right?

And for existing campaigns that are "upgraded" to this new scheme, we can base it on the PC/NPC flag and ownership.  Once the campaign is loaded the first time, saving it out will bump the version number of the campaign file and the new "expose" flag will be there, so no need to do anything further...

**Comment by Phergus** [comment] 2018-10-02 19:18
I don't see the word control in the definition.  You could just as easily say PC means a character that is the focus of the story while NPC means all the bit parts.  As I said, you have DnD lenses in your shades.
 :stuck_out_tongue_winking_eye:

Having the flag turned off if a GM drops a token in is probably a good idea but there also needs to be an easy way to set it for the GM.  None of the GMs in our group have the players drop in tokens.  Tokens are always added by the GMs.

Agree on the campaign upgrade on load.

**Comment by Azhrei** [comment] 2018-10-02 20:30
Heh, you're right.  I'm going to define them as Non-Player Controlled and Player Controlled from now on. 🙄

Yes; for existing campaigns in particular, there needs to be a way to "bulk change" the flag.  The right-click menu is perfect for that using multi select on the tokens, but the silly thing is already too large. 😐

I'm sure @JamzTheMan will create a macro script function for toggling it.  That's kinda his thing.  But I agree that we need something in the UI for this.

**Comment by n2ash** [comment] 2018-10-02 21:52
I'm definitely in that 1% as all my PC tokens are cloned from GM-created templates and I've had players stepping in to run NPC tokens before several times.

As far as allied NPC sight goes: how clunky would adding it as a sight option be? I guess the risk there is needing to clone potentially all your sight definitions if you have a varied cast of allied NPCs..

I'm just not sure there's a more elegant solution than a toggle for joining an NPC token to the collective PC vision - otherwise the rabbit hole seems deep and the edge cases are many.

**Comment by JamzTheMan** [comment] 2018-10-02 22:20
Couldn't this "flag" be a server option?

And ya, game systems now have special rules, usually easier dying rules and such for nlc type characters. 

And how about charmed monster? Clearly you control him in most sense of the word but are not in his mind.

I'd rather not have more flags as well if we can avoid it.

Let's explore this sight tag more... What IF there simply was a tag for this? Or a couple? Like PC|NPC|All 

Does it need to be a flag for vision or for or does it encompass both?

**Comment by Azhrei** [comment] 2018-10-03 01:46
@n2ash 
> I've had players stepping in to run NPC tokens
So clearly you need ownership to mean that FOW should be cleared.  I think we've decided that already, as without being able to clear the FOW, the player wouldn't be able to move the token anyway.

@JamzTheMan 
> I'd rather not have more flags as well if we can avoid it.
And I think the proposal was to replace all of the existing FOW checks so that instead of having a bunch of special cases (if IV=on, and IF=on, and...) they would all be replaced with a single flag that simply says that a given token reveals FOW or doesn't.  You've seen the code in ZoneRenderer so you know how wonky the nested if stamements become... wouldn't it be nice to have a single Boolean to replace all that logic?

I'm going to start a thread on the forum (larger user base) and link back to here, but I'll come back here when there's some kind of vision (pun intended) on the goal.

**Comment by oliver-szymanski** [comment] 2019-03-16 00:15
My POV about this: I agree with people saying PC/NPC should both be able to be controlled by players and therefore have the (configurable) ability to reveal FOW.

Why not per default say a PC does reveal, an NPC not. And then (there was a discussion about adding a GM only writeable tab for token details on edit token dialogue) put an override in the new (hopefully coming) GM tab. That way there is one flag, which has a defined default if not set.

**Comment by Azhrei** [comment] 2019-03-16 02:05
I think the implementation is not as important _right now_ as whether this is even a good idea.  For example, are there situations where a single flag would cause the wrong result?  I can't think of any off-hand.  I did find the spreadsheet I was looking for, but then had a panic attack trying to resolve how it might work... 😳

**Comment by Oryan77** [comment] 2019-04-01 01:04
I am the person that originally reported this bug on the forums. My actually but report explains the problem in more detail (if this is helpful):
[https://forums.rptools.net/viewtopic.php?f=21&t=27936](url)

I was bummed seeing that this still wasn't fixed in v1.5.1. I just want to point out that I have been using MT with these exact settings since whatever version was out in 2011. It was working just fine all the way up to v1.4.0.5. Then it stopped working correctly in every version after that. I only mention that in case it is useful to know.

I prefer using these settings because as the DM, I like to see what my NPC tokens can see so that I am not doing anything "unfair" with those characters (reacting to something he shouldn't be seeing). However, I don't want FoW to be revealed to players just because I moved an NPC token that they didn't even know existed in a room that they didn't even know was there. It worked fine before, so I don't know why the function would change how it has worked for 8 years.

**Comment by Azhrei** [comment] 2019-04-01 02:25
It is useful to know; thanks.  We can compare the renderer code as it was in 1405 with the way it is now.

When someone is dragging a token, a separate thread is created for each drag.  So the main renderer is handling normal stuff, then the new thread handles the moving token.  There is a LOT of conditional code in the renderer to handle all of the different vision, light, aura, and sight options.  It would be quite easy for newly modified code to miss one of those IF statements.  It may have been a side-effect of changes made for "always display above vbl" or similar flags.

**Comment by Phergus** [comment] 2019-08-24 17:01
While configurable behavior would be best, returning MapTool back to the previous system where a GM moved, NPC token does not expose would be the right thing to do now whether it Has Sight or not.

**Comment by JamzTheMan** [comment] 2019-08-24 18:14
I'll have to take a look at this, it got lost in the cracks. Since I wrote the whole "ownership based fow" stuff anyway.  It shouldn't do that and it doesn't for me but I use IFoW settings so suspect that's where it is at...

I pretty much use it like @Oryan77 does for the most part (and prefer to have NPC vision for "fairness" as well. We had a GM that always assumed Creatures had "Darkvision" when in fact a lot do not)

**Comment by Phergus** [comment] 2019-08-24 18:51
Confirmed.  Only exposes if IFOW setting is off.

**Comment by JamzTheMan** [comment] 2019-08-25 00:52
Yea, it was probably overlook because both me and dorpond (I assume otherwise he would have caught it) use iFoW.

It shouldn't be a hard fix, just have to find it.

Maybe we make 1.5.5 the FoW pass. If there are other FoW/Light issues, Let's add them to the project if it makes sense.

**Comment by Phergus** [comment] 2019-08-25 03:45
That sounds reasonable.

**Comment by dorpond** [comment] 2019-08-25 11:35
@Jamz, I never use iFOW because I play face to face and all the players share the same screen. Plus my group never really splits up like they used to 20 years ago; I guess dying wasn’t appealing to them. Lol.

**Comment by JamzTheMan** [comment] 2019-08-25 13:22
@dorpond do you use auto reveal on?

**Comment by Merudo** [comment] 2019-09-05 07:45
@dorpond I believe a workaround is to use iFOW, but give all PC tokens global ownership.

**Comment by Merudo** [comment] 2019-09-05 09:25
For the record I think the problem is with `exposeArea` in `Zone`. It always reveal FoW when iFoW is disabled, regardless of NPC/ownership status.

**Comment by dorpond** [comment] 2019-09-05 10:45
@merudo I don’t experience this bug during games because I don’t autoexpose on move. That’s also a triggering variable with this, right?

**Comment by Merudo** [comment] 2019-09-06 06:30
Yep.

**Comment by JamzTheMan** [comment] 2019-09-07 04:38
hmmm, this may be deeper an issue than I thought... i'll continue to dig and report back,,,

**Comment by Merudo** [comment] 2019-09-07 06:52
Can I have a go at it too? I'd like to try something out.

**Comment by Merudo** [comment] 2019-09-07 08:21
Also, if strict token management is off, should unowned tokens reveal FoW?

**Comment by Phergus** [comment] 2019-09-07 12:46
@Merudo  You had asked whether unowned tokens should expose if Strict Token Ownership (STO) is off.

I don't know.   Without STO, any client can move any token so would it make sense to be using Vision and FoW?   The map explorer is going to tell each client exactly what tokens are on the map.

**Comment by JamzTheMan** [comment] 2019-09-08 14:07
@Phergus Going to reference here from other issue to continue and work out this bug (thanks btw):

> My understanding.
> 
> iView
> ON - a player sees only what his owned tokens can see
> OFF - a player can see what all PC tokens can see
> 
> IFoW
> ON - Exposed FoW areas are **not** shared between tokens and each token has it's own exposed FoW areas kept in the token object. Players have no idea where other player tokens are at unless they are within sight of one of their tokens.
> OFF - Exposed FoW areas **are** shared and that info is kept in map object. Every player can see the areas exposed by player tokens.

I think when iFoW is off and iView is on, the PlayerView code is just being to aggressive and not filtering out the right tokens. 

Question, we can't obviously use "Ownership" in this case and is the issue. So two possible fixes:
1. Revert back to PC vs NPC for this setting option.
2. Use owned vs unowned for this setting. (in other words, show the combined view of any token that has an owner, even if owned by GM client. hide views from any token that has no ownership)

Thoughts?

**Comment by Phergus** [comment] 2019-09-21 16:23
@JamzTheMan 

> 
> I think when iFoW is off and iView is on, the PlayerView code is just being to aggressive and not filtering out the right tokens.
> 
> Question, we can't obviously use "Ownership" in this case and is the issue. So two possible fixes:
> 
>     1. Revert back to PC vs NPC for this setting option.
> 
>     2. Use owned vs unowned for this setting. (in other words, show the combined view of any token that has an owner, even if owned by GM client. hide views from any token that has no ownership)

It's working correctly with the current code so I'm not sure where you are going with this.  The changes you made when you added the server option did that.

I consider this to be done.

@bobifle  if you have the code pulled down please test and confirm.

**Comment by JamzTheMan** [comment] 2019-09-22 16:05
Oops, accidentally hit the close button.

But wait, it's fixed? I swore I tested this and it still was happening... Mmm

**Comment by Merudo** [comment] 2019-09-22 17:27
Yeah it's still happening when Individualized Views are off.

**Comment by Merudo** [comment] 2019-09-22 17:30
I think it's fixed. No FOW is revealed if `Individualized Views` is off and `GM Reveal Vision` is off.

**Comment by JamzTheMan** [comment] 2019-09-22 17:41
Cool cool cool.

**Comment by Phergus** [comment] 2019-09-22 20:45
If that switch is off, GM movement of unowned tokens doesn't expose.  Given that there is no reason to ever assign an owner to a GM NPC, that means that NPC tokens that aren't part of the players party don't expose.  It's working exactly the way it should.

**Closed by Phergus** 2019-09-22 20:45 UTC
Labels: bug, claimed, tested
