### ISSUE TITLE
Maptool hangs on corrupt asset loading.

### ISSUE THREAD

**Issue by FullBleed** [RPTools/maptool#2831] opened 2021-06-29 23:18 UTC
**Describe the bug**
This is a fairly common problem that has been around a long time.  A user comes to the forums or Discord and says, "My screen is stuck at loading X!  What do I do?"

And the usual fix is, "Delete your assetcache."

**To Reproduce**
I don't know how to reproduce the error.  The assumption floated by most devs in the past is that there is a corrupt asset in their assetcache and MT gets hung up on it.  How any why this happens is unknown... but it happens enough to ruin some game sessions when people can't get a timely resolution.

**Expected behavior**
When MT encounters a corrupt asset during load-in it should not hang indefinitely and should be self-healing.

**Screenshots**
Not applicable.

**MapTool Info**
- Version: All

**Desktop (please complete the following information):**
 - OS: I only know for sure that this happens on Windows.  Linux and Mac users would have to chime in on whether or not it's ever happened to them.

**Additional context**
If the issue itself can not be fixed with more robust error-checking during asset transfer, perhaps there needs to be in app fix.

Suggestion:  Put a warning message on-screen after some arbitrary time frame on asset load-in that says something like, "You may have a corrupt asset in your cache.  You can try flushing and restarting the asset transfer below:"  Then add a "Flush Asset" button that they can click to delete the current hung assets and restart the transfer.

**Comment by Azhrei** [comment] 2021-06-29 23:41
Duplicate of #2663

**Closed by Azhrei** 2021-06-29 23:41 UTC
Labels: bug

**Comment by FullBleed** [comment] 2021-06-30 05:38
That is not the same issue.

This is about a corrupt asset.

That is about "When adding many new tokens using assets from the resource library."

Players have MT freeze on them because of a bad asset and they aren't adding anny assets frfom the resource library.
