### ISSUE TITLE
Macro functions getNewRolls() & getRolled() no longer see rolls from json.objrolls()

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2444] opened 2021-03-09 01:15 UTC
**Describe the bug**
The macro functions `getNewRolls()` and `getRolled()` return an empty array after a `json.objrolls()` call.

```
<pre>[json.indent(json.objrolls("['henchman1']",
        "['Str', 'Dex', 'Con', 'Int', 'Wis', 'Chr']",
        "3d6"),2)]</pre>
New: [r: getNewRolls()]<br>
All: [r: getRolled()]
```

**To Reproduce**
1. Copy macro code above and execute in MapTool 1.8.3
2. Note empty arrays.
![image](https://user-images.githubusercontent.com/34379254/110403297-1abd3c80-803a-11eb-81aa-6d4061f8e4b8.png)

**Expected behavior**
Should return the rolls that were made.  Was working in 1.7.0
![image](https://user-images.githubusercontent.com/34379254/110403267-0bd68a00-803a-11eb-9f5a-90e2fc1581e3.png)

**MapTool Info**
- Version: 1.8.3
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Reported by DarkFire82#0569 on Discord.

**Comment by selquest** [comment] 2021-03-10 05:09
After a quick look at this I suspect the issue is the new parser being created here:
https://github.com/RPTools/maptool/blob/536c86a9eb4820653e814863a66c6d342b7783d4/src/main/java/net/rptools/maptool/client/functions/json/JSONMacroFunctions.java#L542-L544
The parser manages the RunData that carries around the rolls history, so a local parser instantiated by a helper method within a single macro call provides some challenges.  Not sure if that context even occurred to me during RPTools/dicelib#38, but it's been a while.  I'll dig into it some more.

**Comment by selquest** [comment] 2021-03-14 06:31
Deeper dive into this, and I've got a fix in dicelib - I'll clean up and submit the issue/PR tomorrow.

For anyone interested in more details:
In the normal course of execution, the MapToolLineParser processes an Expression into a Result, and manages the `rolled` and `newRolls` arrays accessed by `getRolled()` and `getNewRolls()` accordingly.
https://github.com/RPTools/maptool/blob/440a73551b5c1a600fb004f1837bc0c7253fb5be/src/main/java/net/rptools/maptool/client/MapToolLineParser.java#L1032-L1036

The problem here is that `json.objrolls()` creates its *own* parser to evaluate the rolls internally (see previous comment) and gets a Result object that never leaves the helper method.  The fix for this is to have the child RunData instance in this inner context inform its parent when a new number has been rolled - the inner context is aware of only its own rolls, but the parent context can track all the rolls that it or any of its children has made.

Working on a unit test to guard against regression (once a fixed version of dicelib is included), verifying expected behavior of `getNewRolls()` and `getRolled()` in normal chat/macros, UDFs, and internal contexts like this one.  That test will be here in the MT project, so a PR coming here soon too.

**Comment by selquest** [comment] 2021-03-17 17:30
PRs submitted - note that tests added here in MT #2469 will fail until the dicelib fix is applied and included.

Attaching campaign file for easy testing of behavior when interacting with `json.objrolls()`, UDFs, and macros called via `macro()` roll option.  The Campaign macros panel has `json.obj()` test that fails against current build, will pass after changes applied.

[MT-2444-json-obj-rundata.cmpgn.zip](https://github.com/RPTools/maptool/files/6158355/MT-2444-json-obj-rundata.cmpgn.zip)

**Comment by Phergus** [comment] 2021-03-18 16:35
DiceLib updated to 1.7.1.

Tested.  Rolls from `json.objrolls()` now show in `getRolled()` and `getNewRolls()` results.

Normal rolls (`[r: 3d6]`, `[r: eval("3d6")]`, and `[r: execMacro("EM: [3d6]")] are still returned in `getRolled()` and `getNewRolls()` results.

**Closed** 2021-03-18 17:36 UTC
Labels: bug, macro changes, tested
