### ISSUE TITLE
[Bug]: Map-Export Map- can't cancel

### ISSUE THREAD

**Issue by Jmr3366** [RPTools/maptool#4324] opened 2023-10-07 19:04 UTC
### Describe the Bug

If you attempt to export a map, you can't cancel out of the menu and are forced to save the file.
You can choose to overwrite a file and will be prompted cancel after you've selected save

### To Reproduce

Click Map
Select Export Map

Click cancel

### Expected Behaviour

Clicking cancel will close the dialog

### Screenshots

na

### MapTool Info

v1.14.0rc2

### Desktop

Win11, Ubuntu 23.04

**Comment by kwvanderlinde** [comment] 2023-10-26 06:26
This should be fixed for 1.14. It's a new behaviour introduced in #4262, and was identified (and a fix provided) prior to the last RC.

**Closed as completed** 2023-11-03 13:56 UTC
Labels: bug

**Comment by Baaaaaz** [comment] 2024-03-06 21:30
Tried testing in 1.15.0 Beta 1 and could not reproduce the bug.  So a pass from me.
