### ISSUE TITLE
AI Pathfinding works incorrectly in closed area if it is most top-most MBL area on map

### ISSUE THREAD

**Issue by melek** [RPTools/maptool#2379] opened 2021-01-23 20:41 UTC
**Describe the bug**
With AI Pathfinding enabled, the top-most (lowest 'Y' position value) enclosed area of MBL (or VBL if VBL Pathfinding is enabled) will behave as a thicker boundary than it should all around the interior of the shape, effectively 'shrinking' the pathfinding area.

* This issue only affects closed shapes with boundaries at or slightly within the closed shape's grid intended cells.
* Any line/non-closed shape higher on the map (lower 'Y' position value) will correct the error for other shapes on the map. 
* Having MBL (or VBL boundaries if VBL Pathfinding is enabled) boundaries that extend slightly into surrounding cells also corrects the issue.
* If multiple shapes share a 'Topmost'/lowest Y value, the left-most (lowest X value) will be the broken shape.

**To Reproduce**
1. Open a new campaign. Make sure the map has a SQUARE grid.
2. Draw a grid-aligned (hold CTRL) rectangle with the Draw tool (this is just for visual aid), at least 4 cells by 4 cells in size.
3. Draw a grid aligned (hold CTRL) HOLLOW RECTANGLE of MBL perfectly around the drawn area.
4. Place any token in the center area of the shape and enable AI Pathfinding. 
5. Move the token. Note that you cannot path directly to the edges of the shape.
6. Repeat steps 2-5 with another shape ABOVE (lower Y position value) the current shape. 
7. Notice that the NEW shape blocks movement incorrectly near edges, but the original shape now works as it should.

- You can test the same with VBL and enabling VBL pathfinding.  Switching VBL pathfinding on and off may affect which closed shape is the 'topmost' and thus broken.
- If you add a non-closed shape MBL (or VBL if VBL pathfinding is enabled) above all other shapes, all AI pathfinding will work correctly.

**Expected behavior**
MBL/VBL pathfinding should not act incorrectly based on the position of the MBL/VBL, especially not relative to other MBL/VBL shapes.

**Screenshots**
![Screenshot of issue](https://user-images.githubusercontent.com/220149/105613510-d28ed700-5d77-11eb-811c-e56c4ff4d774.png)

**MapTool Info**
- Version: 1.7.0 and 1.8b2
- Install: New installs alongside many older versions.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
This came up in a game while I was DMing, so it affects players during a hosted game as well.

**Comment by kwvanderlinde** [comment] 2021-05-31 23:17
I did a deep dive on this issue and it turns out there is a lot going on to cause the observed behaviour. I'd like to share the details since I found it quite interesting how everything interacts with each other.

First of all, the *apparent* cause of the issue is that JTS incorrectly sees the top-left rectangle as being solid MBL, not hollow. This means that when we do a line check between cell centers, the line is always considered to intersect the MBL of that rectangle. The only reason that the token can be moved freely within the 3x3 innermost cells is that we skip the JTS check when we know neither cell contains any MBL. Only when one of the cells is at the boundary will it actually contain any MBL, which is when the erroneous behaviour is triggered.

Now that is only a symptom. Figuring out *why* the top-left rectangle is solid is where things get interesting. It's all got to do with how AWT `Area`s are converted to JST `Geometry`s. The process looks simple at first:
1. We get a [`PathIterator`](https://docs.oracle.com/javase/7/docs/api/java/awt/geom/PathIterator.html) for the `Area`.
2. We get JTS to consume that iterator, building polygons and punching holes in them.

The way JTS works is that it expects the `PathIterator` to produce a sequence segments that build "rings", i.e., closed loops of vertices. The first ring is always considered a "shell" (the exterior of a polygon), and subsequent rings may be considered "holes" in the polygon. A ring can only count as a hole if it is in counterclockwise order ("counterclockwise" meaning in the standard mathematical coordinate system where the y axis points up, which is the opposite of AWT). If a ring is not a valid hole, JTS will instead treat it as the shell of a new polygon. Each shell is associated with its holes in a single `Polygon`, and then all polygons will be joined together as a `MultiPolygon`.

So we can see that there needs to be some constraints on the `PathIterator` in order to work with JTS:
1. Shell paths must be produced before hole paths.
2. Hole paths must be produced in counterclockwise order.
3. Shell paths *should* be produced in clockwise order (to avoid being interpretted as holes).
4. No intervening paths can be located between the shell and its holes.

While the `PathIterator` satisfies (2) and (3), it violates (1) and (4) by producing all the holes and then all the shells.

Let's look at what happens with two 5x5 rectangles:
1. The first ring is the *interior* of the top-left rectangle. Even though it is mathematically counterclockwise (clockwise in AWT), JTS assumes it is a shell since it is the first ring.
2. The second ring is the interior of the top-right rectangle. It is mathematically counterclockwise, so JTS considers it a valid hole and applies it to the first polygon (even though they are entirely disjoint).
3. The third ring is the exterior of the top-left rectangle. This is not counterclockwise, so is not a valid hole. Instead, it is considered the shell for a new polygon.
4. The fourth ring is the exterior of the top-right rectangle. This is also not counterclockwise, so it is the shell for another new polygon.
5. The three polygons are packed into a single multi-polygon.

Since the only hole is disjoint from its polygon, what we have here is three solid rectangle: two overlapping rectangles for the top-left, and one rectangle for the top-right. If this were the end of the story, we would see that movement at the boundary of every rectangle is blocked, not just the top-left rectangle.

But of course it's not the end of the story, because we then ask JTS to apply a 1 pixel buffer to the `Geometry` (essentially some extra padding around all edges). When a buffer is a applied, JTS reprocesses its geometry. I'm not sure exactly how it does this, but it seems to be equivalent to painting all the polygons and then erasing all the holes. The end result is two-fold:
1. The overlapping rectangles in the top-left have been merged into a single polygon.
2. The misplaced hole has been associated with the third rectangle since they actually intersect.

And this gives us the behaviour observed in the bug report. In general what happens is that the first hole is always misinterpreted as a shell, and the remaining holes are attached to that fake shell. During buffering, all the holes end up with the correct shells, except the first hole which is lost to us.

# Solutions

The ideal solution would be for JST to be made more robust when consuming `PathIterator`s. As long as there is an assumption on the order of shells and holes, this problem will likely continue to exist. They already have an open [bug report](https://github.com/locationtech/jts/issues/408), which we've previously run into in the context of #1299. I may have a suggestion for a fix to offer them, but since I'm not too familiar with that project it might not be a good approach for them.

We can implement a workaround on our side by leveraging the fact that holes come before shapes and that buffering will collapse everything. Essentially we just need to reverse the order that rings are produced by the `PathIterator`, but without reverse the order of the segments within a ring. It's not too difficult to do, but it's also still not a robust solution. However, I have verified that it will give the correct results in this case.

**Comment by Phergus** [comment] 2021-06-01 01:24
Great work digging into that.

**Comment by Phergus** [comment] 2021-06-01 12:19
Testing latest changes didn't show any movement anomalies with VBL, MBL or VBL/MBL.

![image](https://user-images.githubusercontent.com/34379254/120321475-9678ff00-c2a0-11eb-92e2-35091df6364b.png)

![image](https://user-images.githubusercontent.com/34379254/120321977-29199e00-c2a1-11eb-97c6-9400db1cac68.png)

**Comment by Phergus** [comment] 2021-06-01 12:19
@melek you want to give it test?

**Closed** 2021-06-07 13:09 UTC
Labels: bug, tested
