### ISSUE TITLE
A function to return the dimension of an image from its assetID

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#949] opened 2019-11-28 10:19 UTC
**Is your feature request related to a problem? Please describe.**
It is to my knowledge impossible to get the dimensions of an image from it's asset ID. It makes it difficult to deal with images properly, for example to display an image in a frame of proper dimensions.

**Describe the solution you'd like**
A function, maybe called `getAssetProperties`, to return a json holding the properties of an asset. Right now only images are assets, so the json could be something like:

`["type":"image", "width":300, "height", 200]`

**Comment by Phergus** [comment] 2019-11-28 14:38
Technically the getTokenNativeWidth/Height functions did this but the problem is that they depend on values set on the token and sometimes the values don't represent the actual image dimensions.  Going straight to the asset for the info is the right way IMO.

**Comment by Azhrei** [comment] 2019-11-28 16:16
I’m fine with this.  But I’m thinking using the MIME type of the asset and splitting it into two fields would be easier for consumption.

I don’t know what other kinds of assets might exist in the future, but MIME types seem like a good place to start.  I can see text assets needing a character encoding and SVG ones needing a default scale, but knowing which properties to expect will be driven by MIME type...

**Comment by Phergus** [comment] 2019-11-28 17:02
Using the MIME type would be a good idea.  Too bad that the type is never set in Asset.java.  The class has a field for it and a getter but no setter.  It also has `extension` but that is only set to `null`.

It appears that the name is always set so putting the name in the JSON return might be nice.

**Comment by Azhrei** [comment] 2019-11-28 17:16
IIRC, the AssetManager also keeps track of where the asset originally came from (repo, URL, etc) so maybe that would be good to include.  I don't know that much else is tracked (like last-modified time stamp and such).  It might be that the more detailed metadata has to be looked up in the Assetmanager instead of getting it from theAsset itself...

**Comment by Phergus** [comment] 2019-11-28 17:59
I don't see any info beyond filename - without extension - being captured by AssetManager.  The .info file in the asset cache only has the filename and creation date in it.

**Comment by Merudo** [comment] 2019-11-28 23:34
PR #950: I added the subtype (extension) to the properties returned.

**Comment by Merudo** [comment] 2019-11-29 05:54
> Technically the getTokenNativeWidth/Height functions did this but the problem is that they depend on values set on the token and sometimes the values don't represent the actual image dimensions. Going straight to the asset for the info is the right way IMO.

Agreed, plus even fixed `getTokenNativeWidth/Height` wouldn't work very well for table images.

**Comment by Phergus** [comment] 2019-11-29 12:29
A good point as well.

**Comment by Merudo** [comment] 2019-11-30 12:17
I noticed getting the properties from a table gives the wrong width and height if the asset isn't loaded yet - it returns the width and height of the "loading asset" image.

I suggest replacing the method "getImage" by "getImageAndWait".

**Comment by Phergus** [comment] 2019-11-30 13:06
It does return "transferring" in the status but that puts the onus of handling the delay on the macro coder.  Is there a risk using getImageAndWait() that a macro could get hung up waiting for an image that never loads?  The CountDownLatch does a timeout on it?

**Comment by Merudo** [comment] 2019-11-30 14:07
I'm not sure about `getImageAndWait` hanging up a macro.  I know the method is used at multiple times without issues.

A timeout could be added to the `await` method of `CountDownLatch`.

**Comment by Phergus** [comment] 2019-11-30 14:41
I'd rather not add a timeout to `await`.  Switching to `getImageAndWait` is probably safe.  If there is an issue it would show up in the other places it is used as well.

Go for it.

**Comment by Phergus** [comment] 2019-12-02 16:08
Tested new change.  No problems found.

**Closed by Phergus** 2019-12-02 16:08 UTC
Labels: feature, macro changes, tested
