### ISSUE TITLE
Frame is always in front of dialogs

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#1087] opened 2020-01-06 21:47 UTC
**Describe the bug**
When a frame is open, dialogs open behind the frame. The frame cannot be moved or closed until the dialog is closed, but the dialog cannot be closed if it’s behind the frame.

**To Reproduce**
1. Open a frame.
2. Open preferences. The frame is on front the preferences
3. Try to close the frame. It can only be closed after the preferences have been closed.

**Expected behavior**
Dialogs that absolutely need an action (such as preferences, campaign properties, or the dialog to delete a macro) should open on top of every other window. In some cases, the dialog cannot be reached if there’s a frame in front of it.

**MapTool Info**
- Version: 1.5.10
- Install: Upgrade from 1.5.8,

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 10.15.2

**Comment by Phergus** [comment] 2020-01-06 22:00
Appears to be specific to MacOS.  Under Windows the Preferences, Campaign Properties, and Edit Token dialogs all open on top of open frames.

@Azhrei - thoughts?

**Comment by Azhrei** [comment] 2020-01-06 22:12
(Tested with 1.5.9 snapshot install that I had available.  Inside a dev environment might be different, so I didn't use Eclipse.)

I tried what the OP tried, and the campaign properties and preferences opened on top of all frames, floating or docked.

However, when I right-clicked on a macro in the **Campaign** panel and chose **Delete...**, it opened on top of the main window but underneath the floating **Chat** panel.  So it is confirmed, at least for that type of dialog and on macOS.

I'm doing this as my normal user account and it sometimes has other issues with MT/Java, so I'll try a fresh user account as well, just to be certain...  Yes, it happened there instead.  The **Delete...** popped _under_ the frame, and so did the **Quit** confirmation when I terminated MapTool with a keystroke.

Perhaps related to the update of the JIDE libs?  Need to go back to an older build and test there.  I'll do that later tonight if no one beats me to it.  (Don't have time to download and test right now.)

**Comment by mrkwnzl** [comment] 2020-01-18 12:43
Since I’m working a lot with frames as character sheets, this is really annoying. I’ve had it happen more than once, where I got stuck as I forgot to close the frame before editing or deleting a macro, and I had to force quit MapTool (and lost what I did), because I couldn’t reach the dialog behind it. 

Is there anything I could try to help with this issue?

**Comment by Phergus** [comment] 2020-01-18 13:19
Only thing I know if is that if the frames are docked then the dialogs can't open behind them.

**Comment by Azhrei** [comment] 2020-01-18 19:29
I was looking through the MapTool code to see if any dialogs are created without an explicit parent, thinking maybe that would have an effect.

However, it looks like it might be [this OpenJDK bug](https://bugs.openjdk.java.net/browse/JDK-7124246) or [this one fixed in JDK 12](https://bugs.openjdk.java.net/browse/JDK-8208543).

I'm going to continue to research this, but the second bug (the one fixed in JDK 12) might mean we just wait for the new Java packager to settle down and then upgrade to the latest JDK.

**Comment by Azhrei** [comment] 2020-01-18 21:35
No fix found yet.

In the meantime, when you're in a situation where the dialog is opening and it's behind other screen elements, remember that the dialog still has focus; you can press Enter or ESC to activate the OK or Cancel buttons on the dialog.  This should at least allow you to move the obscuring frame out of the way in order to continue work.

So far the only workaround I've thought of is to always place dialogs in the upper left corner of the screen on macOS.  I'm not happy with that option, of course, so I'm going to keep looking...

**Comment by mrkwnzl** [comment] 2020-01-18 21:43
Thanks for all your effort. I really appreciate it!

**Comment by Phergus** [comment] 2021-06-17 16:39
@Azhrei , @mrkwnzl  Is this still happening under Java 16?

**Comment by Azhrei** [comment] 2021-06-24 20:16
I've done some testing using 192 and I don't see the problem any more.

When I do the same operations as above (right-click on macro button and choose Delete), the dialog pops up on top of all other floating frames (I tried multiple frames placed so that they overlap each other).

I cannot close the frame while the dialog is open (which is expected for a modal dialog), but I _can_ double-click the frame to raise it above the dialog.  If the frame is larger, it will completely obscure the dialog.  However, a click anywhere within the MT window will cause the dialog to rise to the top of the stack again.  I would like the frame to always stay behind the dialog, but the current situation seems quite usable.

There's no telling if this is related to a JDK update or a JIDE update, but I consider this fixed.

**Closed by Azhrei** 2021-06-24 20:16 UTC
Labels: bug
