### ISSUE TITLE
Reloading of Map Objects

### ISSUE THREAD

**Issue by FluxIX** [RPTools/maptool#129] opened 2016-11-09 03:18 UTC
I would like a command which can destroy all of the map objects on the current map and reload them from the server.

**Comment by Azhrei** [comment] 2016-11-09 03:57
And what problem does the solve?  Isn't that the same as just clearing the cache directory under `.maptool`?  (Well, except that clearing the cache directory isn't per map.)

**Comment by FluxIX** [comment] 2016-11-09 05:47
I have noticed that sometimes when loading a map it will stop on an asset for a very long time, far longer than should be attributed to the size of the asset (I've seen it go for an hour, with application restarted between attempts in the specified time period). I think the asset is being cached but the asset loading procedure is stopped and it only continues when some internal state is cleared; clearing the map objected and having the objects reloaded would be a means of resolving such states.

**Comment by wolph42** [comment] 2016-11-09 13:39
well I can imagine that if the 'map loading proces' is stuck, that it would be nice to have a button somewhere you can click that 'solves the problem'. In this case: deletes the cache and restarts the map loading proces.

**Comment by Azhrei** [comment] 2016-11-09 14:24
Ah, I see. :)

It would be nice to have a more robust file transfer interface.  Since MT uses TCP between the server and clients, one would expect reliable delivery (a guarantee of the TCP protocol), yet it clearly doesn't work as advertised.  We should determine why and then see what we might do to correct that.

I think there's already a dialog that will tell you which files are being transferred (on the Window menu, choose **Show Transfer Window**).  However, since images are managed using their checksums, this doesn't help much.  I had planned a rewrite of the `AssetManager` code where the image name was tracked for informational purposes, but that ended up being much more work than expected and touched so much code that I didn't consider it practical.  We will likely need a rewrite of that code anyway when we move to JavaFX...

Perhaps the transfer window could include a button for each asset that would cancel the download and then add the asset to the bottom of the transfer queue, thus causing the download to start again?  Not sure how practical that is in terms of the existing code, though.

**Comment by JamzTheMan** [comment] 2016-11-18 06:51
Although not an exact solution, it sounds like just clearing your asset cache and switching maps should do the same thing although not in one go and not as easy.

For 1.4.1.x
There is a small "safe" icon, bottom right status bar, double clicking it will clear your asset cache...

**Comment by wolph42** [comment] 2016-11-18 08:03
this happens to me...once every 2 years i think. I am however not (contrary general believe) an intensive maptool user. If you apply statistics on my n=1 measurement, then overall it doesn't look good and overall its an issue! For one I think its a safe assumption that no one knows about this, save an elite few. Hence a 'safe' icon hidden somewhere in plain view won't be really helpful to anyone encountering this issue. 

That said: that clickable icon is a great addition! Saves me (and especially others) some hassle in clearing the cache!!

Overall though, I really plea for a more UF solution to this issue, e.g. like Azh mentioned.

**Comment by JamzTheMan** [comment] 2016-11-18 09:46
Oh, I agree. It's not a fix, just something for the "did you know..." list.

**Comment by Jmr3366** [comment] 2022-09-17 13:24
This request appears to originate as a hack to overcome a network communications issue.

Perhaps if it can be explained in a way that would provide benefit as a real "feature request"?  

It is 6 years old without additional information to know if this "bug" can be reliably duplicated and if it can't be, should be closed, it isn't a "reasonable" feature request as it isn't explaining the benefit.

**Comment by Phergus** [comment] 2022-09-17 15:20
Actually the more likely root cause was a failure to transfer an asset due to concurrency/threading issues.  Some of these have been addressed since then so it is possible that this no longer happens as often or not at all.  Most long time users of MT just got used to swapping maps and forcing the reload so it may just not get reported any more.

In any case, I'm going to close this for now though it wouldn't be a bad thing if there was a more convenient way to reload the assets from the server to a player clients map.

**Closed by Phergus** 2022-09-17 15:20 UTC
Labels: feature
