### ISSUE TITLE
onTokenMove does not work on tokens which are set to not visible to players

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#2176] opened 2020-08-23 14:57 UTC
**Describe the bug**
When I have a token set to be not visible to players, onTokenMove does not work, even though it’s on the token layer.

**To Reproduce**
1. Create a new campaign with a lib token (“lib:TokenMove”) and a regular token (“Eagle”).
2. Create an onTokenMove macro with the line ```[r: broadcast("It’s working!")]``` on lib:TokenMove. Alternatively, use the attached campaign in which I already did 1 and 2.
3. Move Eagle and observe the chat closely. It says “It’s working!”
4. Now set Eagle to not visible to players. (Note: Don’t move it to the hidden layer!)
5. Move Eagle and observe the chat closely. It does not say “It’s working!”

**Expected behavior**
I expect the chat to say “It’s working!” during step 5.

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade 1.6.X

**Desktop**
 - OS: macOS 10.15.5

[onTokenMove.cmpgn.zip](https://github.com/RPTools/maptool/files/5114114/onTokenMove.cmpgn.zip)

**Comment by selquest** [comment] 2020-09-05 01:53
This is working as designed, not a bug.  Presumably the thought is that tokens not visible to players can only be moved by GMs, so there's no need to enforce any kind of movement restrictions.  You also probably wouldn't want invisible tokens announcing themselves via any chat output, etc.

https://github.com/RPTools/maptool/blob/18a6a347a7ff7b53a0e951eb577929057b3e1df9/src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java#L580-L584

**Comment by Phergus** [comment] 2020-09-08 11:37
Right.  If players can't see it they can't be moving it.  For "invisible" tokens there is the `Visible to Owners Only` setting for tokens which would allow for movement control on player owned and moved tokens.

**Closed** 2021-03-12 02:38 UTC
Labels: bug, working as designed
