### ISSUE TITLE
add lumens support to Sight (Light already has it)

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1726] opened 2020-04-29 03:32 UTC
**Describe the bug**
Lights are currently capable of expressing "negative lumens", causing darkness.  There's a note in the Help text of the Campaign Property's **Light** tab that says the dark vision **Sight** is equivalent to 100 lumens.  The problem is that I have a creature that can cast darkness at lumens=-100 (per the **Light** tab) but needs to be able to see through it and can't (because the **Sight** tab doesn't have a "lumens" keyword).

**Expected behavior**
Since the **Light** tab allows negative lumens, the **Sight** tab should allow the definition of vision types that can see through it.

**MapTool Info**
- Version: 1.6.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.15

**Additional context**
I haven't looked at the code (I have no development environment installed, currently) but this may or may not be a lot of work.  Since the **Light** tab says darkvision (which should be any vision type with the **r** modifier) effectively has "lumens=100", I'm hoping there's already a field in the structure and it just needs the proper parsing in the **Sight** tab to be active. 🤞

**Comment by selquest** [comment] 2020-07-10 22:02
I'll update the various Sight/Light wiki pages to reflect these changes coming in 1.8

**Comment by selquest** [comment] 2020-07-11 17:31
Updated the "Introduction to Lights and Sights" wiki page to include the existing option of Lumens for Light Sources, and advise of the upcoming option to add them to Sight.

**Comment by Phergus** [comment] 2020-07-14 19:29
I don't think this is working as desired.

Map Vision set to Night.  No FoW.  Info token has Darkness Light with lumens=-120

GM Client - Hero token selected
![image](https://user-images.githubusercontent.com/34379254/87465669-4898d100-c5d2-11ea-86d4-87970b14d4f8.png)

GM Client - Elf token selected
![image](https://user-images.githubusercontent.com/34379254/87465717-5b130a80-c5d2-11ea-8bca-caa3f2efe221.png)

Hero Client - Nothing is visible in the area covered by the darkness as his light source is only a Lumens 100 and he has Normal vision.  The problem is that the darkness area itself is also not visible.  No indication that there is an area within his view that is covered by darkness.
![image](https://user-images.githubusercontent.com/34379254/87467270-ec837c00-c5d4-11ea-9ec4-21f3e8447221.png)

Elf Client - Has personal light with lumens=150.  Same issue as Hero.  Can't see that there is an area of darkness.
![image](https://user-images.githubusercontent.com/34379254/87467510-4edc7c80-c5d5-11ea-9b48-4b8b9af18a8b.png)

Setting the Map Vision to Day has similar issues.  The darkness area isn't visible at all on the GM client.  Only the Elf can see the darkness area that is outside of his personal light range but he can see the Wolf token which shouldn't happen unless the Day lumens value is > 120.  The Hero can't see any indication there is an area of darkness at all. His vision isn't clipped.

**Campaign File**
[SightLumensTest.cmpgn.zip](https://github.com/RPTools/maptool/files/4920869/SightLumensTest.cmpgn.zip)

**Comment by selquest** [comment] 2020-07-14 21:11
@Phergus it looks like it's handling the visible area calculation as expected, but the color of the Elf's personal light source is covering the color of the darkness source underneath it.  Interestingly, you can see this happening even for the generic 40' light source applied to the Hero here.

That doesn't seem to be related to this particular change though.  I tried reverting to the dev commit just before this PR was merged (f451a7ef26d2ea192165aaccad2440b55aeb4ce6), and we can see the same behavior there (although obviously the "Extra Darkvision" sight defined just uses the default 100 lumens at that point):
<img width="463" alt="PremergeColorBleed1" src="https://user-images.githubusercontent.com/2325887/87475683-324f3d00-c5f3-11ea-8773-082f4540ad0f.png">

Interestingly, adding an explicit color to the Elf's personal light source made it actually blend the colors as expected.  The only change made between the last screenshot and this one was setting the darkvision light source to #000000 color:
<img width="456" alt="PremergeColorBleed2" src="https://user-images.githubusercontent.com/2325887/87475971-a558b380-c5f3-11ea-80be-d0518d8cafd6.png">

I think the strangeness here then is more related to the interactions with the light source colors than any problems with adjudicating light/darkness to work out a vision area.  Maybe #1893 playing a role?

For reference, this is what it looks like on **1.7:**
<img width="394" alt="OnRelease1 7" src="https://user-images.githubusercontent.com/2325887/87476737-e604fc80-c5f4-11ea-99bc-91c75eda0e18.png">

**Comment by Phergus** [comment] 2020-07-15 02:25
> @Phergus it looks like it's handling the visible area calculation as expected,..

Yes.  Was only commenting on how the area of darkness is not visible.

> ...but the color of the Elf's personal light source is covering the color of the darkness source underneath it.

Yup and that produces the result that you can't tell where the areas of darkness are at without adding a color to each light source.  It's more of what was discussed in #1893 as you say.

**Comment by selquest** [comment] 2020-07-15 04:08
Yeah, it looks like this is a direct result of decisions made there - care is taken specifically to prevent the "dim light" with a color from applying its color to the pure white default light.  If all the lights involved have color, none of them are considered "bright" and we get the mix of visual indicators.  The fact that in this case that "dim light" actually has negative lumens doesn't change the behavior at all.  I can see arguments either way as to whether it should - I'd prefer to have the visual cue, but the initial premise of #1893 was that if your Daylight spell can overcome the darkness, you want the bright light to extend all the way into the darkness.

**Comment by Phergus** [comment] 2020-07-15 12:23
The problem is that the visual implies that the Hero's light source is illuminating the area of darkness.  The Hero player could move his token right up to or into the area of darkness without realizing there even was an area of darkness or that the apparently clear area might not be empty.  I think this will be problem.

**Comment by selquest** [comment] 2020-07-15 14:16
Well the Hero player not being able to see the darkness has always been the case - the area covered by the darkness is explicitly subtracted out of his visible area.  Now we've lost the GM's visual feedback to help explain why that's the case though.  I think it probably makes sense to have sources of darkness treated as an exception from the rendering changes in #1893.  I'll make a new issue for it, but I haven't dug into any of the actual UI painting code yet, so I'm probably not the best to try and change it.

**Comment by Phergus** [comment] 2020-07-20 01:32
Tested.  Working as designed.

**Closed** 2020-07-20 13:10 UTC
Labels: feature, tested
