### ISSUE TITLE
After disconnecting from server, Save Chat Log History... is bringing up Token as the file type filter

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#234] opened 2019-02-11 05:09 UTC
After disconnecting a Player client from the GM's server, selecting **File > Save Chat Log History...** from the menu caused the proper dialog box to open (with the title, **Save Message History**) but the file type filter at the bottom of the dialog only allowed tokens to be selected.  The actual list was Token, Token (GM Name), Token Image, and Token Portrait — which doesn't make much sense at all for file type??

Typing in a filename (`chatlog.html`) _did_ work and _did_ save the content as HTML, it's just the list of valid file types that's incorrect.

**Comment by Phergus** [comment] 2019-02-11 05:34
OS?  Java version?  MapTool version?

**Comment by Phergus** [comment] 2019-08-22 23:15
Unable to reproduce with 1.4.1.8, 1.5.0, 1.5.3.  Closing.

**Closed by Phergus** 2019-08-22 23:15 UTC
Labels: 1, bug, low, not reproducible
