### ISSUE TITLE
[Bug]: Maps with Blast, Burst or Radius templates cause an NPE when Server is started.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3594] opened 2022-09-07 01:46 UTC
### Describe the Bug

When trying to load a MapTool 1.11.5 campaign in MapTool 1.12.0 Beta 2 (after starting the server ,first), I get the following exceptions in the order listed below:

![Screenshot 2022-09-06 201719](https://user-images.githubusercontent.com/50708405/188768741-168164c4-2219-4dff-8657-ca262ad50792.JPG)

![Screenshot 2022-09-06 201739](https://user-images.githubusercontent.com/50708405/188768752-b364fae8-a61a-42b1-b6cb-131d1a9d53c1.JPG)

### To Reproduce

1. Start MapTool 1.12.0 Beta 2 (recommend not using one that you might already have running on your desktop).
2. Start the server with the following options:

![Screenshot 2022-09-06 203150](https://user-images.githubusercontent.com/50708405/188769086-087b945b-1a0b-4c19-8e5e-c0047205597f.JPG)

3. Load the "test2a.cmpgn" (unzip "test2a.zip") -- important note is that test2a.cmpgn is a paired down version saved with 1.12.0 Beta 2 of the original campaign from 1.11.5 that produced exactly the same exceptions only in MapTool 1.12.0 Beta 2 and this same file still does NOT produce exceptions in MapTool 1.11.5 even though it is now a MapTool 1.12.0 Beta 2 file:

[test2a.zip](https://github.com/RPTools/maptool/files/9501953/test2a.zip)

4. Get the following exceptions in the order listed:

![Screenshot 2022-09-06 201719](https://user-images.githubusercontent.com/50708405/188769214-4e12c1c5-0d36-4c2f-92c3-311cbb250409.JPG)

![Screenshot 2022-09-06 201739](https://user-images.githubusercontent.com/50708405/188769231-683235fa-38ba-495a-b1dc-01a58659ca6e.JPG)

### Expected Behaviour

Should not get any exceptions in MapTool 1.12.0 Beta 2.  MapTool 1.11.5 has no trouble loading this file using the same scenario outlined in my steps-to-reproduce, even though it was saved with MapTool 1.12.0 Beta 2.

### MapTool Info

1.12.0 Beta 2

### Desktop

Windows 10

### Additional Context

test2a.cmpgn started its life as a MapTool 1.11.5 campaign.  I removed the other maps and the image file used for the remaining map and saved with MapTool 1.12.0 Beta 2 to make test2a.cmpgn small enough to upload.

I carefully verified that the exceptions produced by test2a.cmpgn are the same as the exceptions I uploaded (which were captured from the original 1.11.5 campaign) -- so you can compare the images with the exceptions you get to verify for yourself that they are the same.

**Comment by adventuremagic123** [comment] 2022-09-07 01:57
The following "test2a_1.11.5_version.cmpgn" file is the same as test2a.cmpgn, except that it was created in the same way by only using MapTool 1.11.5 and saved with MapTool 1.11.5.  It causes exceptions in MapTool 1.12.0 Beta 2 but NOT MapTool 1.11.5.  Unzip "test2a_1.11.5_version.zip":

[test2a_1.11.5_version.cmpgn.zip](https://github.com/RPTools/maptool/files/9502083/test2a_1.11.5_version.cmpgn.zip)

**Comment by adventuremagic123** [comment] 2022-09-07 02:09
In "test3a_1.11.5_version.cmpgn" (unzip "test3a_1.11.5_version.cmpgn.zip"), I removed melek#4527's Lib:Elevation and Lib:SimpleDoors and disabled their overlays (see Overlay menu).  When loading that in MapTool 1.12.0 Beta 2 (again, you must start the server first because of my Hero Lab tokens), only the first exception appears -- not the second.

[test3a_1.11.5_version.cmpgn.zip](https://github.com/RPTools/maptool/files/9502155/test3a_1.11.5_version.cmpgn.zip)

**Comment by melek** [comment] 2022-09-07 21:10
It appears that somehow the zone id is null for some call. The second exception probably is probably still the same root error, just invoked one fewer times thanks to the disabled libraries. 

My guess from these errors (only a guess) is that the libraries are uninvolved. You could test if this is related to the campaign data (not any tokens) by:

1. In MapTool 1.11.5, remove all library tokens. Do not remove any maps, only tokens.
2. Save the campaign.
3. Retry your import into 1.12b2

Whether that still causes an exception that'll be helpful to isolate the issue.

**Comment by Phergus** [comment] 2022-09-07 23:20
This is another fallout from the switch to protobuf.   Maps with radius templates on them cause this because the Zone GUID isn't getting set (or is passed as null) in one of the `fromDTO()` calls.

**Comment by Phergus** [comment] 2022-09-07 23:22
This is trivial to reproduce.  A single map with a radius template on it saved from 1.11.5 when loaded into 1.12 and then starting a server.

**Comment by Phergus** [comment] 2022-09-08 22:51
Fix from PR does not stop the issue.  I've edited the bug report title to accurately describe the issue.

If an older campaign (1.11.5 or prior) is loaded and has a map with Blast, Burst or Radius templates present an NPE is produced and starting the server fails.  The `fromDto()` method in Drawable calls `setRadius()` which calls `adjustShape()` (or `adjustRectangle()` in BlastTemplate) which makes a call to `MapTool.getCampaign().getZone(zoneID)` using the Zone ID saved in the Drawable object.  However, this ID isn't in the list of Zones for the campaign and so a null is returned for the Zone.

Replacing this line in the three problem templates...
```
    int gridSize = MapTool.getCampaign().getZone(zoneID).getGrid().getSize().
```
... with the following code lets the campaign work but is a bandage over a deeper problem which is that the two different paths to get the campaign gets you two different lists of zones.
```
    if (MapTool.isHostingServer()) {
      zone = MapTool.getServer().getCampaign().getZone(getZoneId());
    } else {
      zone = MapTool.getCampaign().getZone(getZoneId());
    }
    if (zone == null) return;

    int gridSize = zone.getGrid().getSize();
```

**Comment by Phergus** [comment] 2022-09-08 22:54
Here is a simpler campaign with just one map that has the various template types on it.
(Remove the `.zip` extension.)
[Templates_1_11_5.cmpgn.zip](https://github.com/RPTools/maptool/files/9531069/Templates_1_11_5.cmpgn.zip)

**Comment by Phergus** [comment] 2022-09-09 21:41
@adventuremagic123 please confirm that this issue has been resolved with beta 3.  Thanks.

**Comment by adventuremagic123** [comment] 2022-09-14 03:21
Yes, it has.  Works for the cmpgn file I attached.

**Closed** 2022-09-14 04:14 UTC
Labels: bug, tested
