### ISSUE TITLE
Client Does not Update until Interaction

### ISSUE THREAD

**Issue by FeralBytes** [RPTools/maptool#480] opened 2019-05-23 23:06 UTC
OS: Linux
Server Linux Mint 19.1
Client on Linux Same Machine as Server

Running the client on the same machine as the server. The client does not update to changes made on the server unless I interact with the client screen.

**Comment by Phergus** [comment] 2019-05-24 01:08
MapTool version?

At all?  No token movement, vision updates, map changes, nothing?

@rkathey Have you seen this?

**Comment by FeralBytes** [comment] 2019-05-24 04:17
MaptTool Version: 1.5.2

**Comment by rkathey** [comment] 2019-06-03 14:41
I'm running 1.5.2 on Ubuntu 18.4 and do not experience this problem.

Did you install the .deb file or are you running from the jar file?

**Comment by FeralBytes** [comment] 2019-06-05 05:43
I used the .deb and downloaded and installed it via [this}(https://github.com/RPTools/maptool/releases/download/1.5.2/maptool-1.5.2.deb). I also had a friend over and he was the GM/DM and he runs a mac book pro and it connected to my laptop as the server, and when he changed things they updated automatically. So it appears to be only on the same machine as client and host that I have the problem. If you can not reproduce it, then it may not be worth investigating.

**Comment by Phergus** [comment] 2019-06-05 12:41
That's really odd.  I run server and client on the same machine all the time as part of testing campaigns and testing MT.  I can't reproduce this but I am on Windows.

To be clear, with a player and server clients running on the same machine, and both visible, token movements or FoW reveals done on the server do not appear on the player client until you make the player client active?  Does the client then fully catch up to events?

When the player client is connecting, is it using the LAN tab or the Direct Connect tab?

If Direct Connect, are you using the LAN IP or 127.0.0.1 or what?

**Comment by FeralBytes** [comment] 2019-06-06 20:28
On Linux I have one on a separate workspace so not technically both visible at the same time, or not side by side. For the second part of that question, yes, no screen updates until I click into the client window, then the client fully catches up.
I used the LAN tab to connect the client. 
But will have to try a direct connection to localhost and the LAN IP.

**Comment by Phergus** [comment] 2019-06-06 20:58
> On Linux I have one on a separate workspace so not technically both visible at the same time, or not side by side.
That's a pretty significant bit of information that has been missing.  Is it documented that applications on the not visible workspace should continue to update their GUIs even though they aren't visible?

> I used the LAN tab to connect the client.
> But will have to try a direct connection to localhost and the LAN IP.
That shouldn't matter but it may tell us something if it does.

**Comment by Azhrei** [comment] 2019-06-06 23:24
I haven't used Mint since about 17.x, but I can install a VM and try it this weekend.  It's really strange — it sounds like the GUI isn't spending any cpu time on updating the display until an application in that workspace is given the focus, which is... weird.

What about other applications?  For example, if you open a Terminal in a different workspace and run this command, when you switch away, wait 10 seconds, then switch back, has the output been continuous?  Or does it not update until you click in the Terminal window?

    while sleep 1; do date; done

(You can kill it with Ctrl-C when you're done.)

**Comment by FeralBytes** [comment] 2019-06-12 06:14
@Azhrei Sorry for the delay in responding. I ran your test and yes the output was continuous, it does not seem that Linux Mint Cinnamon is Pausing the windows on different workspaces.

**Comment by Azhrei** [comment] 2019-06-12 15:06
Okay, then it’s likely not an issue with the GUI itself, but just the application.  Strange we haven’t heard it from other Linux users.  We’ll have to try to recreate it ourselves.

Which desktop GUI did you choose?  Are you running 32- or 64-bit?  Is there anything beyond a generic install of 19.1 that I should do to create the same environment?

**Comment by FeralBytes** [comment] 2019-06-12 17:32
Linux mint 19.1 64-bit Cinnamon. This is an upgrade from 18.1. it is also my dev machine. I will try maptools on my wife's computer in a few weeks when I get back. Because this is a dev machine but could be something I did at some point, too many factors. If you can't reproduce on a clean install then don't worry about it.

**Comment by Azhrei** [comment] 2019-06-13 22:08
Okay, downloading 19.1 Cinnamon now.  I'll try playing with it during the game tonight. ;)

**Comment by FeralBytes** [comment] 2019-06-13 22:55
Thanks you are going above and beyond. If you can't reproduce I recommend we close this as something up with my dev machine.

**Comment by Azhrei** [comment] 2019-06-15 05:48
You'll be glad to know (or maybe not?) that a fresh install of 19.1 64-bit Cinnamon exhibits the same behavior in my VirtualBox VM.  I configured it with 2 cpus and 2GB of RAM with the VMSVGA driver with 3D acceleration enabled (those video settings are the defaults).  The next step will be to determine _why_...

**Comment by Azhrei** [comment] 2019-06-15 05:59
Just tested on a fully updated macOS Mojave laptop and it happens there as well, although it's a little less noticeable.  When I switch to another workspace (called a "Space" on macOS) by clicking the application icon in the dock, the display switches to the app in the other Space _and_ updates the screen.  This is likely because the GUI is activating the window, ie. giving it focus.

I'm guessing that the Java runtime doesn't bother to process the event queue while the window is not displayed (which is reasonable) but giving the window focus forces it to update.

Thanks for reporting this.  This could be an issue in a MapTool server meant to be used headless, ie. without a display attached.

**Comment by FeralBytes** [comment] 2019-06-16 03:55
@Azhrei Thanks for digging into the problem. I am glad to know that it is not just my computer. I look forward to a fix, when you are able. Thanks for making great software.

**Comment by Phergus** [comment] 2019-08-16 11:59
@Azhrei - Any further thoughts on this?

**Comment by Azhrei** [comment] 2019-08-16 15:36
Nothing specific.  My next step was to add some logging in the rendering thread (and maybe the network thread) to indicate when events were arriving and being processed.  Maybe the rendering is still happening within MT and it’s just Java that’s letting the queue fill up without processing...

If the above is true, then at some point this “queue” could fill up to the point that Java is forced to flush it even when the window isn’t being displayed (something to test).  It also may be possible for us to set the size of the queue to ameliorate this a bit (although I’d be hard-pressed to think I know better than the Java GUI stack developers about the best setting for the general case).

Honestly, this had dropped off my radar.

Since the window isn’t displayed, I don’t really see it as a huge problem.  Perhaps document it so that it doesn’t surprise users, but close the issue?

**Comment by Phergus** [comment] 2019-08-16 16:01
It does seem to be a bit of an edge case.

Will defer it for now and it can be revisited after the GUI rework for 2.0.

**Closed by Phergus** 2019-08-16 16:01 UTC
Labels: deferred, investigating
