### ISSUE TITLE
getTokens() visibility is based on client's view position

### ISSUE THREAD

**Issue by SterLovesFood** [RPTools/maptool#2667] opened 2021-05-21 19:28 UTC
**Describe the bug**
The parameter 'visible' on the getTokens() function will not return tokens that are not on the users active screen based on where they are personally currently looking. 

**To Reproduce**
1. Create a getTokens() function on a token using the 'visible' parameter. 
```
[h: cond = '{ "range": {"upto":99, "distancePerCell":0, "token":"' +getSelected()+ '"}, "visible":1}']
[r: ids = getTokens("json", cond)]
```
2. Run the macro. Move your viewport away from all other tokens or zoom in to an area to exclude tokens from your view and run the same macro for new results.

**Expected behavior**
I would personally prefer if visibility strictly referred to the visibility based on the sight of the current token, not the users viewport. This may not be the expected case for some, so this truly being a bug could be subjective.
I'm not sure how deeply rooted this situation is as it likely digs into how Fog of War and VBL dictate what is visible.

**MapTool Info**
- Version: 1.8.5 and earlier

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10.0.19042

**Additional context**
If this isn't considered a bug, hopefully it can still start some discussion on this behavior.

Here is an example of how this has effected my framework:
I have some macros that create a 'confusion' state which randomly selects a target from all currently visible targets so that a player can no longer choose their target. I noticed that you technically could just zoom into the target you wanted to hit so that it is the only one you can see and it would be the only viable option to be attacked due to how this works. If visible is set to 0, you would start attacking enemies through walls that you actually can not see.
Also the longer range an ability is, it becomes much more likely that a player just doesn't have all possible targets on their current screen.

**Comment by Irarara** [comment] 2021-05-21 21:26
This is almost certainly a bug. Right now it's just using the list of tokens that are to be rendered, hence the issue. That said, I definitely think it's worth talking about what visible is supposed to mean here.

Is it supposed to be what is visible to the client right then? This is technically the current behavior. but even if you include stuff off screen, that's kind of weird because what is visible is something that can change depending on what token is being selected if token vision is in play (that may be fine in the case where you're only ever running the macro on a selected token like in your example, but that might not always be the case).
Is it visibility with regards to a specific token? Then the ID of the token whose vision is being checked against needs to be a parameter.
Is it about the visibility flag? Well... then that'd be pretty simple, but not what most probably want here (and doesn't seem like what the filter is supposed to be limited to, despite what the wiki says).

Also, `getVisibleTokens()` has the same behavior.

**Comment by Phergus** [comment] 2021-05-23 12:24
Neither `getTokens()` with `visible:1` nor `getVisibleTokens()` are based on token vision.  The wiki docs for both says it is about what the *player* can see.    I believe Craig added this function way back when and that it is working as intended.

To get if a token is visible based on vision/LOS/FoW, you would have to filter the list returned by `getTokens()` with `canSeeToken()`.

**Comment by Irarara** [comment] 2021-05-23 13:16
If it's working as intended then the documentation at least should probably be updated to reflect that. The documentation for `getVisibleTokens()` states that it "returns a string list or JSON Array of token ids for the tokens that are visible to the player." I guess you could read that as meaning "tokens visible on screen at the moment of execution", but I (and I think most others) would reasonably interpret that as meaning tokens the player can see period. Meanwhile, the documentation for the `visible` param for `getTokens()` states that it's only based on the visibility flag.

**Comment by Azhrei** [comment] 2021-05-23 16:51
I can see why the docs might be confusing and you're welcome to edit and clarify that page (it _is_ a wiki, after all!).

In general, I don't think it's practical for the docs to rehash every factor that might influence the operation of a macro function, though.  For example, when you clarify those docs, are you going to add a note about how the map has a vision distance limit?  Are you going to mention the various interactions between vision and light?  Will you mention that tokens can have VBL on them and movement of such tokens can have an effect on the results?  What changes occur when Strict Token Ownership or Individual Views are turned on/off on the server?  And those are just the ones I can think of off the top of my head.

Given that it's not practical for the function to actually return all tokens that might be visible to a particular token (consider the overhead in calculating VBL between the selected token and all other tokens at any distance), it does what _is_ practical.  At some point, I suppose a second function could operate as you want but it would need a large caveat that the operation could be very slow (and such a function would need to reimplement the VBL process of the renderer).

**Comment by FullBleed** [comment] 2021-05-27 21:27
> I would personally prefer if visibility strictly referred to the visibility based on the sight of the current token, not the users viewport. 

I agree.  Sometimes, as a GM, I'm working with a very small viewport with various panels open.

**Comment by Phergus** [comment] 2021-05-29 13:48
The `visible` option is working as designed.  Changing the behavior of the option now could negatively impact it's use in existing macros/frameworks.

I've updated the wording on both [getTokens()](https://wiki.rptools.info/index.php/getTokens) and [getTokenNames()](https://wiki.rptools.info/index.php/getTokenNames) to perhaps remove some of the confusion.

A new option (`isVisibleTo`?) could be added that would filter the results based on token vision by passing an array/list of token names/IDs.  Should probably enforce a max range based on lesser of map vision distance or the token(s) current vision.  If desired a new Feature Request should be opened.

**Comment by bubblobill** [comment] 2021-06-10 12:55
I find this concerning. I use getTokens() with filters for range and visibility to obtain all tokens visible to the character within the desired range. If it doesn't work that way I have things to rewrite.

**Comment by Jmr3366** [comment] 2022-09-17 12:31
This should be closed as confirmed working as designed.  If something more is desired, that would be a feature request.

**Comment by Phergus** [comment] 2022-09-17 12:48
Agreed.  Closing.

**Closed by Phergus** 2022-09-17 12:48 UTC
Labels: bug, working as designed
