### ISSUE TITLE
Theme is not applied at menu bar and menu items

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#1613] opened 2020-04-19 02:59 UTC
**Describe the bug**

Theme in config directory is not applied at menu bar and menu items.

When I copy  a theme file in `.maptool-rptools/theme/ui/Default.theme` to my user directory (%userprofile%), such items are showed well.

**Screenshots**

Select "Default" theme.  
![select-default](https://user-images.githubusercontent.com/29275/79678212-e3804a00-8233-11ea-8722-fe307bff5ef1.png)

Copy "Default" to user directory.  
![default-in-user-dir](https://user-images.githubusercontent.com/29275/79678210-e24f1d00-8233-11ea-9b32-1b1d7270c79c.png)

**MapTool Info**
- Version: 1.6.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
 - Language: Japanese

**Comment by Phergus** [comment] 2020-04-19 04:06
> Theme in config directory is not applied at menu bar and menu items.

What do you mean by _config directory_?

And why are you copying them?  You just have to select the theme from the Theme menu and the next time you start MapTool it will use that theme.

**Comment by fw** [comment] 2020-04-19 06:00
> > Theme in config directory is not applied at menu bar and menu items.
> What do you mean by _config directory_?

I mean _config directory_ as _`user directory/.maptool-rptools`_. _user directory_ is %userprofile% dir in Windows.

> And why are you copying them? You just have to select the theme from the Theme menu and the next time you start MapTool it will use that theme.

I know theme switching feature in MT 1.6+ and tried switching all themes.

After installed MapTool, I recognized menu is broken (the first image attached above), however, many items displayed correctly japanese more than 1.5.x.

So I wanted to manage to show correctly japanese in menu, put theme file which I made for 1.5.x, that is good for japanese,  to `.maptools-rptools/theme/ui` and switched my theme, but there ware broken display in only menu. I made theme file by using TinyLaF 1.4.

I put the theme (editted by me) in user directory, and then menu was showed correctly in japanese. All components except menu looked selected theme.

As I guessed that `Default.theme` in `theme/ui` included by MapTool 1.6.1 has capability to display japanese correctly, tried copy this theme to user directory. And then, I got a good showing (the second image).

**Comment by Merudo** [comment] 2020-04-19 11:56
I can reproduce.

1) Switch language to Japanese, restart MapTool. Notice the menus are all garbled up.
2) Copy Default.theme from `C:\Users\myself\.maptool-rptools\themes\ui` to `C:\Users\myself`
3) Restart MapTool. The menus are correctly displayed in Japanese

**Comment by Phergus** [comment] 2020-04-19 12:31
These is another side-effect of the issue seen in #1513  where the theme was being loaded after the menus were created.

**Comment by Merudo** [comment] 2020-04-19 12:59
I tested and the fix for #1513 also fixes this :).

**Comment by Phergus** [comment] 2020-04-19 13:38
@Merudo  with current code and language set to Japanese, the menus are correct but the EditToken dialog is throwing an exception when I open it.

![image](https://user-images.githubusercontent.com/34379254/79689129-0862c600-8210-11ea-9b00-ba34f716859d.png)

Which is this line in OwnerListModel.java
`Set<String> ownerSet = getModel().getOwners();`

Suggests that the `model` hasn't be set.

Doesn't happen in English, French or Spanish so I'm guessing there is a translation issue.

**Comment by Merudo** [comment] 2020-04-19 15:45
Found out the issue.

The problem is that the title of the VBL subpanel is used directly in `EditDialog.java`. Changing the title thus break the code.

Example: `tabbedPane.indexOfTab("VBL")`

**Comment by Phergus** [comment] 2020-04-19 15:58
The woes of trying in allow for translations.

**Comment by Merudo** [comment] 2020-04-19 16:03
PR #1624 fixes this.

**Comment by Phergus** [comment] 2020-04-20 01:22
Tested.  Menu issue was fixed in #1513 .   Edit Token dialog crashing was fixed with PR #1624.  PR #1619 updates Default and MT_Flat_Green_Sans_13 themes to use a font with a more complete character set.

**Closed** 2020-04-20 19:40 UTC
Labels: bug, tested
