### ISSUE TITLE
Input() display bug

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1441] opened 2020-04-01 04:02 UTC
**Describe the bug**
Since PR #1289, the `input` dialog is displayed incorrectly when minimal input prompts or restricted widths are used.

**To Reproduce**
1. type `[H: input("junk|a|a")]`
2. Compare the output of the macro in 1.6.0 to 1.5.14.

**Expected behavior**
The `input` is not displayed worse than in 1.5.14.

**Screenshots**
From aliasmask:

1.6.0 beta 1:
![1 6](https://user-images.githubusercontent.com/7371085/78098099-b9113e80-73a3-11ea-973a-fbdfdc9dd3ac.png)

1.5.14:
![1 5 14](https://user-images.githubusercontent.com/7371085/78098110-be6e8900-73a3-11ea-9261-cbb033b0584f.png)

**MapTool Info**
- Version: 1.6.0 beta 1, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Phergus** [comment] 2020-04-01 12:52
From what I can tell this is dependent on the overall length of the input field which is somewhat dependent on prompt.  The example above shows the issue but this does not.
`[input("junk|a|bbbb|TEXT")]`
Change it to:
`[input("junk|a|bbbb|TEXT|WIDTH=4")]`
And it does.

So it appears that the container for the input fields is not filling the minimum window size horizontally.

**Comment by Phergus** [comment] 2020-04-01 12:54
@emmebi You want to take a look at this?

**Comment by emmebi** [comment] 2020-04-01 13:16
Yeah sure, assign it to me.

**Comment by Merudo** [comment] 2020-04-03 20:31
Great job!

**Comment by JamzTheMan** [comment] 2020-04-11 01:18
![image](https://user-images.githubusercontent.com/8051654/79031949-486ade80-7b68-11ea-8ddd-e21fdb3f7227.png)

Looks like a similar issue. With 150% windows display scaling, dialog breaks. Turning display scaling off and dialog displays ok.

**Comment by emmebi** [comment] 2020-04-11 05:40
Two questions:
- what do you mean with windows display scaling?
- does the bug reproduces with the following input()? If not, can you share a macro showing the bug? 

```
[H: input("tab|tab|tab|tab","label|A really wide label to show how the bottom space changes.|tab|label",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab",
"tab|tab|tab|tab"
)]```

**Comment by Phergus** [comment] 2020-04-11 12:46
Under Display Settings on Windows there is a setting to scale the UI.  This is used on Hi DPI displays to increase the size of the UIs for not only Windows but other applications.
![Screenshot 2020-04-11 06 35 19](https://user-images.githubusercontent.com/34379254/79043855-2ea8b600-7bbf-11ea-8556-83c79403d250.png)
The screenshots Jamz posted were from a user on Discord.   The working was version was huge. Must have been 50 different input fields and check boxes.

**Comment by emmebi** [comment] 2020-04-11 13:14
Checking on the latest development release, screen at 150% zoom:

```
[h: m_l = ""]
[for(i, 0, 20), code: {
	[h: m_l = listAppend(m_l, "tab|tab|tab|tab", "##")]
	[for(j, i * 20, i * 20 + 20), code: {
		[h: m_l = listAppend(m_l, "i_"+ j + "|0|input " + j + "|text", "##")]
		
	}]

}]
[h: input(m_l)]
```

This creates 20 tabs, each with 20 controls inside. 

![multi-input](https://user-images.githubusercontent.com/1532349/79044713-a8ac5f80-7bfe-11ea-850a-3701a0ba64c8.png)

**Comment by Phergus** [comment] 2020-04-11 13:26
Yeah.  I can't reproduce it here on 1.5.14, 1.6.1 or dev.

**Comment by emmebi** [comment] 2020-04-14 18:17
@JamzTheMan can you provide more context here?

**Comment by JamzTheMan** [comment] 2020-04-14 19:19
I'm unable to replicate this myself on my HDPI so not sure.  I contacted the user to see if I can get details...

**Comment by JamzTheMan** [comment] 2020-04-14 19:49
Ok, got some more details.  The user does have multiple monitors, one is a 1080p and the other is HiDPI with the display scaling at 150%.  Maybe multiple monitors is key? (no idea why)

I'll continue to see if I can replicate on my end.

**Comment by JamzTheMan** [comment] 2020-04-14 20:08
From the user:
> So, as long as my Samsung is not the main monitor scaling doesn't matter.
If the LG 1080p is the main I can have them both scaling and it works fine, If I have the Samsung as the main it has to have no scaling or it causes the issue.  

The above macro worked fine btw. So, if you can, download my First Edition campaign from http://maptool.nerps.net

On first map `0. Camp` I put a token `Thyiggs Glanmek` on it.
On the token, there is a macro `Click me then click link in chat` that will bring up the dialog that breaks. (It's also on the character sheet `Attack` tab/sheet, clicking any weapon brings up the same dialog)

**Comment by Phergus** [comment] 2020-04-15 14:05
Has he tried the HiDPI settings on the MapTool.exe properties?

**Comment by Merudo** [comment] 2020-04-17 11:20
@Wolph42 is having the same issue:

![input](https://user-images.githubusercontent.com/7371085/79564001-7756e800-8073-11ea-8f15-e6031a11bb19.png)

**Comment by wolph42** [comment] 2020-04-17 11:33
Here's the corresponding code:
[h:status = input(
    "junk|<html><b>New Token</b></html>|-|LABEL|SPAN=TRUE",
    nameList+"||PROPS|SPAN=TRUE SETVARS=UNSUFFIXED",
    "isNPC|PC, NPC|<html>Type</html>|RADIO |SELECT="+isNPC(),
    "token.visible|"+token.visible+"|<html>Visible</html>|CHECK",
    "SuddenDeath|"+if(suddenDeathRule && isNPC(), 1, 0)+"|<html><span title='<html>When you turn this on then the token means will die when the Wounds go below 0, so no critical hits</html>'>Sudden Death</span></html>|CHECK",
    "propertyType|"+typeList+"|<html>Token Property Type</html>|LIST| VALUE=STRING SELECT="+listFind(typeList,getPropertyType()),
    "fateType|"+fateList+"|<html>Type of Favour</html>|LIST |SELECT="+getLibProperty('hasFate','lib:DH')+" VALUE=STRING",
    "Size|"+sizeList+"|<html>Size of Token</html>|LIST |SELECT=3",
    "sightName|"+sightList+"|<html>Sight type of Token</html>|LIST |SELECT=1 VALUE=STRING",
    "newOwner|"+ownerList+"|<html>Owner</html>|LIST |VALUE=STRING"
)]
[h:InitToken = if(status,0,1)]
[h:abort(status)] 

This is on a HP laptop 1920x1080 (if that matters

**Comment by Phergus** [comment] 2020-04-17 16:27
With malformed PROPS line:
![Screenshot 2020-04-17 09 13 56](https://user-images.githubusercontent.com/34379254/79591514-df1e2a80-8095-11ea-8858-ea6e16bd4153.png)
With fixed PROPS line:
![Screenshot 2020-04-17 10 25 27](https://user-images.githubusercontent.com/34379254/79591589-fa893580-8095-11ea-8f1d-37ad00715e97.png)

**Comment by emmebi** [comment] 2020-04-18 10:18
Looking into this. I wonder if SPAN could have something to do with it.

**Comment by emmebi** [comment] 2020-04-18 10:43
Tried this up to 300% with Nerps campaign, but I was unable to reproduce this.

Checking the HiDPI settings, if this could help.

**Comment by emmebi** [comment] 2020-04-18 10:51
I don't have any specific DPI for Maptool (so both Program DPI and High DPI scaling override are unset).

@wolph42 @JamzTheMan what are your settings here? 

Next test for me: changing the main display and see if this changes anything.

**Comment by emmebi** [comment] 2020-04-18 10:59
Switching the main display doesn't show the issue (tested with wolph42 macro)

**Comment by Merudo** [comment] 2020-04-18 11:27
Another thing I noticed is that comma `,` is not longer allowed in the option of `input()`.

For example, this works in 1.5.14 but not in 1.6.1:

```
[h:status=input("feature|Hunter's Quarry, Sneak Attack, Warlock's Curse|Type of Striker Damage|LIST|SELECT=0, VALUE=STRING")]```

**Comment by Phergus** [comment] 2020-04-18 13:11
The wiki docs specify spaces to separate the items in the Options list.

**Comment by wolph42** [comment] 2020-04-19 11:22
@emmebi which settings are you referring at? I was testing the above on a 'normal' laptop with (irc) 1080p lines. The windows text zoom was probably set to 125 or 150%. 
I'm now testing my 'test' macro on another pc and the issue doesnt' show. 
However the original macro *does* show the issue. so my test macro is unusable to test this. I'll try to make another one. 

ok, done. This one does show the issue:
====

[h:GM_Name 		= ""]
[h:typeList		= "Character, Horde, Vehicle, Ship, Army, Grenade, Teleport, None"]
[h:nameList		= if(isGM(),"Names|Name="+token.name+"; GM_Name=","Names|Name="+token.name)]
[h:sizeList		= "Miniscule, Puny, Scrawny, Average (Human), Hulking (Space Marine), Enormous, Massive, Immense, Monumental, Titanic"]
[h:setSizeList	= "Diminutive, Tiny, Small, Medium, Large, Huge, Gargantuan, Colossal, Colossal, Colossal"]
[h:sightList 	= "None, Normal, Short, Narrow, Infra-red Goggles, Photo Visors, Dark Sight"]
[h:fateList 	= "None, Infamy, Fate", "None, Fate"]
[h:players		= getAllPlayerNames()]

[h:gmName		= "god"]
[h:gmIx			= listFind(players, gmName)]
[g:gmNameOrig	= listGet(players, gmIx)]
[h:players		= listDelete(players, gmIx)]
[h:ownerList	= listAppend(gmNameOrig, players + ", None")]

[h:abort(input(
	"junk|<html><b>New Token</b></html>|-|LABEL|SPAN=TRUE",
	nameList+"||PROPS|SPAN=TRUE SETVARS=UNSUFFIXED",
	"isNPC|PC, NPC|<html>Type</html>|RADIO |SELECT="+isNPC(),
	"token.visible|"+token.visible+"|<html>Visible</html>|CHECK",
	"SuddenDeath|"+if(1 && isNPC(), 1, 0)+	"|<html><span title='<html>When you turn this on then the token means will die when the Wounds go below 0, so no critical hits</html>'>Sudden Death</span></html>|CHECK",
	"propertyType|"+typeList+"|<html>Token Property Type</html>|LIST| VALUE=STRING SELECT="+1,
	"fateType|"+fateList+"|<html>Type of Favour</html>|LIST |SELECT="+1+" VALUE=STRING",
	"Size|"+sizeList+"|<html>Size of Token</html>|LIST |SELECT=3",
	"sightName|"+sightList+"|<html>Sight type of Token</html>|LIST |SELECT=1 VALUE=STRING",
	"newOwner|"+ownerList+"|<html>Owner</html>|LIST |VALUE=STRING"
))]

**Comment by emmebi** [comment] 2020-04-19 11:30
Still not able to reproduce the issue, apparently: 

![macro1](https://user-images.githubusercontent.com/1532349/79686563-3e687000-8239-11ea-8365-ede0f2ff0f0d.png)

As for the settings:

Right click on MapTool (from the Task bar) -> right click on MapTool again -> Properties -> Compatibility -> Change high DPI settings

**Comment by wolph42** [comment] 2020-04-19 11:41
you were too quick, I edited the post read the bottom part!!
as for the dpi settings: everything in there is checked off.
Im currently pin pointint the issue

**Comment by emmebi** [comment] 2020-04-19 12:11
I am trying with and without HTML tags, but I am still unable to reproduce the issue. Checking if on a second monitor something changes.

**Comment by emmebi** [comment] 2020-04-19 12:13
This is the sample campaign I have used. Extension changed to make github happy.


[html_nothml.zip](https://github.com/RPTools/maptool/files/4498915/html_nothml.zip)

**Comment by emmebi** [comment] 2020-04-19 12:52
@wolph42 ^^

**Comment by wolph42** [comment] 2020-04-19 14:14
If I copy paste that above code in the chat of a clean session in maptool 1.6.1 I get
<img width="207" alt="Screenshot 2020-04-19 16 14 09" src="https://user-images.githubusercontent.com/19568714/79690066-d9bd0d80-8258-11ea-92ba-4857dc9cc2e9.png">

**Comment by JamzTheMan** [comment] 2020-04-19 14:33
FWIW for my player it only happen with the right config of multiple monitors and which one was primary doing with one being hidpi and the other just s 1080p monitor. Def a strange animal to fix.

**Comment by emmebi** [comment] 2020-04-19 14:40
Wild ideas here: is it possible that Direct3D/OpenGL has something to do? I can't reproduce the issue so far (I have only one monitor + laptop, however).

**Comment by wolph42** [comment] 2020-04-19 14:49
reminds me of the issue with macro errors in MT. Nested macro errors were ignored by MT on my PC, but not on another PC. meaning that I was convinced it was working and then got all kinds of error reports that puzzled me...until I learned about the console...old days...

**Comment by Phergus** [comment] 2020-04-19 14:49
Using code posted above I get:
![image](https://user-images.githubusercontent.com/34379254/79690981-7e6c2a80-821a-11ea-89bc-1312a45468b4.png)
This is on a HiDPI (3840x2160) display.  Display scaling set at 100%.

**Comment by wolph42** [comment] 2020-04-19 14:51
ok, so its a local dependent issue...nice... note that i have this issue and im also behind a 3840x2160 screen. so not sure that's the issue. I *do* have a dual screen setup with a small screen next to the big one.

**Comment by wolph42** [comment] 2020-04-19 14:52
hmm jave version related maybe?? what version do you have?

**Comment by emmebi** [comment] 2020-04-19 14:53
I am using 10.0.1 (the one bundled with MapTool)

**Comment by wolph42** [comment] 2020-04-19 14:54
ah right...its bundled, never mind, pointless question

**Comment by emmebi** [comment] 2020-04-19 14:54
what Gather Debug Information reports?

**Comment by emmebi** [comment] 2020-04-19 14:55
Here is my idea: let's create a new version with this patch reverted; if the issue still shows, then it's this patch, and even if we don't understand why for the moment, we can try to create a workaround; if it isn't, we can continue looking.

**Comment by wolph42** [comment] 2020-04-19 14:56
was already starting up to check it ;)

==== MapTool Information ====
MapTool Version: 1.6.1
Max mem avail..: 3 GB
Max mem used...: 308 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
PATH...........: Number of Procs: 16

==== User Information ====
User Name: Rolph
User Home: C:\Users\Rolph

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

==== Locale Information ====
Country.: United Kingdom
Language: English
Locale..: English (United Kingdom)
Variant.: 

==== Encoding Information ====
Default Locale:   en_GB
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 3840x2160(32)
Display 2: 1280x1024(32)

==== Internet Gateway Devices ====
	No IGDs Found!

**Comment by Phergus** [comment] 2020-04-19 15:03
Tested with 1.4.0.5 and 1.5.0.  Get same expected result.

Weirdly, when I did the 1.5.0 test and then closed MT, the display freaked out, leaving like partial images of windows behind.  Had to reboot.  Now can't reproduce it.

This is so weird.

**Comment by Phergus** [comment] 2020-04-30 22:33
This also came up in Discord today and removing the HTML tags in use in the input() fixed it for the person there.
https://discordapp.com/channels/296230822262865920/296657960720007169/705542939174240319
This was also a situation with multiple monitors.

**Comment by Phergus** [comment] 2020-05-01 00:43
And apparently this fixed it.
![thesesettingsfixit](https://user-images.githubusercontent.com/34379254/80772026-837e8300-8b12-11ea-8d58-2f471318c397.png)

**Comment by Phergus** [comment] 2020-05-03 18:12
The layout issue appears to be a OS/Display Drivers issue that can be fixed on the user side as noted above.

Tested and working as expected.

**Closed** 2020-05-03 21:13 UTC
Labels: bug, macro changes, tested
