### ISSUE TITLE
MapTool 1.8b2 doesn't start in Japanese environment in Win10

### ISSUE THREAD

**Issue by fw** [RPTools/maptool#2214] opened 2020-09-09 12:10 UTC
**Describe the bug**
In Japnese environment in Windows 10, MapTool 1.8.0 beta 2 does not start.

**To Reproduce**
1. Install MapTool 1.8.0 beta-2
2. Starting MapTool.
3. In detail tab on task manager, MapTool process is showed for a while, but dosen't open MapTool window nor splash screen.
4. A "hs_err_pid####.log" file is appeared in installed directory.

[hs_err_pid48756.log](https://github.com/RPTools/maptool/files/5194953/hs_err_pid48756.log)

**Expected behavior**
Launching MapTool normally.

**Screenshots**

**MapTool Info**
- Version: 1.8.0 beta 2
- Install: New, by msi installer

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 Pro 1909

**Additional context**
Change language environment of Windows to English.
Then MapTool starts correctly.

In macOS Catalina in Japnese environment, MapTool launces normally.

**Comment by Phergus** [comment] 2020-09-09 13:21
There are two config files:
- User home dir under `.maptool-rptools\config`
- Install dir under `app`

Both are named maptool.cfg.  If you change the language in them both to `en` will it start?
This line under Java Options:  `-Duser.language=en`

If you change both to use `ja` what happens?

Looks like it's a problem getting a font but I'm not sure why since that code didn't get touched.

**Comment by fw** [comment] 2020-09-10 04:53
I tried it.
When both options specified `en`, MapTool starts with English interface.

When both options specified `ja`, MapTool does not start.

**Comment by Phergus** [comment] 2020-09-10 14:04
Okay.  We'll have to dig into it.

**Comment by Phergus** [comment] 2021-02-07 17:04
Needs to be retested under current 1.8 beta code but will likely get attention in 1.9.

**Comment by Phergus** [comment] 2021-03-12 02:36
@fw  have you tested with 1.8.3?  You will need to set the `user.language` option manually.

**Comment by fw** [comment] 2021-03-19 17:05
@Phergus ,
I tried to start MapTool 1.8.4 with ``-Duser.language=xx`` in ``install-dir/app/MapTool.cfg``.
(cfg file wasn't exists in ``%USERPROFILE%/.maptool/config``, so I didn't edit it.)

MapTool starts with English interface normaly, when I specified ``en``.

MapTool does not start, when I specified ``ja``.
(MapTool process appeared at Task Manger for a few seconds and disappeared.)

**Comment by Phergus** [comment] 2021-03-19 17:23
Confirmed.  In the install directory is probably a file like `hs_err_pid13764.log`.  Go ahead and attach it to a reply.

MT gets the error with/without the Japanese translation file so that's not it.  Other languages including Chinese are working fine.

**Comment by fw** [comment] 2021-03-20 05:59
I understand. Is this it?
[hs_err_pid29992.log](https://github.com/RPTools/maptool/files/6174971/hs_err_pid29992.log)

**Comment by Phergus** [comment] 2021-03-20 12:16
That's it.  Thanks!  Appears to be a font issue during startup.

**Comment by Irarara** [comment] 2021-04-08 19:05
This one has had me curious so I finally did a little digging. This much was mostly obvious from the log, but it seems like deep in the AWT library it's doing something wrong when initializing the system font when the language is Japanese (I actually managed to get Maptool to launch in Japanese... by setting a breakpoint and modifying a property on the bad object in question). The noteworthy thing I can say though is it doesn't seem to be Maptool specific, just opening an empty Swing window with the language set to Japanese causes it to fail. 

Which leads me to what I should have done to begin with, look up the problem. Turns out this is an old bug in Java (introduced in 11.0.6?) that happens when launching in Japanese with`-Dfile.encoding=UTF-8`.  Learning that, I tested some other encoding options and everything I tried (shift-jis. utf-16, utf-32, us-ascii, etc. etc.) I'm not sure what, if any, issues there might be with Maptool with that parameter being changed though, so I'm not sure if this is enough to really fix the issue (though, I can say it at least launches).

**Comment by Azhrei** [comment] 2021-04-08 22:22
> Learning that, I tested some other encoding options and everything I tried (shift-jis. utf-16, utf-32, us-ascii, etc. etc.)

Did you want to finish that sentence? ;)  It sounds like it should end with "worked."

Do you have a link for the bug you referred to?  I'd like to read up on it.

**Comment by Irarara** [comment] 2021-04-08 22:49
> Did you want to finish that sentence? ;) It sounds like it should end with "worked."
Yes, yes I did. I did edit the post though! 😅

Here's the reports I saw: https://bugs.openjdk.java.net/browse/JDK-8241129
 https://bugs.openjdk.java.net/browse/JDK-8241245

**Comment by Azhrei** [comment] 2021-04-09 02:36
Thanks for the links.  Yes, it looks like this is resolved and the fix will be included in the next release of Java 15.  I don't know how changing the encoding for the JVM might affect reading/writing of text within MT in the Japanese locale.  It would be good to try reading a campaign file from a previous version of MT with the encoding changed as you describe to see if there are any problems.  It appears from https://www.sljfaq.org/afaq/encodings.html that perhaps UTF-16 is a better bet for compatibility with local file encodings.  (For example, if you use UTF-16 and then unzip a campaign file, you're likely going to have better luck reading it on a Japanese locale system (Windows or otherwise) that if you use Shift-JIS.  But again, I can't test that.)

**Comment by Irarara** [comment] 2021-04-09 12:50
I only tested briefly, but I was able to read/write campaigns with Shift-JIS encoding (older campaigns and new). Campaigns saved this way also loaded fine with the encoding switched back over to UTF-8. Writing out the chat log has some encoding issues with certain characters. Overall, observed way fewer issues than I expected, but it was admittedly not the most thorough test.

With UTF-16 I ran into a few issues:
* An unreadable error at launch (unreadable due to messed up encoding, and just as unreadable when the language is English)
* An exception when trying to paste some characters into the chat (but only the first time? And some stuff just won't paste?)
* Was unable to load campaign files saved with the encoding
* Was unable to drop images/tokens to the map

That said, that's all with the system locale as English. Would be good to switch over and see, I might try testing that.

**Comment by Irarara** [comment] 2021-04-09 13:13
Went ahead and tried it out. Same experience in Japanese locale (on Win10).

**Comment by fw** [comment] 2021-04-12 20:50
I tried that changing cfg with "-Dfile.encoding=shift-jis", and started MapTool correctly.
But, a macro that reference map name named in japanese said errer.

Error messages in ``language=en``:
``Can not find map "0-���C�u����HTM3" in function "setProperty".``
``Error trace : WriteJournal@Lib:AdventureJournal <<< macroLink``
(Of course, I had tried in Japanese, and same error occured.)

**Comment by Irarara** [comment] 2021-04-13 20:17
Ouch. Well, not surprised to see it to fail somewhere.

Out of curiousity, what is the map name? I seem to have issue with `setProperty()` (or any function taking the map name parameter) if the map name parameter has unicode characters even when encoding is UTF-8.

**Comment by fw** [comment] 2021-04-14 18:57
Okay, map name is "0-ライブラリHTM3".

In chat, I run `[getCurrentMapName()]` with `ecoding=shift-jis` and got map name correctly.
However, I got broken text when using form field (`<input type="hidden" value="[r: getCurrentMapName()]">`).

**Comment by Phergus** [comment] 2021-04-16 20:25
@fw @Irarara can you test against 1.9.0-alpha.9?

**Comment by Irarara** [comment] 2021-04-17 00:34
@Phergus Launches in Japanese with UTF-8 encoding perfectly for me. 👍 Not seeing any issues.

**Comment by Phergus** [comment] 2021-04-17 01:22
That's great!  It does look quite a bit cleaner.  Craig mentioned some bug-fixes related to the Japanese language in Java 16 so looks like they helped.

**Comment by fw** [comment] 2021-04-17 19:45
@Phergus I tested too.
MapTool launches well!!!
As stated in a picture posted by Irarara, Fonts looks is clear (in 1.8.4, it is not typicaly Japanese font look).

**Comment by Phergus** [comment] 2021-04-17 19:51
@fw  Excellent news.  Thanks for checking.

**Closed** 2021-04-23 22:40 UTC
Labels: bug, tested
