### ISSUE TITLE
Drag/drop image not working

### ISSUE THREAD

**Issue by ThePsycher** [RPTools/maptool#1559] opened 2020-04-15 19:56 UTC
**Describe the bug**
Within library MT works as expected, however I cannot drag/drop anything from the desktop or any other folder, I get the error symbol (circle with a slash through it) and it will not accept these tokens I created with token tool, or any other image file for that matter. I have tried uninstalls/fresh installs, running MT with/without admin. privileges, full screen and windowed mode (I have 2 monitors).  

This is a continuation of an earlier thread where I also reported an error with discord, that has been resolved.

**To Reproduce**
1. Open MT window
2. click/drag created jpeg or png token from desktop
3. attempt to drag/drop token into maptool map area
4. error symbol, will not complete

**Expected behavior**
Expect drag/drop to work from desktop the same as within the library

**MapTool Info**
- Version: 1.6.1
- Install: New (previous versions did this as well, for at least a year - before that it used to work as expected)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Version [10, 18362]

**Comment by Merudo** [comment] 2020-06-04 18:42
Previous effort to diagnose the issue are discussed in #1511

So far we have been unable to reproduce the drag/drop issue. I've noticed @ThePsycher had two monitors on - maybe that could play a role?

**Comment by ThePsycher** [comment] 2020-06-08 15:17
Merudo that is true. I also have it running in admin mode, as well as discord (only way I could get discord to work while looking in maptools). I tried to run File Explorer with admin privileges to see if this would allow me to drag/drop, but unfortunately that is not an option.

**Comment by Jmr3366** [comment] 2022-08-14 03:31
Can this be replicated by anyone else? 
I am unable to duplicate it using cached, not cached, from desktop, from file explorer folders, jpg (or png, or webp ) files.
In review of the information shared, it appears to be a %userprofile% windows security folder issue (or something akin to this).

**Comment by Phergus** [comment] 2022-08-14 04:23
Yeah.  I suspect it was something specific to the users system but I don't know what.

Closing as cannot reproduce.

**Closed by Phergus** 2022-08-14 04:23 UTC
Labels: bug, not reproducible

**Comment by IncendiaryCrocs** [comment] 2024-03-11 14:50
Got the same bug. I do not have Duel Monitors, just using a Windows 11 Lenovo laptop.
Suddenly, halfway through the game, it no longer accepted me dropping files into the system.
I'm using exclusively my own images in the game (8 bit PNGs) - the drag n' drop no longer works on any campaign or map either.

**Comment by ThePsycher** [comment] 2024-03-20 16:03
I've gone through multiple computer builds, Windows 10 and 11, and several
fresh installs (OP and maptools) and it never works.

If it wasn't for the fact this was something I could do many years ago, I'd
assume that Maptools just does now allow drag and drop from Windows.

**Comment by Myckou** [comment] 2024-09-16 16:18
Stumbled across this after running into this issue myself. I did end up resolving it. It's a long running issue it seems so I thought this might be helpful.

I originally had MapTool installed in a non-default location, specifically within my personal user folder instead of the AppData/Local/MapTool path. Perhaps because I am the only administrator for my computer it meant whenever MapTool opened it ran as admin and I had to allow it each time I opened the program. 

I did a full uninstall and then reinstalled it with the default install location. After that it no longer needed a prompt to run as admin and I was able to drag and drop images into MapTool once again.

**Comment by FullBleed** [comment] 2024-09-16 17:04
> I originally had MapTool installed in a non-default location, specifically within my personal user folder instead of the AppData/Local/MapTool path. Perhaps because I am the only administrator for my computer it meant whenever MapTool opened it ran as admin and I had to allow it each time I opened the program.
> 
> I did a full uninstall and then reinstalled it with the default install location. After that it no longer needed a prompt to run as admin and I was able to drag and drop images into MapTool once again.

I hope this does help people who have this issue... but I would like to mention that I never install to the default location and I've never had the problem.  So it seems like it might be more a permissions issue than strictly an install location issue (where using the default install location comes with the necessary permissions on some systems.)

At any rate, thanks for updating the issue.
