### ISSUE TITLE
Map Export: File Size Doesn't Change After Asset Deletion

### ISSUE THREAD

**Issue by dorpond** [RPTools/maptool#2261] opened 2020-10-12 18:11 UTC
**Describe the bug**
I noticed that exported maps stay the same size even if I delete items from the map and export it again.

**To Reproduce**
1. Export a map that has many assets.
2. Observe export file size.
3. Delete many assets from that map.
4. Export the map again.
5. Observe that the file size hasn't changed.

**Expected behavior**
If I delete assets and export the map again, the files size should be lower.

**Screenshots**
N/A

**MapTool Info**
- Version: 1.7.0 (EXE)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Comment by irisiflimsi** [comment] 2020-11-11 21:36
Maybe you can specify this a bit more? I couldn't reproduce it. I created  default campaign, dumped all CSUAC tokens on it. (waited...) and then removed all but 5 tokens. The size shrank from 74MB to 54kb.

If you delete many of the smaller assets, but keep the larger, compression may play tricks on you.

You could also share the campaign files export1 and export2, so we could compare. (Assuming they are not too big. Or share a link then.)

**Comment by dorpond** [comment] 2021-04-15 11:07
Hmmm, let me investigate this further. The map that I noticed this on was a map of the D&D monster tokens I created - 400+ assets (which is why I can’t share it up here). I had so many that I exported the map, to save them all, and then delete most of them from the map. When I exported it again, that was when I didn’t notice much change in size. I think I have a clue why - each of my tokens also had handouts of the monster character sheets. Those png/jpg’s handouts can add up, and that was why I was surprised the map export didn’t change to reflect that. I am curious if the handouts that aren’t being purged when the token are deleted? That could explain why my 3 year campaign file is also 500MB. Maybe handouts aren’t purging?

**Comment by dorpond** [comment] 2021-04-15 11:28
That isn’t the cause; I created a fresh map, dropped 10 or so rptok’s to the map, exported, noted size, deleted most, exported again, and the size changed a lot. 

I will work to try and recreate this myself; if I am unable to do so, then perhaps it had something to do with version 7.0 as I am testing against 1.8.4 now.

**Comment by thelsing** [comment] 2022-04-07 20:42
@dorpond Could you recreate this?

**Comment by Phergus** [comment] 2022-04-08 17:09
Closing.  Can be reopened if it can be reproduced.

**Closed by Phergus** 2022-04-08 17:09 UTC
Labels: bug, not reproducible
