### ISSUE TITLE
[Request] Rename a macro group

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#368] opened 2019-03-23 07:03 UTC
Currently, if one wishes to rename a macro group, it is necessary to edit all of the macros and set the new group name, or edit one, and drag all the others. 
It would be nice, if it was possible to just edit the group name once, and it would affect all the buttons there.

**Comment by melek** [comment] 2020-04-08 18:57
I was posting this as a new issue when I found your feature request. I figured I'd comment my request here to bump the issue instead of making a new one.

Also, you should be able to gather all the un-grouped macros at the top of a panel into a new or existing group with the same/similar command, maybe labelled `Add to Group...`.

**Is your feature request related to a problem? Please describe.**
When I want to rename groups of macros I have to edit each macro manually or with a macro. This

**Describe the solution you'd like**
An option in the macro panel right-click menu to `Rename Group...`, perhaps above `Clear Group...`

**Describe alternatives you've considered**
* Manually renaming works, but is slow and irritating. 
* As @Tdue21 mentions, manually renaming one, copying all the macros to the new group, and removing the originals is a workaround - but it is obnoxious and can lead to human error.. and changes the ID of all the macros.
* Renaming macro groups with a macro works, but MapTool users need to be able to write such a macro or find one already written for them. There is also great potential for human error to break all one's macros.

**Additional context**
Here is a quick screenshot of the current context menu in the macro panel when you right-click on the group name:
![image](https://user-images.githubusercontent.com/220149/78821670-b2c82700-798e-11ea-837a-f8df64e45e79.png)

**Comment by emmebi** [comment] 2020-04-08 22:34
Please assign this to me, I plan to work on this hopefully during the week.

**Comment by Phergus** [comment] 2020-04-12 19:57
Tested with develop.  Rename groups, including no group, working.

Note that connected clients do not see the group name update unless a token anywhere on the same panel is edited.

**Comment by Phergus** [comment] 2020-04-13 19:25
@emmebi   Need to send the server event out to update the panel on connected clients.

**Comment by emmebi** [comment] 2020-04-13 19:57
@Phergus ack, will look into this and check with a connected client to ensure it works properly

**Comment by emmebi** [comment] 2020-04-13 20:08
While looking at this, I checked the following scenario:
- start a server
- connect a client
- rename a macro on the server
- the client doesn't see the change

I suspect it's the same problem which I am having with the renaming of groups (as I most probably followed the same pattern)

**Comment by emmebi** [comment] 2020-04-13 20:14
@Phergus to clarify, what is the behavior where you would like the server event to be generated?

**Comment by Phergus** [comment] 2020-04-13 20:42
When I rename a macro on the server, the client is updated immediately. Whether the macro is not in a group or is in a named group.  Do you maybe not have Player get Campaign Macros enabled?

Adding a new macro _but not editing it_ and the client doesn't get updated.  This might be a good thing as if it is a player accessible macro there isn't much point in showing the `(new)` button that doesn't do anything yet.

If I rename a group, the client never gets updated unless I rename a macro.  Can be any macro and not just one in the renamed group.

So the desired behavior when renaming a group is that all clients get that update.  Otherwise you'll have the GM telling people to push the X button in the Y group and the players won't see a Y group.

**Comment by emmebi** [comment] 2020-04-13 20:51
Understood; however, apparently this is much wider than that: if you delete a group, this is not immediately sent to the client. 

I suspect the problem is in deleteMacroGroup, which first sends a command and then reset the token panels; as I basically copied the behvaior in the renameMacroGroup in Token class, I suspect that could be the cause. Making a quick test now with the deleteGroup.

**Comment by emmebi** [comment] 2020-04-15 21:00
@Phergus 

Did a little investigation; the following is happening when the "Player Receive Campaign Macros" is on:

Token:
- adding a macro -> no update on the client
- renaming -> no update on the client
- delete a macro -> no update on the client
- clear group -> no update on the client

Campaign
- adding a macro -> no update on the client
- renaming a macro -> instant update on the client
- clear group -> no update on the client
- clear panel -> no update on the client

Of course the client is updated as soon as the token is selected or a Campaign macro is edited.

**Comment by Phergus** [comment] 2020-04-16 15:41
Yup.  Lots of bugs to be fixed.  That'll teach you to touch decades-old code.

**Comment by Phergus** [comment] 2020-05-03 17:58
Tested.  Renaming of macro groups working with limitation that clients may not get notified.

Lots of related bugs concerning updating of clients as noted above.  New issue will be created for that.

**Closed** 2020-05-03 21:14 UTC
Labels: documentation, feature, tested
