### ISSUE TITLE
[Bug]: getState() always returning 0

### ISSUE THREAD

**Issue by taustinoc** [RPTools/maptool#3644] opened 2022-09-19 16:48 UTC
### Describe the Bug

In the newly release 1.1.2.0:

getState() is supposed to return 1 if the state is set, 0 if it is not. It always returns 0, regardless of whether the state is set or not. 

### To Reproduce

Add a token. Set a state. Run a macro for getState for that state. It will return 0.

### Expected Behaviour

Return 1 if the state is set.

### MapTool Info

1.12.0

### Desktop

Windows 10

**Comment by FullBleed** [comment] 2022-09-19 18:45
Duplicate of #3642

**Closed** 2022-09-19 23:01 UTC
Labels: bug, duplicate
