### ISSUE TITLE
Enhancement: Decimal digits in map properties (distance per cell)

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#50] opened 2016-05-05 22:30 UTC
[Forum request: Decimal digits in map properties (distance per cell)](http://forums.rptools.net/viewtopic.php?f=26&t=26636&p=262974#p262974)

> It would be great if you could use decimal digits (like 3.5 or 4.7) at "Distance per cell" in the map properties. It would make MapTool more international. A little example:
> 
> In Pathfinder one cell on the map is 5 foot. 5 foot are 1.5 metres in the metric system, which is used all over the world outside the USA (and so in the rpg rulebooks of course).
> 
> Not a big thing, but it's implemented in other virtual tabletops like Roll20, and it would make things just a little bit easier and more compfortable for non-americans.

Should be doable, duplicates another forum request.

**Comment by oliver-szymanski** [comment] 2019-03-16 02:30
I have a fix for this but will test a little bit more, cause this is spread all over the place ;) Just saying so that nobody picks it up too

**Comment by oliver-szymanski** [comment] 2019-03-16 17:14
Fix in https://github.com/RPTools/maptool/pull/319

**Comment by rkathey** [comment] 2019-03-23 11:37
Tested.  I fear there may be some deep dependencies on this one but it seems to be working as intended. Cell size of 2.5 on a new map
![image](https://user-images.githubusercontent.com/231042/54865614-ff19d800-4d35-11e9-979d-7a672aeafc1d.png)

**Closed** 2019-03-24 16:14 UTC
Labels: claimed, feature, tested
