### ISSUE TITLE
[Bug]: getPropertyNames() & getPropertyNamesRaw() return display option characters from older tokens

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3195] opened 2021-11-20 02:50 UTC
### Describe the Bug

getPropertyNames() & getPropertyNamesRaw() should return lists of the property names on a token.
They are instead returning lists of the property names including the preceding * from the campaign properties display option.
This happens with string lists and JSON outputs

Sample output
**New token**
*old lib:animation:* ac,anim.register,charisma,constitution,defense,description,dexterity,elevation,hp,intelligence,movement,onlytheseclients,register,strength,wisdom

**Old token**
*lib:function:*
**"*ac"**,"charisma",**"*constitution"**,"defense","description","dexterity","elevation","hp","intelligence","movement","strength","udfs","wisdom",spelluse

### To Reproduce

1. Impersonate an old token created way back when
2. in chat type [getPropertyNames()] or [getPropertyNamesRaw()]
3. Try again with a new token and compare

### Expected Behaviour

Lists returned should be the property name without the decorative fruit

### MapTool Info

1.10.3

### Desktop

Win10

**Comment by Phergus** [comment] 2021-11-23 21:58
Unable to reproduce with tokens and campaigns up to 2 years old.

**Comment by Phergus** [comment] 2022-08-16 16:57
Tried again with tokens as old as 12 years but no luck.  Closing.

**Closed by Phergus** 2022-08-16 16:57 UTC
Labels: bug
