### ISSUE TITLE
[Bug]: Dropped images are displayed as big red Xs initially

### ISSUE THREAD

**Issue by u-fm** [RPTools/maptool#3238] opened 2021-12-03 10:06 UTC
### Describe the Bug

All dropped images are displayed as big red Xs before restarting Maptool.

### To Reproduce

Dragged and dropped an image file (png and jpg) from a folder.
After restarting Maptool and reloading the campaign file the image is displayed.

### Expected Behaviour

Expected to add a blank token with dropped image.

### Screenshots

![a](https://user-images.githubusercontent.com/68992476/144584409-960cd79e-e0b7-4457-a0a6-7a0f17d19a33.png)

### MapTool Info

1.11.0

### Desktop

Windows 10

### Additional Context

==== MapTool Information ====
MapTool Version: 1.11.0
MapTool Home...: C:\Users\Admin\.maptool-rptools
MapTool Install: C:\Users\Admin\AppData\Local\MapTool\app
Max mem avail..: 1 GB
Max mem used...: 112 MB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\Admin\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: C:\Users\Admin\AppData\Local\MapTool\runtime
Java Vendor....: Eclipse Foundation
Java Version...: 16.0.2
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\Admin\AppData\Local\MapTool\MapTool.exe

**Comment by FullBleed** [comment] 2021-12-03 10:18
Already Reported here (albeit with a less descriptive name): https://github.com/RPTools/maptool/issues/3232

Currently under investigation... 

A fix is sure to be incoming with our man @cwisniew on the case.

**Comment by u-fm** [comment] 2021-12-03 10:23
Thanks, the report did not mention images explicitly so reported to be sure.

**Comment by Phergus** [comment] 2021-12-03 13:54
This only happens when dropping more than one image at a time as reported in the previous issue which did discuss image files.

**Comment by u-fm** [comment] 2021-12-03 13:58
I only dropped 1 image at a time and still this happened.

**Comment by Phergus** [comment] 2021-12-04 17:01
Duplicate of #3232 which is resolved.

**Closed by Phergus** 2021-12-04 17:01 UTC
Labels: bug, duplicate
