### ISSUE TITLE
Token copy and paste should maintain cursor relative distance and position.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#2940] opened 2021-09-05 05:20 UTC
**Describe the bug**
When I select and copy tokens and, then, paste them, I expect their relative positions to be maintained with respect to the cursor.  Because this is not the case with MapTool 1.9.3 or earlier, when I paste tokens to a new location -- to move them up the stairs, for example -- they wind up in unpredictable locations relative to my mouse cursor.  This causes them to expose parts of the map that should not yet be seen. 

**To Reproduce**
1. Select tokens and notice their relative distance and position relative to the mouse cursor.  For example, a token might be located at 2 inches from the center and 30 degrees  (0 degrees at the top or 12 o'clock position) from the top of the mouse cursor. 
2. Paste these tokens to another location on the same map or onto a different map.
3. Notice that when you paste, the tokens are not pasted to the same relative distance and position with respect to the mouse cursor -- instead they wind up in locations that are hard to predict.

**Expected behavior**
1. Select tokens and notice their relative distance and position relative to the mouse cursor.  For example, a token might be located at 2 inches from the center and 30 degrees  (0 degrees at the top or 12 o'clock position) from the top of the mouse cursor. 
2. Paste these tokens to another location on the same map or onto a different map.
3. The tokens are pasted to the same relative distance and position with respect to the center of the mouse cursor.  So, in this example, that would be 2 inches from the center and 30 degrees from the 12 o'clock relative to the mouse cursor.

**Screenshots**
This is the relative distance and position during a copy:

![IMG_20210905_001124](https://user-images.githubusercontent.com/50708405/132116234-43250a93-0934-4861-85b3-55221080c538.jpg)

This is the relative distance and position during a paste:

![IMG_20210905_001202](https://user-images.githubusercontent.com/50708405/132116255-9c6fc384-74da-4fac-b4d4-7613f7eb4d03.jpg)

**MapTool Info**
- Version: 1.9.3

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

**Comment by adventuremagic123** [comment] 2021-09-05 05:56
When selecting groups of tokens, copying, and pasting, this situation gets a lot more confusing and seems less predictable.  Because the original distance and position from the mouse cursor are not maintained, pasting multiple tokens is always confusing.

**Comment by adventuremagic123** [comment] 2021-09-05 16:46
This is an example of copying a group of tokens:

![IMG_20210905_113934](https://user-images.githubusercontent.com/50708405/132134694-50df7bff-4b55-4a3c-b0b4-7ce4c3e57244.jpg)

This is what pasting them looks like:

![IMG_20210905_114008](https://user-images.githubusercontent.com/50708405/132134706-55f42abe-7a57-4574-92a3-9622acfb0481.jpg)

What's expected is that the position of the mouse cursor would have the same relative distance and position for the paste as when the copy was performed.

**Comment by kwvanderlinde** [comment] 2021-09-08 18:23
In the case of a single token, the location of the pasted token is very predictable:
* If the cursor is over the map, the token is placed at the cursor
* If the cursor is off the map somewhere, the token is placed at the center of the map.

The only other detail is that if the token is not snap-to-grid (or there is no grid), it's actually the top-left corner of the token that is placed at the cursor.

The case of multiple tokens is much less intuitive and there may be some tweaking warranted. In this case, the left-most token will be pasted where the cursor is. And ties for left-most seem to go to the top-most. So, e.g., if we copy these tokens: 
![image](https://user-images.githubusercontent.com/7492219/132561774-e0eb7da5-bf5c-4100-bcd1-2688063a7fb2.png)
when we paste, it is the bottom-left token that will end up at the cursor: 
![group-paste-bottom-left](https://user-images.githubusercontent.com/7492219/132562270-ff343f1e-86d4-4b15-8b8d-7abbd6e82917.png)

But if we copy tokens in this arrangement: 
![image](https://user-images.githubusercontent.com/7492219/132562011-1ec49123-aa9d-47fe-80d9-e09a7fb8f6a6.png)
it is the top-left token that is placed at the cursor: 
![group-paste-top-left](https://user-images.githubusercontent.com/7492219/132562326-50ea4a81-a1d3-44f8-8132-8a3aa021e8c7.png)

**Comment by kwvanderlinde** [comment] 2021-09-08 18:25
In the case of a single token, the location of the pasted token is very predictable:
* If the cursor is over the map, the token is placed at the cursor
* If the cursor is off the map somewhere, the token is placed at the center of the map.

The only other detail is that if the token is not snap-to-grid (or there is no grid), it's actually the top-left corner of the token that is placed at the cursor.

The case of multiple tokens is much less intuitive and there may be some tweaking warranted. In this case, the left-most token will be pasted where the cursor is. And ties for left-most seem to go to the top-most. So, e.g., if we copy these tokens: 
![image](https://user-images.githubusercontent.com/7492219/132561774-e0eb7da5-bf5c-4100-bcd1-2688063a7fb2.png)
when we paste, it is the bottom-left token that will end up at the cursor: 
![group-paste-bottom-left](https://user-images.githubusercontent.com/7492219/132562270-ff343f1e-86d4-4b15-8b8d-7abbd6e82917.png)

But if we copy tokens in this arrangement: 
![image](https://user-images.githubusercontent.com/7492219/132562011-1ec49123-aa9d-47fe-80d9-e09a7fb8f6a6.png)
it is the top-left token that is placed at the cursor: 
![group-paste-top-left](https://user-images.githubusercontent.com/7492219/132562326-50ea4a81-a1d3-44f8-8132-8a3aa021e8c7.png)

**Comment by adventuremagic123** [comment] 2021-09-09 02:28
My example for copy-and-paste for a single token is not followed consistently -- it was not a good example.  I currently GM a campaign where every time when I copy a single token, it is not pasted under the mouse cursor but to some random distance and position away from the mouse cursor.

This is the token distance and position relative to the mouse cursor during the copy:

![IMG_20210908_212300](https://user-images.githubusercontent.com/50708405/132612173-8577fbd6-b2b8-4240-aa40-c1d5234719f9.jpg)

This is the token distance and position relative to the mouse cursor during the paste:

![IMG_20210908_212320](https://user-images.githubusercontent.com/50708405/132612250-30ded37f-89cb-4f41-aff6-bf125f553a38.jpg)

**Comment by dorpond** [comment] 2021-09-09 15:42
If you copy and paste a group of tokens, I believe MT (normal behavior) will paste them with the top left token of the group being the one under the cursor. That should be predictable behavior.

But, by your last post, I see something that suggests you might be noticing another bug that I already reported, where token pasting gets thrown off one by one cell, if the grid was adjusted at all.

https://github.com/RPTools/maptool/issues/2260

**Comment by Phergus** [comment] 2021-09-09 22:33
This is a duplicate of #2260.

**Closed by Phergus** 2021-09-09 22:33 UTC
Labels: bug
