### ISSUE TITLE
Bar macro functions seem to be using putToken() and appear to cause the "full token copy" problem when two or more people try to modify a token via macros.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#761] opened 2019-10-04 13:52 UTC
**Describe the bug**
MapTool 1.5.4 bar macro functions seem to be using putToken() and appear to cause the "full token copy" problem when two or more people try to modify a token via macros.

**To Reproduce**
1. Create macro A that calls **setBarVisible("Health", 1)** and **setBar("Health", 5/10)** for a token, receives input, and sets token property a.
2. Create macro B that receives input and sets token property b.
3. Start macro A with token X selected but let it wait for input.
4. Start macro B with token X selected and provide input so that it sets token property b and exits.
5. For macro A, provide input so that it sets property a and exits.
6. Property b is not set.

**Expected behavior**
In step #6, property b should be set.

**Screenshots**

**MapTool Info**
- Version: 1.5.4

**Desktop (please complete the following information):**
 Windows 10

**Additional context**
The state macro functions appear to be working.  Don't seem to cause this issue.

**Comment by Phergus** [comment] 2019-10-04 17:51
This is the way all macro functions that affect tokens worked up until 1.5.4.  These two were missed in the updates made in 1.5.4 and there may be others.

- setBar
- setBarVisible

**Comment by Merudo** [comment] 2019-10-05 03:41
There are a few more that were missed. However to avoid the `full token copy problem`, I'll try to fix them all.

**Comment by adventuremagic123** [comment] 2019-10-05 04:17
Thank you for all your work to help us with this general "full token copy" issue.  You've help MapTool reach an entirely new level of usability!  I very much appreciate it!

**Comment by Merudo** [comment] 2019-10-05 04:27
Thank you. Hopefully PR #764 will solve your problem, at least when using macro functions.

**Comment by adventuremagic123** [comment] 2019-10-05 15:04
Below is a campaign file that demos a situation that might be related to the pushToken issue.

The macros contained within are my best attempt so far to exclusively use only setProperty to set properties for tokens -- and avoid the pushToken problem that causes a "full token copy".

The "Edit Basics" (run as GM) and "Delete" for Equipment & Money (run as a Player) does the following:

1. GM starts the "Edit Basics" macro and lets it sit at the form without providing input.
2. Player connected to the server in a separate MapTool 1.5.5 instance starts the "Delete" Equipment & Money macro.
3. The Player deletes an equipment item by selecting it and clicking "OK".
4. The GM clicks "OK" in the "Edit Basics" macro.
5. The Player now clicks "Delete" Equipment & Money macro and confirms that the equipment item is still deleted -- but does nothing else and sits there at the form.
6. Now, the GM starts the "Edit Basics" macro and sits there at the form.
7. The Player now deletes another equipment item by selecting it and clicking "OK".
8. The Player now clicks "Delete" Equipment & Money macro and finds that the equipment item is NOT deleted (and this is unexpected).
9. The Player tries to delete the item, again, and this time is successful.


[suspected pushToken issue.zip](https://github.com/RPTools/maptool/files/3693372/suspected.pushToken.issue.zip)

**Comment by adventuremagic123** [comment] 2019-10-05 15:07
Interaction with other macros similar to the use case above also lead frequently to unexpected results.  I don't think it's a mistake I've made because I've investigated the code very carefully in at least two of these scenarios.  But I could be wrong.  Maybe I missed something -- or this is an example of pushToken issues?

**Comment by Azhrei** [comment] 2019-10-05 16:20
When a macro begins, MT creates something called a “variable resolver” internally.  That object is used to lookup the values of variables while the macro is running and is what allows different macros to have different scopes (when you use UDFs).

But once the variable resolver obtains a token from the map, it caches that information.  Some macros call putToken() to put a fresh copy of the token on the map but even so, the resolver doesn’t track that change (AFAIR).  This means macros must terminate before a fresh copy of the token will be retrieved from the map.  If your macro is sitting in an `input()`, it can never refresh.  This is why the recommendation is to use HTML frames:  they don’t keep any state and when they are displayed, they grab the data they need, display it, and then the macro terminates.

I haven’t looked at the contents of your macros, but if they’re using `input()`, this is likely what’s happening.  I don’t see this changing in the current version of MT.  It might be that the Parser 2.0 project will change this, but I don’t know how much of the internal plumbing is going to change with the new parser.

**Comment by adventuremagic123** [comment] 2019-10-05 16:24
Thanks.  Yes, I use input() all over the place.

**Comment by adventuremagic123** [comment] 2019-10-05 16:30
Might be good to have a section in MapTool Doc about rules for writing macros to enable multiple people to edit token properties at the same time via macros.

**Comment by JamzTheMan** [comment] 2019-10-05 16:30
Good info there.

Would it be better create a UDF that sort of mimics an input() for a campaign then? Something that at least handles creating, posting and closing the frame for you?

**Comment by adventuremagic123** [comment] 2019-10-05 16:40
That would be great, I think.

There's two reasons I use input() much more often than HTML frames (though I have used it to edit skills, for example):

1. input() is much simpler to use.

2. input() seems to have much faster performance.

However, to enable my macros to be usable by two or more people on the token at the same time, it is worth it to me to do almost anything.

**Comment by JamzTheMan** [comment] 2019-10-05 16:48
I feel ya, I have the same thing in my framework. Luckily I'm not far into it's redesign so will be keeping an eye on using setProperty everywhere and look into converting a couple of my most used input() functions into frames (initiative and damage/healing)

**Comment by Merudo** [comment] 2019-10-05 17:28
@adventuremagic123 I tested your campaign out using the PR submitted and it seems the issue is fixed. I deleted stuff when the GM is in the "Edit Basics" menu and it didn't come back once the GM ended the macro.

**Comment by rkathey** [comment] 2019-10-05 18:45
A MapTool built-in that can produce simple HTML Frames and Dialogs would decrease the learning curve for newer users who want to produce basic frameworks. Or even experienced ones who have simple input tasks. it would be a great addition for 2.0 when you can do more with CSS.

I still use input screens a bit for simple things. I do like that you can 'inline' them in a macro without having to call a function to process the inputs.

**Comment by adventuremagic123** [comment] 2019-10-05 18:59
@Merudo careful, the scenario you describe already works -- depending on how you set it up.  You have to follow all of my steps to find a problem, and there's nothing in there involving the "Health" bar.

**Comment by Merudo** [comment] 2019-10-05 21:39
@adventuremagic123 I did your instructions exactly and I can't replicate your outcomes with `Maptool 1.5.6`. If I do exactly as you said, in Step 5 the first item that was deleted comes back (unsuccessful deletion). It also comes back at Step 8.

With 1.5.6, both deletions are unsuccessful.

With the new code, both deletions are successful.

**Comment by adventuremagic123** [comment] 2019-10-06 02:36
Ok.

**Comment by Merudo** [comment] 2019-10-06 02:51
1.5.6 is out already, it's exactly like 1.5.5 but with a fix for mac users.

**Comment by adventuremagic123** [comment] 2019-10-06 04:22
Does that mean I should wait for 1.5.7?

**Comment by Merudo** [comment] 2019-10-06 04:33
Yep, or at least the first 1.5.7 release candidate.

In the meanwhile, could you repeat steps 1-5 on 1.5.6 and tell me if the item remains deleted? Because on my end, the item is restored when the GM clicks on "OK" in the "Edit Basics" macro.

**Comment by adventuremagic123** [comment] 2019-10-06 04:37
Ok.  Thanks for the quick reply.  I'll investigate in the morning.

**Comment by adventuremagic123** [comment] 2019-10-06 13:03
I redid the "Edit Basics" & "Delete" test with MapTool 1.5.6.  I got exactly the same results Merundo did.  #5 and #8 both gave the unexpected result that the deleted equipment item was not deleted and should have been.

**Comment by adventuremagic123** [comment] 2019-10-06 13:13
I also did the same test where, instead of sitting at input() in "Edit Basics", I was sitting at the HTML frame in "Edit Skills".

At #5, I got the expected result.  The equipment item was successfully deleted.  #8, though, still yields the unexpected result.

Do you believe your change will fix the issue with input()?

The other developers seemed to think that converting all the calls to input() with HTML frames was necessary?

**Comment by adventuremagic123** [comment] 2019-10-07 02:46
BTW, I take everything back about what I said about HTML frames being slower than input().  So far, I've only been using them in complex scenarios -- so I thought ...  But I was wrong.

**Comment by Merudo** [comment] 2019-10-07 03:10
I think it will solve at least some of the issues with `input`, including the example you listed here.

**Comment by adventuremagic123** [comment] 2019-10-07 20:19
Good.  That's great!

**Comment by Phergus** [comment] 2019-10-10 16:39
Listed functions tested and no longer overwrite the entire token object.

**Comment by Phergus** [comment] 2019-10-13 19:20
Documentation updated. Closing.

**Closed by Phergus** 2019-10-13 19:20 UTC
Labels: documentation, feature, macro changes, tested
