### ISSUE TITLE
Add sounds to MapTool

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#615] opened 2019-08-25 06:17 UTC
**Is your feature request related to a problem? Please describe.**
Sounds and music are often requested for MapTool.

I think audio help wonderfully with ambiance, and would be an amazing feature to have.

**Describe the solution you'd like**
I suggest we expend the build-in sounds for MapTool beyond the current dink.mp3 and clink.mp3. A small library of open source sounds (such as footsteps, doors, rain, etc) would be wonderful, and would not increase the size of the download substantially.

I propose a function, `playSound`, that can play the build-in sounds on every client on demand.

Eventually, we can augment the function so that it can play files at an arbitrary location. The GM could therefore send a zip files of sounds to players, and play those sounds while playing.

**Additional context**
 We might want to change our sound player to something better once the switch to FX occurs.

However as long as the `playSound` user function call is carefully defined, we can implement music and sounds now and later change how the sounds work.

**Comment by Merudo** [comment] 2019-08-25 06:24
I added a commit that implements three sounds:

```
[playSound("Dink")]
[playSound("Clink")]
[playSound("Door")]
```

**Comment by JamzTheMan** [comment] 2019-08-25 13:30
It really wasn't hard to add audio to the asset library (did it once back in Java 1.7 days) and even had a panel to control audio. But I didn't know mt that well or FX 1 and had (I believe now) threading issues.

Otherwise, letting MT recognize .mp3, .ogg, .wav files isn't too much work. It will cache then and transfer them just like images.

The "issue" I had with the design is, I don't want to have to drag and drop each audio onto the map so they can be synced so they can be played.

I think we need to implement streaming (which FX can do) at least as an option, maybe it needs both?

**Comment by Phergus** [comment] 2019-08-25 13:45
Some type of UI to manage sounds will be needed though it might be nice to actually drop them on a map and get an icon that could be used to play a sound.  Not everyone wants to use macros and corresponding buttons to do everything.

There also needs to be GUI controls so that players can mute or stop sounds and a way to set volume.

**Comment by rkathey** [comment] 2019-08-25 20:09
Would eventually like individual/connection sounds based on token location
(sounds of lapping water, trap explosions, etc). This is a lower priority
than the other use cases, however.

**Comment by dorpond** [comment] 2019-08-25 21:48
There was a great discussion and mockups that I once provided, but are no longer there due to technological changes throughout RPTools history, but this could help with ideas:

http://forums.rptools.net/viewtopic.php?t=2417

If anyone can locate the mockups I made in some archive server of sorts, I’d love to see them again!

**Comment by Azhrei** [comment] 2019-08-25 23:01
The images come from gallery.rptools.net and I think Craig archived that stuff somewhere; I didn't keep it.

**Comment by JamzTheMan** [comment] 2019-08-26 00:03
Honestly, we don't need mockups, it's not a UI issue, it's more of a technology and maybe UX issue...

**Comment by dorpond** [comment] 2019-08-26 00:44
Yeah, probably right. I think the mockup I made for the sound tool, was basically just like lighting, where you would see the 'sound circles' of each sound object on the map, and when you entered the 'circle', you would start to hear the sound faintly, and as your moved closer to the center of the source, the volume would get louder. Of course, stuff like that would be a better fit for 2.0, and simply calling sounds via macro would suffice.

**Comment by dorpond** [comment] 2019-08-26 00:47
I put a lot of thought into sound in the past, and while I don't have my visuals, I did find my notes. I will post them in here, if for anything, could be an outline for those who wish to think about implementing sound or even making their own sound tool: 

-	Scenes (Battle of Evermore)
o	Made up of Events. Each event can be turned on and off individually.
	Music Event: Playlist X
	Loop Event: Wind Blowing 
	Single Event: Clock Bell Rings 
	Random Event: Thunder Rolling.
	Has a master on/off/pause switch that stops all events that may be playing.
	Upload photo that represents the Scene.
-	Events
o	Made up of Sounds. Can create 1 of the 4 following events:
	Music Event (Calming Music)
•	Volume Control.
•	Playlist
•	Random Play – checkbox
•	Delay Start – checkbox: time value 
•	Fade During Start / Stop – checkbox: fade in value, fade out value
•	Pause Between Songs – checkbox: time value
•	Fade Between Songs – checkbox: fade in value, fade out value 
	Loop Event (Soft Wind Blowing)
•	Volume Control
•	Balance Control
•	File Chooser
•	Fade During Start / Stop – checkbox: fade in value, fade out value
	Single Event (Lightning)
•	Advanced Volume Control (min and max setting)
•	Advanced Balance Control (min and max setting)
•	File Chooser
•	Stop Another Event – checkbox: event chooser
•	Fade During Start / Stop – checkbox: fade in value, fade out value
	Random Event (Rolling Thunder)
•	Advanced Volume Control (min and max setting)
•	Advanced Balance Control (min and max setting)
•	File Chooser
•	Delay Start – checkbox: time value 
•	Repeat Interval - checkbox: random time value between A & B
•	Fade During Start / Stop – checkbox: fade in value, fade out value
•	Stop Playing After – checkbox: time value (or) number of plays value.
-	Sounds
o	Upload, record your own, or get from FreeSounds.org (they have an API to search and download their content: https://freesound.org/help/tos_api/ )

**Comment by dorpond** [comment] 2019-08-26 00:50
[Ambient Sound Mixer.docx](https://github.com/RPTools/maptool/files/3538991/Ambient.Sound.Mixer.docx)

Outline above didn't format well, so here is the Word file. Again, I was designing this to be it's own tool, so...

**Comment by Azhrei** [comment] 2019-08-28 22:43
Why does there need to be an "Audio Resources Directory"?  Is Milestone 1 just an interim solution until Milestones 5 and 6 are complete, and then it'll be removed?  (If it is just interim, can we remove it and put numbers 6 and then 5 as Milestones 1a and 1b?)  Thanks.

**Comment by Merudo** [comment] 2019-08-29 01:10
> Why does there need to be an "Audio Resources Directory"?

You can read my proposal [here](https://github.com/RPTools/maptool/issues/615#issuecomment-525429512) and [here](https://github.com/RPTools/maptool/issues/615#issuecomment-525422235).

**Comment by Azhrei** [comment] 2019-08-29 02:55
Yes, I read your proposal previously.  It explained the implementation, but I'm asking about behavior.  What feature does this directory provide that can't be provided intrinsically within MT right now (assuming that sound files were added as droppable media)?

**Comment by Merudo** [comment] 2019-08-29 05:00
> This would negate the streaming issues mentioned.

and

> Now that everyone have the sounds locally, there is zero audio streaming done during gameplay - all the transfer was done beforehand - so low download/upload speeds are no longer an issue.

**Comment by dorpond** [comment] 2019-08-29 10:43
I don’t really care how it is all done at the end of the day whether it be streamed or thrown into a library, as long as I can play two different ways: 

1. Maptool session is all planned out ahead of time, where maps, monsters, and sounds are all in place and ready to go.

2. Unexpected random encounters, where we make the encounter on the spot during session.

#2 is important - I think it is important to be able to support that GM who shoots from the hip during play - they random encounters every hour (in game time), and roll against a bunch of random charts. Some GM’s prefer the excitement of unknowing where the session is going, with that said, I think it is just as important to be able to drag/add a sound file to the “current map” or session, during play, just as we do with tokens, objects and maps. 

So please keep that mode of play in mind when designing.

**Comment by JamzTheMan** [comment] 2019-08-29 12:18
Re eliminate steaming...

I think people are still assuming that everyone uses MapTool the same way. That you have players that can run and start a server ahead of time and pre download these assets?

There are people that get together last minute to play games with other people, one such group is Pathfinder Society.

So, what I'm hearing is, either I don't get audio or I have to wait for all these assets to download? And then after the game, what happens? Oh great, I now have 72gb of assets eating up space because I just played 6 sessions with 6 different GM's This week who all loved music and I had to download each if there "resource libs"?

Delete it you say? Oh sure, so it has to redownload again next month when I play with him again?

This is sort of like Dorponds mode #2 where you may need the kitchen sink but you play with dozens of GM's a year so please keep the player in mind not just the GM.

**Comment by Merudo** [comment] 2019-08-29 13:33
> Re eliminate steaming...
> 
> I think people are still assuming that everyone uses MapTool the same way. That you have players that can run and start a server ahead of time and pre download these assets?

Do you include me among those who assume that everyone uses MapTool the same way?

I thought my milestone proposal was rather exhaustive and covered the important cases, including the one where the music is streamed from host to clients (Milestone 4).

If you think I overlooked a useful feature, I'd be glad to add to my list of milestones.

**Comment by JamzTheMan** [comment] 2019-08-29 13:45
Just making sure it's covered. I do see it in milestones so ok with that.

I saw your last comment / quote about "this would eliminate the streaming issues...." And may have read it out of context.

I'm all good. :)

BTW FX handles streaming, clips, and such so should not be an issue. It also handles Video and I had planned on incorporating that as well. Both as a "open in a window to play this mp4 or you tube url" for cinematic scenes as well as background maps (or other objects) as there are a lot of cool battle maps out there now in video. (I have a almost working POC but had issues with grid/layers)

So may keep that in mind for functions/architecture (eg should it be playMedia() stopMedia()?)

**Comment by rkathey** [comment] 2019-08-29 13:45
@Merudo at the end of the day it's yours to develop and nothing you've proposed precludes changing the methodology midstream if needed. We'll learn a lot from the eventual POCs. So don't let the discussions and questioning get you down. We really appreciated all the effort and thought you've put into this.

**Comment by Azhrei** [comment] 2019-08-29 14:39
> [...] What feature does this directory provide that can't be provided intrinsically within MT right now (assuming that sound files were added as droppable media)?

We seem to have a disconnect.  I'll try to rephrase again and then I'm going to figure "three strikes and I'm out", so I'll just stop. 🙄

In the current implementation, GMs can drag images to a map, then create a repo and upload that repo somewhere.  Adding the URL of the repo to the Campaign Properties allows those images to be deleted from the GM's machine since both the GM and Player systems will retrieve assets from the repo when they're needed (the repo is essentially an index file that keeps track of which asset ID refers to which file inside the repo).

Why not use the same approach for sounds?  Let the GM drag/drop sound files to the map, then create a "sound repo" that they upload anywhere they want and include the URL in the Campaign Properties.

When the GM goes to **Export > Campaign Repository file...** they will receive a dialog box that is different than it is today.  They will see a list of asset names and sizes — a summary of what is going to be created.  Then either/both an image repo and sound repo are created.

_(I was thinking the sound files might have checkboxes to indicate which ones should be in the repo vs. which are embedded in the campaign file itself, and a file size slider that automatically changes the state of checkboxes that are sized larger or smaller than the value on the slider.  This way the GM can choose all files larger than such-and-such, then toggle individual files as well.  Because a sound repo that contains music is likely to be very large, the repo might be stored as a directory with an index file in it, but the point is that they'd be managed inside MT.)_

Perhaps your **Audio Resources Directory** is what I described above, but it wasn't clear to me what the advantage was of having a directory outside of MT's purview instead of a repo created and managed by MT.  I suppose some POC code or dialog mockups would clear that up...

**Comment by rkathey** [comment] 2019-08-29 14:49
![Export](https://user-images.githubusercontent.com/231042/63950611-e975b080-ca41-11e9-9065-e4322adf5fbf.png)
![CampaignPrefs](https://user-images.githubusercontent.com/231042/63950622-f09cbe80-ca41-11e9-9185-7252d93efd1d.png)
This was my thought as well. I know we still have the huge streaming file question but I would rather use the current image method for sound rather than invent a new method.

**Comment by JamzTheMan** [comment] 2019-08-29 14:57
To expand on that, do we plan on using the Asset Library to show audio files as well?

Re dragging audio clips to the map, what I did in my POC was use a static speaker icon to represent them.

I could see using the same "vision" mechanic to show how loud the sound is. Eg it's "decibel" if you will (vs lumens). It would denote how many "feet" away you could hear the sound and show a radius circle to the gm.

Sorry, getting off topic...

@azhrei I think we are trying to walk a fine line here. The "problem" (ok may not be a problem) is by adding them to the campaign/repo is that it can get bloated. But I suppose no more than adding images. If it's handled like other assets and cached once, it should not be to bad and probably better than syncing a whole directory.

Given audio clips are treated like image assets, any sort of "dir" sync may be better handled by third party like Google Drive.  I already added a preference in MT that you can add a "external drive" location so MT could reference that as "root" and could be extended.

**Comment by Azhrei** [comment] 2019-08-29 15:22
If people drag the entire sound track to _Conan the Barbarian_ to their map, then we should probably warn them that they should **_really_** consider creating a sound repo for the campaign!

Let's be clear:  music != sfx clips.  I think we can all agree that shot 2-5 second sound clips aren't really the issue.  The issue is mood music that includes entire movie sound tracks, for example.

We could have a separate directory under `.maptool`, something like `.maptools/sounds`, that is used for such things.  But then it'll be like the Global macros that we have now — not part of the campaign so not transported when the campaign is moved or copied.

I would rather have sound files that are dropped onto the map copied into `.maptool/assets` (or a subdirectory of that, if you wish) so that they can be saved when the campaign is saved.  They can also be managed with the existing `AssetManager` class, et al.

However, creating a sound repo is more tricky.  When creating the sound repo, MT can ask the user for a directory name and it copies the larger sound files to that directory (DropBox, if you like).  Then it stores an `index.gz` file in that same directory.  In the Campaign properties, a repo that points to a directory instead of a single file would then read the `index.gz` from the directory and treat the rest of the assets as being in the same directory.

Users will likely want to use the same directory over and over again (I know I would), so we'd need to update the `index.gz` instead of overwriting it, since some of the sound files might already exist.  But verifying that the sound files haven't changed means computing a checksum, which means reading them, which is potentially a very time-consuming operation (for files that aren't on the local computer).  We could use {file size, timestamp} but that's not as reliable.

And what happens when the campaign-file-as-directory is implemented?  If all of the sound assets are stored in a particular directory (separate from other assets), then maybe the repo (i.e. the `index.gz` file) is created as part of the process of saving the campaign.  But how to easily use that directory?

**Comment by JamzTheMan** [comment] 2019-08-29 15:38
So ya, let's stick with "clips" for discussion now and how to handle that, eg phase/milestone 1.

FWIW when I did a POC a couple of years ago, I initially did it using assets and all, just extending the image list to include .mp3, .wav with special handling of missing/default images.

The only downside is having to have the sound on the map to play it. I didn't think of it at the time but probably should have followed the image:dragon notation and used a audio:roar notation to fix that.

It still sort of sucked to have to add it to a physical map when it didn't need to be on a map really. But same could be said for image:images, do they really need to be on a "map".

Maybe that is where @merudo is heading? A "place" in the campaign that holds "assets" shown as a list only vs being on a map, sort of how campaign "macros" are handled. It's part of the campaign still.

Oh gosh, here I go again but maybe there needs to be a new tree panel view that holds and displays assets not on a map. You could have macros, images, and audio "assets" here and can be referenced from any macro. This gets rid of the need for lib tokens as well.

It's scope creep and not needed for milestone 1 but throwing it out there some IF something like this is created it's created to hold multiple types of things. Heck, maybe even just plain "text" can be stored as an asset so a JSON to hold spell data doesn't have to be on a lib token?

**Comment by rkathey** [comment] 2019-08-29 15:43
Another scope creep idea: Sounds on tokens so they can move with the critter. Maybe they should always be associated with tokens for the sfx type. You could use your own sound marker that way.

And I still like the idea of a sound explorer per map but if you had them associated with tokens then the existing token tree idea works.

**Comment by dorpond** [comment] 2019-08-29 15:56
> Another scope creep idea: Sounds on tokens so they can move with the critter. Maybe they should always be associated with tokens for the sfx type. You could use your own sound marker that way.

Ooooo, I had never thought of that before, but makes total sense! Why have a dragon sound in a room when the dragon itself makes that/those noises! Brilliant @rkathey!

**Comment by Azhrei** [comment] 2019-08-29 15:57
> Maybe that is where @Merudo is heading? A "place" in the campaign that holds "assets" shown as a list only vs being on a map, sort of how campaign "macros" are handled. It's part of the campaign still.

This will be a necessary part of the token split project.  Might as well consider it for sound clips.  And eventually, macros.

**Comment by rkathey** [comment] 2019-08-29 16:05
> Ooooo, I had never thought of that before, but makes total sense! Why have a dragon sound in a room when the dragon itself makes that/those noises! Brilliant @rkathey!

The downside would be that you would need to save the sound in the RPTOK file bloating those a bit and increasing their transfer time. But if it was associated with a token a creaky door would always be a creaky door without dropping sound markers all over the place

**Comment by JamzTheMan** [comment] 2019-08-29 16:58
Yea, great point, no reason a sound token would just be a "token" as well...

**Comment by Phergus** [comment] 2019-08-29 20:08
Mostly just agreeing with what others have said...

It seems like using the current MapTool mechanisms for asset management/delivery would serve perfectly well for SFX clips and other small audio resources.  Supported audio types would show in the Resource Library with appropriate icons and once made a part of a campaign by
- dropping them on a map,
- adding them to a table, 
- attaching them to a token,
- etc.
would be sent to clients just like images.

To facilitate transfers to clients when the GM's outgoing connection might be limited, the existing remote repository function would work for audio files just as it does for image files.

Larger audio files would need a streaming solution but doing so from a GM's computer could well be problematic for many.  The remote repository can help with moving the bandwidth off the GM's computer still would have the players downloading potentially massive amounts of data.   As RPTools/MapTool won't be running an online streaming service to handle this we may need to see if there are audio streaming services available that MapTool could connect with through the REST functions.

A solution that has GM's telling their players to download a couple GB of audio files before the next session isn't very user-friendly for GMs or players.

One issue that hasn't been brought up is that streaming of copyrighted audio material may well fall under the laws governing streaming media services.

**Comment by Azhrei** [comment] 2019-08-30 16:01
> Larger audio files would need a streaming solution but doing so from a GM's computer could well be problematic for many. The remote repository can help with moving the bandwidth off the GM's computer still would have the players downloading potentially massive amounts of data. As RPTools/MapTool won't be running an online streaming service to handle this we may need to see if there are audio streaming services available that MapTool could connect with through the REST functions.

Unfortunately, HTTP isn't a great protocol for streaming audio.  This makes something like DropBox or similar less than ideal as a "sound repository" location.  However, it's what we've got — such storage services are ubiquitous and users (both GMs and Players) are familiar with them.

> A solution that has GM's telling their players to download a couple GB of audio files before the next session isn't very user-friendly for GMs or players.

Definitely true.

Of course, if I were the GM, I'd be using DropBox or similar and I'd be sharing the folder with players in advance.  In fact, I would likely have one folder per campaign that I'm running and I'd just share it with all players in that campaign during the first gaming session.  The DropBox software on each player's machine would simply download the files any time the system was up and running with no action on the part of the player from then on.

> One issue that hasn't been brought up is that streaming of copyrighted audio material may well fall under the laws governing streaming media services.

There's no problem playing music for a party that you're hosting at home.  There shouldn't be any issue with streaming music for a "virtual party" as well, particularly when you haven't invited the whole world. 😉

I don't think MT wants to get into this, but we _could_ downsample the larger sound files into something pretty low, like 128k or 92k audio, and then put _that_ into the sound repo.  It'll be good enough for most cases, since you don't want players really focusing on the music anyway... it's supposed to be background for the actual content: the game.

In addition, the files will have asset ids as names, which makes them difficult for people to "accidentally" find if they're just scanning all of DropBox's public folders.

_(Do we want metadata about the sound clips accessible without reading the clip itself?  For example, we can read the first few hundred bytes of an MP3 to find track length and such, but we'd have to read an entire WAV file to get the same information.  Do we want that info to be available to clients so that they can choose whether to play the music in the first place?  If I'm on a hotel wifi link, I may choose to "turn off" any sound file downloads that are so large that they're going to eat up my bandwidth for the next 5 minutes...)_

**Comment by Phergus** [comment] 2019-08-30 17:19
VLCJ might be a solution to handle the streaming issue.  At least there is some activity on it in the past year.  It is still putting the bandwidth use on the GM's outgoing connection.   And, of course, now we'll have the tech support for opening more ports in their router.

Streaming will also need multiple channels for SFX (if streamed), ambient sounds, music sound track, etc. so that players can individually control volume or mute those channels as needed.

**Comment by Syndaryl** [comment] 2019-08-30 17:31
> > One issue that hasn't been brought up is that streaming of copyrighted audio material may well fall under the laws governing streaming media services.
> 
> There's no problem playing music for a party that you're hosting at home. There shouldn't be any issue with streaming music for a "virtual party" as well, particularly when you haven't invited the whole world. 😉

Except there is, you're not at a party at home. You're broadcasting it over the internet, and all the common sense in the world won't make that less sketchy in some jurisdictions. Calling someone on the phone and playing music to them is broadcasting in the US. _Hold music_ has to be licensed properly!

**Comment by JamzTheMan** [comment] 2019-08-30 17:35
We're not beholden to that anymore than people sharing copyrighted images or text. We don't host the server, only create software that can share digital media.

If someone is illegally hosting material a DMCA take down can be requested.

**Comment by Azhrei** [comment] 2019-08-30 17:39
> Except there is, you're not at a party at home. You're broadcasting it over the internet, and all the common sense in the world won't make that less sketchy in some jurisdictions. Calling someone on the phone and playing music to them is broadcasting in the US. _Hold music_ has to be licensed properly!

You're wrong.  Broadcasting implies no control over who can receive the transmission.  Hence, radio and television are broadcast mediums, while cable stations are not (since the receiver must pay for such service).

Hold music is licensed because of commercial use reasons, and there is no commercial use here.  (I suppose if the GM is charging money for Players to join the game, that argument could be made.  Doesn't affect MT though, as _we_ are not the ones making the music available.)

You're certainly correct about "some jurisdictions", but again, that doesn't affect MT — we're not the ones streaming the music, nor are we the ones with any control over who can download and play the music.  We _are_ the folks who are downsampling the audio (potentially) and we _are_ the ones obfuscating the filenames to make it less likely that some random individual trolling the interwebs will find it.

**Comment by Phergus** [comment] 2019-08-30 18:57
Yeah, that's what Napster said too.

**Comment by rkathey** [comment] 2019-08-30 19:02
Napster was hosted. MapTool isn't. That's like saying FTP is at fault for transferring licensed content.

**Comment by Phergus** [comment] 2019-08-30 19:55
Napster was peer-to-peer.  No content was hosted by them.    Also RPTools.net does facilitate the connection of strangers to one and other through the server list.

**Comment by rkathey** [comment] 2019-08-30 20:00
But it doesn't list the audio files each user will be using. As I understand it, Napster's goal was to hook folks up based on available music files.

**Comment by JamzTheMan** [comment] 2019-08-30 20:58
Napster hosted the catalogue of files. Much like NZB sites get in trouble but Usenet servers that do the hosting do not.

**Comment by Merudo** [comment] 2019-09-06 11:11
I added `playStream(url)` and `stopStream(url)` to stream sounds from an online source. 

Example:

`[playStream("https://www.fesliyanstudios.com/musicfiles/2019-05-01_-_Undercover_Spy_Agent_-_David_Fesliyan.mp3")]`

It works well enough. I quickly realize however how limiting our sound player `javazoom` is, with basically no feature beside playing and stopping a sound. For example there is currently no way to change the sound level.

Any idea of what a good replacement player might be? Once we decide on something I think I'll have enough to create a PR for `playStream` and `stopStream`.

**Comment by Merudo** [comment] 2019-09-08 13:08
I implemented `playStream()` (#667) to play music from a remote server. I'm quite excited about the feature and I'm happy with the implementation in `JavaFX`.

**Comment by Phergus** [comment] 2019-09-10 22:35
@Merudo   Looks like something broke `cycleCount` in the current code.   No longer loops.

**Comment by Merudo** [comment] 2019-09-11 08:36
> @Merudo Looks like something broke `cycleCount` in the current code. No longer loops correctly. 2 works but 3 only gives 2, 5 gives 3 and 10 gives 6.
> `"https://ia601701.us.archive.org/21/items/Laser_201304/laser.mp3"`
> 
> Edit: Maybe it just doesn't like that one. Others seem to be counted accurately.

This is really weird. I checked with `getStreamProperties` and the `currentCount` goes 0, 1, 2, 4, 6, 8.

**Comment by Merudo** [comment] 2019-09-11 11:08
Posted issue on StackOverflow: https://stackoverflow.com/questions/57887596/javafx-mediaplayer-plays-half-as-many-times-it-should-when-setstoptime-is-used

Upvotes would help this getting more attention.

**Comment by rkathey** [comment] 2019-09-11 12:25
I received this when voting.

Thanks for the feedback! Votes cast by those with less than 15 reputation
<https://stackoverflow.com/help/whats-reputation> are recorded, but do not
change the publicly displayed post score.

**Comment by JamzTheMan** [comment] 2019-09-11 12:28
@Merudo is there a GitHub issue opened for this over at the JavaFX repo? Perhaps that is a better place to garner attention and a fix?

**Comment by Merudo** [comment] 2019-09-11 12:34
I guess this is a bug, isn't it? I will open a bug report.

**Comment by Phergus** [comment] 2019-09-21 16:38
New playStream, editStream, stopStream and getStreamProperties functions added for 1.5.5 via #667 

Moving this issue out of 1.5.5 project and into backlog for further discussion/changes.

**Closed** 2020-06-20 18:43 UTC
Labels: feature, macro changes
