### ISSUE TITLE
MapTool 1.5.2 Exception thrown when trying to move or add tokens on a map.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#471] opened 2019-05-16 14:34 UTC
**Describe the bug**
Started the MapTool 1.5.2 server.  Players were connected.  I was moving a token and this happened.  Same thing happened when I tried to drop a new token on a map.  MapTool 1.4.1.8 has no trouble doing the same thing with the same campaign.

```
java.lang.NullPointerException
	at net.rptools.maptool.client.ServerCommandClientImpl.putToken(ServerCommandClientImpl.java:122)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.commitMoveSelectionSet(ZoneRenderer.java:504)
	at net.rptools.maptool.client.tool.PointerTool.stopTokenDrag(PointerTool.java:295)
	at net.rptools.maptool.client.tool.PointerTool.mouseReleased(PointerTool.java:643)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        ...
```

**To Reproduce**
1. Start MapTool 1.5.2 with shared FoW.
2. For the first time, open campaign that was used with MapTool 1.4.1.8.
3. Move token.
4. Get the exception shown above -- and all the players saw the same exception.
5. Can also reproduce by attempting to place a token on the map.

**Expected behavior**

**Screenshots**

**MapTool Info**
- Version: 1.5.2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I can only reproduce this problem while the MapTool server is running on my machine (I'm the GM) and with players connected.  I cannot reproduce the issue if I don't have the server running or if I have the server running but no players are connected.

**Comment by adventuremagic123** [comment] 2019-05-16 14:36
When I say "for the first time", what I really mean is that once I opened the campaign in MapTool 1.5.2 and saved -- I did not ever touch it again with MapTool 1.4.1.8.

**Comment by Phergus** [comment] 2019-05-16 20:05
Does it happen with no campaign loaded with players connected?

**Comment by adventuremagic123** [comment] 2019-05-16 23:36
I haven't tried that scenario.  The campaign was already loaded before the players connected.

I'll ask someone to help me try that scenario, and get back with you.

This is the campaign with an empty
[Empty Map with Two Tokens.zip](https://github.com/RPTools/maptool/files/3189348/Empty.Map.with.Two.Tokens.zip)
 maps and two tokens.

**Comment by adventuremagic123** [comment] 2019-05-16 23:46
We did the test.  There was no problem when no campaign was loaded.  I had one player connected remotely the same way we did during the game.  Also, the Edit Token view also comes up with no trouble -- no delay.  I'll add that info to the other bug.

**Comment by Phergus** [comment] 2019-05-17 18:04
Thanks for the update and campaign file.
In your normal campaign file, are you using any utility libs like Wolph's BoT?  Do you have any lib:tokens with onCampaignLoad or any of the other events listed here: http://www.lmwcs.com/rptools/wiki/Category:Event

**Comment by adventuremagic123** [comment] 2019-05-18 02:43
No to both questions.  All I did was remove the maps, orherwise that is my entire campaign file.

**Comment by adventuremagic123** [comment] 2019-05-18 02:56
So, in other words, there's a new limitation here that would be nice not to have.

**Comment by Phergus** [comment] 2019-07-24 03:16
Unable to reproduce with supplied campaign or otherwise using 1.5.2.
Closing if no reproducible steps can be supplied.

**Comment by adventuremagic123** [comment] 2019-07-25 04:21
This issue seemed to require multiple players to be connected to the server.  Other than that, those are exactly the steps.

**Comment by adventuremagic123** [comment] 2019-07-26 03:01
I could not reproduce even when I had a single player connected.  The problem occurred on game day with multiple players connected.

**Comment by adventuremagic123** [comment] 2019-07-27 14:05
For us, this problem happened immediately and was reproducible every time.

**Comment by Phergus** [comment] 2019-07-27 14:58
Unable to reproduce with supplied campaign and 4 player clients connected.

If you are able to reproduce this at will with the campaign above then more information will be needed.  Screenshot of server options.  Screenshots of preferences tabs.

**Comment by adventuremagic123** [comment] 2019-07-29 05:05
Everything I did was with a fully populated campaign.  Once we stripped out all the maps, it probably made this hard or impossible to reproduce.  I had hoped the stack trace would help.  I think a major part of this is having players connect remotely -- at least one had a DSL connection.  I just don't have the resources to try to figure out what configuration creates this issue.  All of my current players are non-technical.

I've made big changes to my campaign, so we might never see it again.

My players won't whether through another beta test.  It would hurt my campaign to do this again.

I'll try running a server with four players I'll run locally to see if I find anything.

**Comment by adventuremagic123** [comment] 2019-07-29 14:52
I retested this with MapTool 1.5.3.  I ran the GM session locally with 4 local player sessions.  I used the campaign and tokens that originally discovered this problem.

I suspect this is a hard to reproduce issue.  We had about 4 players connected remotely at the time and at least 1 but maybe 2 were using a DSL connection.

For the tokens that found this issue, they had 2718 token properties each.  I thought this might be a factor and have reimplemented my macros to use JSON -- reducing our token properties down to 143.

Another thing that might have come into play is that all of my players had just installed 1.5.2, the build where we found this problem.

With all the changes I made to the macros and some of the work done on 1.5.3, I very much doubt we'll see this issue again.

I'd suggest closing it out as not reproducible, and wait and see if it happens again.

My group is adding two new players next week.  After they have settled in (maybe two weeks from now), we will try 1.5.3 as a test.

**Comment by Phergus** [comment] 2019-07-29 14:57
A lot of factors can play into this.  The exception is telling us that the Zone (i.e. map) didn't exist to put the token on.  Obviously that shouldn't happen.

Thanks for all the work on your end to try and narrow this down.  We'll close the issue for now.

**Closed by Phergus** 2019-07-29 14:57 UTC
Labels: bug, not reproducible

**Comment by adventuremagic123** [comment] 2019-07-30 05:59
Another thought ...  I think while I had players connected I may have loaded a campaign and tried to put tokens on a map.

**Comment by adventuremagic123** [comment] 2019-07-30 06:00
So, I may have had a campaign loaded and, then, loaded another campaign.

**Comment by adventuremagic123** [comment] 2019-07-30 06:03
I think what happened was that I had copied the campaign I was using in 1.4.1.8, loaded the one I wanted only to use with 1.4.1.8, and, then, loaded the copy I had wanted to use with 1.5.2.
