### ISSUE TITLE
Drawable without points throws NullPointerException

### ISSUE THREAD

**Issue by Bbansjkl** [RPTools/maptool#192] opened 2018-07-07 02:50 UTC
Heyho,

in our recent session we were forced to exit maptool because of a IndexOutOfBoundsException while one player was drawing on the map (Sadly I don't have logs for this).  
The GM saved the map on exit, but could not load it again. Looking at the logs showed the following:
```TinyLaF v1.4.0
'Default.theme' not found - using YQ default theme.
Jul 07, 2018 4:18:01 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2018-07-07 04:18:14,975 [client.MapTool:316] ERROR - PersistenceUtil.error.campaignRead
java.lang.NullPointerException
	at sun.dc.DuctusRenderingEngine.createStrokedShape(Unknown Source)
	at java.awt.BasicStroke.createStrokedShape(Unknown Source)
	at net.rptools.maptool.model.drawing.LineSegment.createLineArea(LineSegment.java:66)
	at net.rptools.maptool.model.drawing.LineSegment.getArea(LineSegment.java:50)
	at net.rptools.maptool.model.Zone.collapseDrawableLayer(Zone.java:1658)
	at net.rptools.maptool.model.Zone.collapseDrawables(Zone.java:1641)
	at net.rptools.maptool.model.Zone.optimize(Zone.java:1632)
	at net.rptools.maptool.util.PersistenceUtil.loadCampaign(PersistenceUtil.java:443)
	at net.rptools.maptool.client.AppActions$59.run(AppActions.java:2174)
2018-07-07 04:18:18,945 [util.PersistenceUtil:468] WARN - Could not load campaign in the current format...  trying the legacy format.
2018-07-07 04:18:18,946 [client.MapTool:348] WARN - PersistenceUtil.warn.campaignNotLoaded
```

In the campaign file's content.xml I found the following element in the map entry's `net.rptools.maptool.model.Zone/drawables` at the last position:
```
<net.rptools.maptool.model.drawing.DrawnElement>
  <drawable class="net.rptools.maptool.model.drawing.LineSegment">
    <id>
      <baGUID>AAAAANj+N3EfbgAAAAAAAA==</baGUID>
    </id>
    <layer>TOKEN</layer>
    <points/>
    <width>3.0</width>
  </drawable>
  <pen>
    <foregroundMode>0</foregroundMode>
    <paint class="net.rptools.maptool.model.drawing.DrawableColorPaint">
      <color>-16776961</color>
    </paint>
    <backgroundMode>0</backgroundMode>
    <backgroundPaint class="net.rptools.maptool.model.drawing.DrawableColorPaint">
      <color>-16776961</color>
    </backgroundPaint>
    <thickness>3.0</thickness>
    <eraser>true</eraser>
    <opacity>1.0</opacity>
    <color>0</color>
    <backgroundColor>0</backgroundColor>
  </pen>
</net.rptools.maptool.model.drawing.DrawnElement>
```

Note that the "points" element is empty.
Deleting this drawable let the map load again, in a later test I replaced the empty "points" element with coordinates of another drawable which also allowed the map to load.

I would guess that the initial IndexOutOfBounds exception also stemmed from this: For some reason the drawable was created without points and when the draw function wanted to draw it, it couldn't access any of the points due to the Array having no elements. Sadly there are no logs to support this and I couldn't replicate this.

I'd propose that drawable elements with an empty `points` element should be filtered out and removed either during loading, during drawing and/or when the map is saved.

Versions in Use:
MapTool 1.4.1.8
Java 1.8.0_171

**Comment by Bbansjkl** [comment] 2018-07-07 04:01
> When that exception occurred, I presume there was a popup explaining the error, but MapTool didn't completely crash, correct? So you continued to use the campaign and later saved it. Is that correct

Halfway correct, but I think I left that out earlier. We did get endless exception popups, but I lacked the clarity to get a copy of that, the logfile seemed to have been overwritten with the many tries I did to get that campaign file working again, and even the automatic OneDrive version control didn't pick up the log.  
We couldn't continue, and were only able to exit the program by closing the error popup and pressing alt+f4 fast. The GM saved the campaign at that point, and sadly didn't seem to have backups ready.

> It sounds like the exception handling needs to be beefed up so that partially created drawables are discarded, but also there's clearly an error in that the code attempted to access something outside the bounds of some array somewhere... Hard to track down without the stack trace, but we can give it a shot.

Thank you very much for looking into it. I had a quick look into the code, but I would need a bit more time to get familiar with the code, which I don't have until August.  

I hope my report helps fixing this :) MapTool is an awesome tool and has helped to bring an enjoyable experience to my online groups on many evenings!

**Comment by Bbansjkl** [comment] 2018-07-08 09:50
@Jaggeroth Seems you're right. Right-clicking while using the line draw tool does indeed trigger the IndexOutOfBounds Exception, and results in that Drawable to be saved without any points.

Here's the Log file for the whole process, reproduced by selecting the line tool, drawing a line, right-clicking (which will cause the exception), then saving by quitting.

```
TinyLaF v1.4.0
'Default.theme' not found - using YQ default theme.
Jul 08, 2018 11:42:26 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2018-07-08 11:42:38,537 [swing.MapToolEventQueue:43] ERROR - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.rptools.maptool.model.drawing.LineSegment.getBounds(LineSegment.java:94)
	at net.rptools.maptool.client.ui.zone.PartitionedDrawableRenderer.createChunk(PartitionedDrawableRenderer.java:207)
	at net.rptools.maptool.client.ui.zone.PartitionedDrawableRenderer.renderDrawables(PartitionedDrawableRenderer.java:116)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderDrawableOverlay(ZoneRenderer.java:1846)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1162)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:770)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:36)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
2018-07-08 11:42:42,894 [swing.MapToolEventQueue:43] ERROR - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.rptools.maptool.model.drawing.LineSegment.getBounds(LineSegment.java:94)
	at net.rptools.maptool.client.ui.zone.PartitionedDrawableRenderer.createChunk(PartitionedDrawableRenderer.java:207)
	at net.rptools.maptool.client.ui.zone.PartitionedDrawableRenderer.renderDrawables(PartitionedDrawableRenderer.java:116)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderDrawableOverlay(ZoneRenderer.java:1846)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1162)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.paintComponent(ZoneRenderer.java:770)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:36)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
2018-07-08 11:42:43,024 [client.MapTool:316] ERROR - While creating snapshot
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at net.rptools.maptool.client.MapTool.takeMapScreenShot(MapTool.java:588)
	at net.rptools.maptool.util.PersistenceUtil.saveCampaignThumbnail(PersistenceUtil.java:382)
	at net.rptools.maptool.util.PersistenceUtil.saveCampaign(PersistenceUtil.java:364)
	at net.rptools.maptool.client.AppActions$63.doInBackground(AppActions.java:2298)
	at org.jdesktop.swingworker.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.jdesktop.swingworker.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at net.rptools.maptool.model.drawing.LineSegment.getBounds(LineSegment.java:94)
	at net.rptools.maptool.client.ui.zone.PartitionedDrawableRenderer.createChunk(PartitionedDrawableRenderer.java:207)
	at net.rptools.maptool.client.ui.zone.PartitionedDrawableRenderer.renderDrawables(PartitionedDrawableRenderer.java:116)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderDrawableOverlay(ZoneRenderer.java:1846)
	at net.rptools.maptool.client.ui.zone.ZoneRenderer.renderZone(ZoneRenderer.java:1162)
	at net.rptools.maptool.client.MapTool$1.run(MapTool.java:590)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:36)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.displayPopup(MapToolEventQueue.java:62)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:47)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Jaggeroth** [comment] 2018-07-08 13:58
Well the good news then is that there is an outstanding pull request with a bug fix for that already submitted.

**Comment by Merudo** [comment] 2019-08-21 22:34
Has this been fixed? I can't reproduce  the bug.

**Comment by Phergus** [comment] 2019-08-21 22:39
Sounds like it was fixed quite a while ago. @Jaggeroth ?

Can't reproduce either.  Closing as fixed

**Closed by Phergus** 2019-08-21 22:39 UTC
Labels: bug
