### ISSUE TITLE
MapTool 1.5.2 Edit Token view is very slow to initialize.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#472] opened 2019-05-16 14:43 UTC
**Describe the bug**
Edit Token view is very slow to initialize.

**To Reproduce**
1. Double-click on a token.
2. Takes about a minute for Edit Token to become usable.

**Expected behavior**
For MapTool 1.4.1.8 and a copy of the same campaign, doing the exact same thing to the same token on the same map takes about 1 second for the Edit Token view to come up and become usable.

**Screenshots**

**MapTool Info**
- Version: 1.5.2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
I copied the campaign I was using in MapTool 1.4.1.8 and now use that copy exclusively with MapTool 1.5.2.  It has two token types which each have over 10,000 token properties (and, yes, I'll be working to change that now that I know a lot more about MTScript and how to write complex code with it!).

**Comment by Phergus** [comment] 2019-05-16 20:01
A campaign with an empty map but for 2 example tokens would be helpful.

**Comment by adventuremagic123** [comment] 2019-05-16 23:34
Here you go.
[Empty Map with Two Tokens.zip](https://github.com/RPTools/maptool/files/3189346/Empty.Map.with.Two.Tokens.zip)

**Comment by adventuremagic123** [comment] 2019-05-16 23:48
There was no problem when no campaign was loaded.  I had one player connected remotely the same way we did during the game.  The Edit Token view also comes up with no trouble -- no delay.

**Comment by Phergus** [comment] 2019-05-17 18:14
In that case, I would suspect some macro being run whenever a token is selected.  The changes for the addition of multi-line property editing may be the root cause of the slow-down.

However, the nearly 3000 properties aren't helping either.   The vast majority of that could be moved to either JSON arrays or String Prop Lists.

**Comment by adventuremagic123** [comment] 2019-05-18 02:54
I did it that way because I didn't at the time know how to use library tokens and MTScript seemed very limited with the 2 level nesting limit, so I didn't want to try complex logic.

Also, early in development I didn't have time to support having dialogs and wanted non-programmers to be able to edit token properties directly in the Token Editor.

But that all aside, it works fine in 1 4.1.8 with no performance issue, so this issue seems to point at a scalability issue in 1.5.2.

**Comment by adventuremagic123** [comment] 2019-05-18 02:56
So, in other words, there's a new limitation here that would be nice not to have.

**Comment by adventuremagic123** [comment] 2019-05-18 03:31
BTW, you didn't seem to notice my comment at a token with all those properties opened in about 1 second with campaign loaded.  Something else is going on besides the unruly number of token properties or multi-line property editing.

**Comment by adventuremagic123** [comment] 2019-05-18 03:38
Oh, no, you are probably right.  The scaling issue is associated with the number of token properties.  My no campaign test means no token type was used for the token -- or basic.  Anyway, something with much fewer token properties.

**Comment by Phergus** [comment] 2019-05-18 03:48
I wondered if that may have been the issue.

The reason I bring up the multi-line properties is that now that properties table has syntax-highlighting, word-wrapping text areas instead of simple text fields.  There may be a significant overhead in initializing so many.

If you can, grab [1.5.1](https://github.com/RPTools/maptool/releases/tag/1.5.1) and install it in a different folder somewhere.  They can coexist without issue.  Load up your 1.4.1.8 campaign file in it and see if the edit token lag is there.  1.5.1 didn't have the multi-line props.

**Comment by adventuremagic123** [comment] 2019-05-18 10:52
Ok.  Thank you very much for working on that.  My preference would be to have scalability over a fancy editor -- however I can see a need for that when writing more complex code using JSON.  So, we're all probably hoping we can get the best of both worlds.

Maybe the best thing to do would be to have two modes for each token property in the token editor:  view mode and edit mode.

View mode just shows the data as it is, but you can't change anything.  However, once you click on the data part of the property, it switches to edit mode with the syntax highlighting, word-wrapping text area.

Alternately, let us choose whether we want the text area editor or the simple text editor.  Clearly, my implementation as it is does not benefit from using the text area control -- but it will after I refactor the code, start using JSON, and make it a lot more efficient.  If there was still a performance issue at that point by using the text area control, I'd still very much want the option of having the choice of using the simple text control.

I think that might be the fix.  Give us the option for which control we want to use -- with a warning about potential performance issues when using the text area control.

**Comment by adventuremagic123** [comment] 2019-07-26 13:19
Probably a better approach is to only instanciate the new editor if the data type of the field is JSON.

**Comment by Merudo** [comment] 2020-04-01 14:42
Is this bug still occurring? I can't replicate on 1.5.14.

**Comment by JamzTheMan** [comment] 2020-04-01 14:47
Yea, its especially noticeable with tokens that have larger sets of data.

I notice it more if I open one token then close and open another. I can see the old properties for a second then it "refreshes" to the new token.

**Comment by Phergus** [comment] 2020-04-01 14:53
Yeah.  Still there.  1.5.6 seems a bit slower than 1.5.14.

This campaign has 1300ish token properties.
[LotsOfProps157.cmpgn.zip](https://github.com/RPTools/maptool/files/4415915/LotsOfProps157.cmpgn.zip)

**Comment by Merudo** [comment] 2020-04-01 16:23
Did some testing with a large token. I believe the problem with this code is the follow part:

```
    getPropertyTypeCombo()
        .addItemListener(
            new ItemListener() {
              public void itemStateChanged(ItemEvent e) {
                updatePropertiesTable((String) getPropertyTypeCombo().getSelectedItem());
              }
            });
```
The problem is that the listener is fired 5-6 times _during_  the initial loading of the Edit Token view.

As a result the `updatePropertiesTable()` code is ran 6-7 times instead of once... This dramatically lengthen the time needed for the dialog to show up.

Commenting out the `updatePropertiesTable` line results in a very fast and responsive Edit Token dialog, with as far as I can tell no data missing.

**Comment by Phergus** [comment] 2020-04-01 16:34
Isn't that just for the Property Type combo box?   Without multiple property sets would it be called at all?

**Comment by Merudo** [comment] 2020-04-01 16:39
I don't really understand what the Property Type combo box is or how it works. Is there a description of it in the wiki?

**Comment by Phergus** [comment] 2020-04-01 16:46
That's how you set a token to use a specific set of Token Properties.  I've got the Basic properties for PCs, NPCs, Critters plus a set for Objects.

Documented here:
http://www.lmwcs.com/rptools/wiki/Introduction_to_Tokens#Config

**Comment by JamzTheMan** [comment] 2020-04-01 16:49
Is it populating the propertyTypeCombo with the different prop types available every time you open the dialog or something?

I would thing the intention was if you changed the Properties type, you would want to change the Properties page to reflect this.

**Comment by Merudo** [comment] 2020-04-01 16:53
> That's how you set a token to use a specific set of Token Properties. I've got the Basic properties for PCs, NPCs, Critters plus a set for Objects.
> 
> Documented here:
> http://www.lmwcs.com/rptools/wiki/Introduction_to_Tokens#Config

Oh that's the Property Type drop-down list :D. I didn't think of it as a combo box...

I thought it was related to the option "Categorized" in the Properties tab. I still don't know what that does.

**Comment by Phergus** [comment] 2020-04-01 16:55
With current develop, I set a breakpoint there and even with multiple property sets I only saw it hit once.

**Comment by Merudo** [comment] 2020-04-01 16:57
My guess is, if you put a breakpoint there some threads are resolved in the background. So by the time the event can fire again the job is already complete.

Try using something to log output instead, or just a line like `System.out.println("updatePropertiesTable");`

**Comment by Phergus** [comment] 2020-04-01 17:05
Nope.  One output per dialog open.  Tried with/without server running but no player clients.

Certainly if it hits that several times with a large number of properties or properties with a lot of data I could see it slowing things down a lot.

A thought.  Are any of the properties in your set being calculated based on existing props?

**Comment by Merudo** [comment] 2020-04-01 17:13
I started a new campaign and it only fired once. So yeah the issue is definitely campaign-specific.

In your tests, which campaign are you using? For me it's the campaign provided by adventuremagic123.

**Comment by Merudo** [comment] 2020-04-01 17:34
I think I might have figured it out? Each time a new Editor Token view is opened a new listener is added. So if you open and close the Edit Token view ten times the listener will be triggered 10 times.

Actually it will be more like 20 times because each listener is launched twice.

**Comment by Phergus** [comment] 2020-04-01 17:38
Using his campaign.  I do see multiple outputs and reopening the same token increases the number of outputs by two each time.

**Comment by Phergus** [comment] 2020-04-01 17:39
Going back to my campaign that has 1300 properties *but no calculated properties* it still only makes the call once per open.

**Comment by JamzTheMan** [comment] 2020-04-01 17:39
Ahh, that would track because it does seem to get slower and slower as I use it over the night...

**Comment by Phergus** [comment] 2020-04-01 18:07
It's definitely connected to multiple property sets.  I add a couple more to my test campaign and now I'm getting a lot of hits to update.

**Comment by Merudo** [comment] 2020-04-01 19:27
PR #1446 fixes this. I moved the addItemListener to the initialization stage (so there will be only one of them), and add a condition so that updatePropertiesTable is only ran once.

**Comment by Phergus** [comment] 2020-04-01 20:36
Tested.  Much improved with these code changes though still quite a bit slower than same campaign in 1.4.1.8 which is nearly instantaneous on opening the Edit Token Dialog.

No increase in delay when opening and closing the dialog multiple times.

**Comment by Merudo** [comment] 2020-04-01 20:43
Big thanks to @Phergus and @JamzTheMan for the help with this.

**Comment by Phergus** [comment] 2020-04-01 21:00
Thanks for digging into this!

**Closed** 2020-04-02 16:30 UTC
Labels: bug, tested
