### ISSUE TITLE
Edit Token window will sometimes freeze when alt-tabbing in and out of maptool. 

### ISSUE THREAD

**Issue by welovekah** [RPTools/maptool#1250] opened 2020-02-06 21:51 UTC
Edit Token window will sometimes freeze when alt-tabbing in and out of maptool. 

The window cannot be closed, and the entire application must be force-quit since the window has priority. Cannot save or perform other functions when this happens, so it's resulted in a lot of lost work for me.

Only noticed this problem starting after updating to 1.5.12.

Occurred about 7 times across ~20 hours of usage on this version so far.

Attached image is an attempt to resize the window after a freeze, the contents end up blacking out.

![image](https://user-images.githubusercontent.com/9361068/73981706-a6204780-48e7-11ea-88cb-b4ec60b94ff7.png)

**Comment by Phergus** [comment] 2020-02-06 22:05
Thank you for the report.   This is a duplicate of #1198 .

**Closed by Phergus** 2020-02-06 22:05 UTC
Labels: bug, duplicate
