### ISSUE TITLE
Copy/Pasting tokens doesn't give macros new UUIDs

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#907] opened 2019-11-16 13:01 UTC
**Describe the bug**
Copied tokens will have the same UUIDs for the macros which when edited will change the original token's macros.

**To Reproduce**
1 - Make a token, add a macro to it.
2 - Copy (ctrl-c) the token
3 - Paste (ctrl-v) the token to make a copy of it
4 - Edit the macro of either token in any way
5 - All tokens share the edits

**Expected behavior**
Different tokens shouldn't edit another token's macros.

**MapTool Info**
MerudoToday at 4:33 AM
I checked and the issue is in 1.5.7 RC1

**Comment by Phergus** [comment] 2019-11-16 13:08
The problem does not show up in 1.5.6.  The changes to copyToken and the new GM panel were part of 1.5.7-rc.1.  @Merudo any clues?

**Comment by Merudo** [comment] 2019-11-16 13:15
The issue also occurs if the token is copied with `copyToken`.

**Comment by aliasmask** [comment] 2019-11-16 13:19
I seem to recall discussion on cut/paste vs copy/paste of tokens where a cut would preserve all the original tokens info. In that case, a paste should preserve the UUIDs of the macros but a copy/paste shouldn't. Not sure if that distinction is made already for other aspects of a token.

**Comment by Phergus** [comment] 2019-11-16 13:34
Right.  A copy/paste of a token should generate new UUIDs for the macros.  That code was recently modified as well.

**Comment by Merudo** [comment] 2019-11-16 13:40
I'm been reverting commits in batches and the issue was introduced before October 4.

**Comment by Merudo** [comment] 2019-11-16 13:56
I found out the issue is with #771

**Comment by Phergus** [comment] 2019-11-16 13:58
The discussion about cut/paste and copy/paste were part of #619

**Comment by Phergus** [comment] 2019-11-16 15:45
I'm assuming you got this then @Merudo

**Comment by Merudo** [comment] 2019-11-16 22:51
The `token(token)` constructor is not making a deep copy of the `macroPropertiesMap`.

**Comment by Phergus** [comment] 2019-11-16 23:01
Oops.

**Comment by Merudo** [comment] 2019-11-17 00:25
I'm worried the same issue might occur with HeroLabs data not being deep copied, but I can't test it out (I don't use HeroLabs).

**Comment by Merudo** [comment] 2019-11-17 00:33
By the way, copy/pasting tokens didn't give macros new UUIDs in 1.5.6 either - but the objects were still different so editing one token's macro didn't affect the copies.

**Comment by Merudo** [comment] 2019-11-17 00:44
PR #911 should be this issue. There might still be a problem with the HeroLab stuff.

**Comment by Phergus** [comment] 2019-11-17 00:45
Well, if you really want to test the HeroLab stuff...

[MapTool_Import_Tests.zip](https://github.com/RPTools/maptool/files/3855105/MapTool_Import_Tests.zip)

Don't ask me any questions about it.  I don't use HL either.

**Comment by Merudo** [comment] 2019-11-17 00:58
Thank you!

I'm getting errors about a missing content.html, in 1.5.6 and 1.5.7. Maybe the file should have been in the zip too?

In any case I don't think the Hero Labs could cause an issue - it doesn't seem possible to modify it once imported.

**Comment by Phergus** [comment] 2019-11-17 01:04
> I'm getting errors about a missing content.html, in 1.5.6 and 1.5.7. Maybe the file should have been in the zip too?

No content.html file here and the tokens in the .por file load with no issue with the current dev code.  I'll try the release build.

**Comment by Phergus** [comment] 2019-11-17 01:06
Your zip util didn't extract the contents of the .por file did it?

**Comment by Merudo** [comment] 2019-11-17 01:06
I'm not longer getting the error. Maybe the Hero Labs file wasn't fully loaded when I tried to create a token? Strange.

**Comment by Phergus** [comment] 2019-11-17 01:08
Yeah.  Strange.

So as long as the content of the macros on the copied tokens remain the same, if I rename one of them, they all rename.  Expected?

**Comment by Merudo** [comment] 2019-11-17 01:27
I can't reproduce the issue with PR #911 merged.

I create a few macro on a token, copy/paste the token, and rename one of the macro, and no one macro are changed.

**Comment by aliasmask** [comment] 2019-11-17 01:40
I don't recall if renaming a macro was the issue but rather editing the contents of the macro. Check the UUIDs. Afaik, changing the name doesn't affect the UUID.

**Comment by Phergus** [comment] 2019-11-17 02:03
@Merudo  Try it via the Selection panel with all the tokens selected.

@aliasmask The original report included mention of changing the name on one changed the others.

**Comment by Merudo** [comment] 2019-11-17 04:16
If multiple tokens are selected with the "same" macro (same name and same content), they will show up in a "Common Macros" section in the Selection panel. Editing a macro in the "Common" section will change all the corresponding macros. It worked like that in 1.5.6 too. Is that what you are experiencing?

**Comment by Phergus** [comment] 2019-11-17 04:32
Yes.  Editing the common macro changes the macro on all tokens with that "identical" macro.  Assuming that's the desired behavior - and I guess it is - then that's fine.

Editing an individual macro no longer changes the macros on the original or cloned tokens.  As this was the original issue, that's fixed.

**Comment by Phergus** [comment] 2019-11-17 22:40
Tested.  Working as described.

**Closed by Phergus** 2019-11-17 22:40 UTC
Labels: bug, high, tested
