### ISSUE TITLE
current develop can't connect to current stable release

### ISSUE THREAD

**Issue by thelsing** [RPTools/maptool#2461] opened 2021-03-13 13:36 UTC
This is quite inconvenient because I can't test changes without forcing the whole group to use a devepment version.

**Comment by Phergus** [comment] 2021-03-14 02:53
Please follow the provided templates when creating an issue.

**Comment by thelsing** [comment] 2021-03-15 10:20
The pull request was closed, but the problem remains. Since maptool claims to use semantic versioning such incompatibilities between minor versions should not be acceptable. The least that should be done is to show the user a meaningful error message. At the moment the whole client basically  freezes.

**Comment by cwisniew** [comment] 2021-03-27 10:04
The minor versions are expected to be both campaign and macro compatible (some times regression issues will occur unfortunately but should be fixed ASAP), but due to the need for GM to be confident that players clients are operating the same as the server, clients of different versions wont be able to connect to the server.

**Closed by cwisniew** 2021-03-27 10:04 UTC
Labels: feature
