### ISSUE TITLE
Make it clearer in the Initiative Panel if a token is invisible to players

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1845] opened 2020-05-15 14:25 UTC
**Is your feature request related to a problem? Please describe.**
The Initiative Panel doesn't make it very clear to the GM which of its entries are displayed to players:

- Tokens on the Hidden layer appear normally
- NPC tokens with Hide NPCs enabled show up normally
- Invisible tokens are displayed with a gray label that's a bit darker than normal

**Describe the solution you'd like**
A clear visual cue for the GM that the tokens are not visible to players.

The Map Explorer displays invisible tokens as semi-transparent to the GM, maybe the same could apply to tokens in the Initiative window.

**Comment by selquest** [comment] 2020-08-27 18:40
I'm going to try and work on some incremental changes to Initiative this weekend, and this one seems like an easy addition.

**Comment by selquest** [comment] 2020-08-27 19:43
> Given that the existing approach is to color the text the same as it's done on the map, what is your plan for the visual aspects of this change?

The grey vs blue highlight is definitely a good start, but I figured I'd go with the suggestion of shading the token images (and possibly italicizing the token name) in the same way the Map Explorer does.  Should help with the visual distinction, and improve some consistency between the UI panels as a bonus.

**Comment by Azhrei** [comment] 2020-08-27 19:45
Ah, that sounds like a good start.  I didn't recall that the MapExplorer used italics...

**Comment by selquest** [comment] 2020-08-30 19:26
Here's an in-progress example:
![MT-1845-InitiativePanelTransparency](https://user-images.githubusercontent.com/2325887/91667675-54821900-ead4-11ea-8870-cf503f47dfb7.png)

The Dragon is not visible to players, and now indicated by italicized text and a transparent token image, in addition to the current dark gray background.  I'm waffling a bit on the transparency, since it makes for a kind of weird look with the background.

I think really the heart of the issue is that there's not quite enough contrast between the blue (visible NPC), gray (visible PC), and dark gray (invisible) backgrounds.  I'd recommend an alternate color scheme, but ideally we'd actually convert it to an HTML styling that would also be themable.  There's a lot more that would have to go into that kind of restructuring though, so it's definitely out of the "incremental improvements" scope.

**Comment by Phergus** [comment] 2020-08-30 20:12
The transparency is a bit weird but that may be me not being used to it.  It certainly sticks out that something is different about the token.  As I don't use the Initiative panel I don't have a strong opinion one way or the other but I think what you have here works.

Be nice if the PC tokens stood out a bit more but they match the map and map explorer display so that is something for a broader rework.

**Comment by selquest** [comment] 2020-08-31 00:34
Committed with the transparency and italic text indicators.

**Comment by Phergus** [comment] 2020-09-06 20:58
Tested.  Tokens not visible to players are partially transparent and use italic text.  Working as described.

**Comment by selquest** [comment] 2020-09-07 01:36
Included discussion of UI indicators in the new http://lmwcs.com/rptools/wiki/Introduction_to_Initiative (still a WIP)

**Closed** 2020-09-08 15:15 UTC
Labels: feature, tested
