### ISSUE TITLE
Weird frame appearance - undocked, grouped panels.

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2455] opened 2021-03-12 05:57 UTC
**Describe the bug**
May not be a bug, may just be weird.

**To Reproduce**
Take one panel and drag it onto another undocked/floating panel so they are stacked.
Two levels of OS window frame surround the grouped panels.

**Expected behavior**
I would have expected none or at most one OS window frame.

**Screenshots**
![image](https://user-images.githubusercontent.com/45483160/110898775-d0d69e00-833a-11eb-9ff1-0e87252aba59.png)

**MapTool Info**
- Version: 1.8.3

**Desktop (please complete the following information):**
 - Win 10

**Comment by Phergus** [comment] 2021-03-12 13:45
Definitely weird.

Does it as far back as 1.5.1 as well so not a new behavior.   With the "native" MT windows as well as with frame() and frame5().

**Comment by Jmr3366** [comment] 2023-08-22 11:49
I can't duplicate this is 1.13.2 (not saying it isn't happening but that odd outer frame I can't duplicate "today")

**Comment by Azhrei** [comment] 2023-08-25 03:38
This is still happening on macOS Ventura 13.5 (latest release, fully updated) running MapTool 1.14.0-rc3.

The outer OS frame can be closed or the "X" in the upper right corner of the MapTool frame will close it.

![Screenshot 2023-08-24 at 11 33 32 PM](https://github.com/RPTools/maptool/assets/4120974/67500831-f679-4b2e-a85d-ae1514d9ee68)

**Comment by Jmr3366** [comment] 2023-08-25 11:12
What you're pointing at isn't the bug though, that would be the frame that holds the other _two frames_  What I do see on your Mac OS is the extra red, clear, green icons, those do not exist in Windows.

To be clear, the bug is this (and I don't actually see that on your screenshot either,  there are NOT 3 "X"'s)
![image](https://github.com/RPTools/maptool/assets/100969108/56acb299-38d2-48c9-a0ac-bc9a0309dd33)

Windows 11 to compare
![image](https://github.com/RPTools/maptool/assets/100969108/e807e002-6b52-455f-8269-1ef7b7581906)

I think our two screenshots confirm the bug is actually gone :), or maybe theme related

**Comment by Azhrei** [comment] 2023-08-25 20:24
The red button IS the close button from the OS. Had it been in the upper right instead of upper left, it would look just like the OP’s image: an outer level created by the OS, the first inner level created by the JIDE docking framework, then the third innermost level representing one panel.

based on your Win11 shot, it looks like that platform sizes the outer window to be the same as the JIDE docking window, so only one appears. Or maybe the JRE actually builds the window hierarchy differently.

**Comment by kwvanderlinde** [comment] 2023-08-27 04:29
For completeness it's also a thing for Linux (at least on Cinnamon):
![image](https://github.com/RPTools/maptool/assets/7492219/f4222aa2-191b-4097-9e27-fdd63c52ba66)

And for Windows, I can confirm it no longer shows... for the most part. I've noticed the second titlebar flashes for a moment while closing the docked frames via one of the dialog's "X"s.

What's going on here is that JIDE puts floating frames in a dialog. A frame on its own will have its title bar be hidden since the frame itself has a titlebar already. But when multiple frames are docked together, a title bar is needed (presumably to support moving the group as a whole). The problem is that JIDE does this by decorating the dialog itself _and_ the root pane of the dialog, and both of them will add their own version of a title bar.

**Closed** 2023-08-30 23:56 UTC
Labels: bug
