### ISSUE TITLE
[Bug]: getInfo("client") causes an NPE

### ISSUE THREAD

**Issue by Wyrmwood** [RPTools/maptool#3803] opened 2023-01-01 19:29 UTC
### Describe the Bug

`java.lang.NullPointerException: Cannot invoke "java.awt.Rectangle.getX()" because the return value of "com.jidesoft.docking.DockContext.getUndockedBounds()" is null error executing expression getInfo("client").`

This happens 100% of the time with MacOS, occasionally with Windows or Linux. 

### To Reproduce

Open chat and enter `getInfo("client")`. 

### Expected Behaviour

json output of client info

### MapTool Info

MapTool Version: 1.12.2

### Desktop

Windows 10 (Version 10.0.19044.2364), MacOS (Ventura 13.1)

**Comment by FullBleed** [comment] 2023-01-02 05:25
Does this happen if you output to a frame instead of the chat window?

**Comment by Jmr3366** [comment] 2023-01-21 13:50
I thought this was a chat box limiting issue.  The chat box can only hold so much in one "string" so it will NPE due to the output being too large.  As FullBleed stated, this should NOT occur in a frame or into a string that will NOT output to chat.

As I understand it, while one could argue if it is a bug, it sounded like a MAJOR overhaul to overcome and knowing this data can be captured into a variable, and also that dumping this data to chat doesn't really provide any use-case value.  

What is a limitation vs bug vs feature request (I think this is more a feature req than a bug).  We're asking the Devs to change how chat works regarding large strings.

**Comment by kwvanderlinde** [comment] 2023-03-16 00:25
The issue of large output being sent to chat is a separate thing with a different error. This bug is caused by Jidesoft not returning the undocked bounds of a frame for some reason.

This particular error could be mitigated with a null check. But depending on the reason for it, there could be other things not working as expected. E.g., are we holding onto a frame name that doesn't actually exist anymore? Is this just a frame that was somehow never undocked? :shrug:

**Comment by kwvanderlinde** [comment] 2023-03-24 19:09
Duplicate of #3316

**Closed by kwvanderlinde** 2023-03-24 19:09 UTC
Labels: bug
