### ISSUE TITLE
getTokens() occasionally doesn't get tokens when called through an overlay.

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#2056] opened 2020-06-25 23:50 UTC
**Describe the bug**
I have a campaign with an overlay that uses a form call a macro.
The macro can also be called from a macro button on a token.
If I call the macro with the macro button it works fine. 
If I call it from the overlay, it randomly gets different amounts of tokens on a filtered getTokens().

**To Reproduce**
Affected campaign file: https://mega.nz/file/uxh30ZTD#1NW1NaFTe4xbdV_Jc7g7LLXbKU2e8MCmhZMrWlHgn5g

1. Impersonate the "Zalanfe" token
2. Type in `[macro("powerBarEx@Lib:BS"):""]` to fire up the overlay.
3. Click on memories of light button.

relevant macro output code that fails
`
[h: power = json.get(PowerLibrary, json.get(macro.args, "power"))]
[h: setProperty("lastUsed", json.get(macro.args, "lastUsed"), currentToken())]
[h: includeAllies = 1]
[r: tokenString = "{
	visible:true,"
	+ if(includeAllies, "", "current:false,")
	+ if(includeAllies, "", if(isPC(),   "pc:false,",  "pc:true,"))
	+ if(includeAllies, "", if(isNPC(), "npc:false,", "npc:true,"))
	+ "unsetStates:['Dead', 'KnockedOut'],"
	+ "layer:['token', 'hidden']
}"]
[r: "First<br>"]
[r: validTokens = getTokens("json", tokenString)]
[r: "<br>"]
[r: "Second<br>"]
[r: validTokens = getTokens("json", tokenString)]
`

4. First and second are usually not the same.

**Expected behavior**
The testing info I put in should always show the same result for first and second.

**Screenshots**
 relevant output:

`
  | { visible:true,unsetStates:['Dead',              'KnockedOut'],layer:['token', 'hidden'] } First["49361A2AD5F3456B8EFC5FC3DA3E0C9F","4C53229CD48F4EF983D0D972C1E84792","A551FE0461E244A79DBB316FC5E9946E","EAF1FE20160142A883D90E1CEE2CDA69","75C035B4F34E465BA09E334373F46075","6B36F9781EB44D748D417435E8BC4623","3E185FD2BEA54C19B01B249B1993E298","9991382B90ED4F65B160BF0EAF5A5FE9","8FC20F6185BB4176B7219AAD1413C964","44E4B42E4805469F9EC8D77B0C7D5715","122A4F276E004DA780AC1708CEE71CBB","7C72CBC208984F76ACF0741A7F44C966","174BF502B72C4FB99214089245DFEECE","0F3F43C1619542C9A907136B8A7DC8FD","F3A0C2F83E58463AA351694717C86923","E92028D6425040C9812B0553ED922707","EB7AAE6535004EE49F47DF375A8EEB27","5ED9424296AB4BB68E9DFE5F4CD8112E","102C292618B846A9AE95BA8BD3EDCA2A","EAC87D9578EB434EB5DC353413C8DBA3","57F01C22073840A4948657746958FD10","DA919729132F405594415106908B9B19","923EBF04942E459A8BD1BC18D07721C1","2EE407D0C05F4A24AD63B0A8DC0AC619","78F3955241784149A4EE6D8C6553675D","8A92E846028E45878EA7ECB23AE8833F","BB37FF365F7B48FBA967BEE69B1E45FE","086961374AC5402DA925712AC86DB647","0C47D111951048B3A254FC9D7F5C1F3F","976977D78419429B857041E74D5D5385","806FA00F43764449BBEF07F32E07E441","304F591B3CC643A88B707C9E3C18B0A7","C00FE50D735147E2A1F5DD0F701593F1","650A4F31A1924D17B379CF6837B3D005","1DCD45891BEF402C871C0AD594BA363E","64ED120B58934CC3A94EB8579BB8556D","5C3455B8970C444586018006FFC2012B","4776117D98DA45B0A71CADD33022AC51"]Second["D941C01B2CDA457D9098E4930848C784"]
-- | --
`

**MapTool Info**
- Version: 1.7.0
- Install: Upgrade [previous version]

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 pro

**Additional context**
Tested on 2 different computers.

From MapTool, paste info from menu Help -> Gather Debug Information...

==== MapTool Information ====
MapTool Version: 1.7.0
MapTool Home...: C:\Users\Ahri\.maptool-rptools
Max mem avail..: 4 GB
Max mem used...: 640 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: C:\Users\Ahri\AppData\Local\MapTool\runtime
Java Version: 10.0.1

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PATH...........: C:\Users\Ahri\AppData\Local\MapTool\app;C:\Users\Ahri\AppData\Local\MapTool
Number of Procs: 8

==== Locale Information ====
Country.: United States
Language: 
Locale..: United States
Variant.: 

==== Encoding Information ====
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

You can also attach files (drag and drop here) such as log files or paste a file sharing link.
Campaign file again:
https://mega.nz/file/uxh30ZTD#1NW1NaFTe4xbdV_Jc7g7LLXbKU2e8MCmhZMrWlHgn5g

**Comment by Merudo** [comment] 2020-06-26 13:16
I tried a few times but I could not reproduce.

**Comment by Akaku-Keninari** [comment] 2020-06-27 02:02
reopened campaign, tried again, failed within 3 button presses.
changed test code to
`[h: includeAllies = 1]
[r: tokenString = "{
	visible:true,"
	+ if(includeAllies, "", "current:false,")
	+ if(includeAllies, "", if(isPC(),   "pc:false,",  "pc:true,"))
	+ if(includeAllies, "", if(isNPC(), "npc:false,", "npc:true,"))
	+ "unsetStates:['Dead', 'KnockedOut'],"
	+ "layer:['token', 'hidden']
}"]
<br>
[COUNT(10, "<br>"):  json.length(getTokens("json", tokenString))]]`

(in example file, text code is powerBarProcess@lib:BS)

fails at least once in the 10 runs per press.


  | { visible:true,unsetStates:['Dead',              'KnockedOut'],layer:['token', 'hidden'] }1301414141414141414
-- | --

**Comment by Akaku-Keninari** [comment] 2020-06-27 03:29
Tried same code on develop branch, did same error.

**Comment by Merudo** [comment] 2020-06-27 08:08
I managed to reproduce the issue, thank you.

Also, this is not specific to `overlay` but also happens when using `frame5`.

**Comment by Merudo** [comment] 2020-06-27 09:32
Turns out the form submit is running on the wrong thread, which can lead to concurrency issues.

PR #2061 fixes this.

**Comment by Phergus** [comment] 2020-06-27 13:12
@Akaku-Keninari  please test and confirm that the issue is fixed in the develop branch.

**Comment by Akaku-Keninari** [comment] 2020-06-27 22:52
Ran it a few times with a count 100, getting same max and min, so likely fixed.

**Comment by Akaku-Keninari** [comment] 2020-06-27 22:57
Does this not happen currently with dialog5? Just overlay and frame5?

**Comment by Phergus** [comment] 2020-06-28 15:09
If I'm not mistaken the fix is in code used by all three.

Flagging as tested OK.

**Closed** 2020-07-04 15:35 UTC
Labels: bug
