### ISSUE TITLE
In the chat window, move the text below the name

### ISSUE THREAD

**Issue by mrkwnzl** [RPTools/maptool#1318] opened 2020-02-24 19:54 UTC
**Is your feature request related to a problem? Please describe.**
Right now, when you enter text in the chat or have a text output from the macro, the text appears right of the name of the person entering the text. With character pictures enabled in the chat and some character names being rather long, the text doesn’t have much space in narrow chat fields (which you have if the chat is located at the side).

**Describe the solution you'd like**
My proposal is to have the text entered below the name, in the next line. It would save a lot of horizontal space, while the vertical space wouldn’t lose as much. Maybe print the name in bold so that it is more prominent.

**Additional context**
Here is a mock up as an example.
![Example Chat Window](https://user-images.githubusercontent.com/40534855/75186196-c35a7000-5747-11ea-8861-cbe4cd99d28e.jpg)

**Comment by Azhrei** [comment] 2020-02-24 20:28
Most frameworks generate their own output for the chat and don't use the built in formatting.

However, one option might be a `<div>` around the image, then another `<div>` for the name and all user text, with the name being followed by a line break.  (That wouldn't require any CSS `float` elements, which Swing doesn't support.)

Ideally, the chat panel will become a JavaFX web view at some point, with full HTML5 support and user-specified CSS styling.

**Comment by Phergus** [comment] 2020-02-24 21:28
Something like this?
![Screenshot 2020-02-24 14 27 25](https://user-images.githubusercontent.com/34379254/75192653-dfdbb580-5711-11ea-84c9-042e8c323ca3.png)

**Comment by mrkwnzl** [comment] 2020-02-24 21:47
Exactly.

**Comment by mrkwnzl** [comment] 2020-04-13 10:34
I just encountered this again and just wanted to give a real life example as to why this bothers me. This is for our upcoming western game, and the character name is pretty long, as the PCs have nicknames, too. As you can see, the actual content of the chat message has only about half the windows width and there’s a lot of white space between the character name and the message (and, less importantly, somehow the messages don’t line up, as the lines break differently with different line lengths).

<img width="368" alt="Screen Shot 2020-04-13 at 12 26 37" src="https://user-images.githubusercontent.com/40534855/79114156-de7a5100-7d82-11ea-88be-66e8798f1d24.png">

I was wondering if there was something I could do using macros until this gets implemented.

**Comment by Phergus** [comment] 2020-04-13 12:17
You can use `broadcast()` to work around it.  Try this example:
```
[h: output = "<table  border=1 cellspacing=0 cellpadding=3><tr><td>"+token.name+"</td></tr><tr><td>My output goes here.</td></tr></table>"]
[h: broadcast(output,"ALL")]
```
![Screenshot 2020-04-13 06 15 03](https://user-images.githubusercontent.com/34379254/79119675-2b900000-7d4e-11ea-95d9-ff03679e7e55.png)

That's an ugly example but I believe that @aliasmask has some macros for making nice-looking output using broadcast.

**Comment by mrkwnzl** [comment] 2020-04-13 12:27
Thanks a lot! Didn’t know about `broadcast()`.

**Comment by mrkwnzl** [comment] 2020-05-01 07:55
I was looking through the code to see if this is something I could handle, but I’m having difficulty finding where the default chat output is styled. I was wondering if one could point me to the right direction for that. Thanks a lot!

**Comment by Phergus** [comment] 2020-05-01 12:27
The code is in `SayMacro.java`.  Easy enough to change it but the issue is that some folks aren't going to want this change.  So there needs to be a user-configurable solution.

Probably something in Preferences to either customize the HTML/CSS used or to load a user-defined block of code.

**Comment by Azhrei** [comment] 2020-05-01 12:46
> Probably something in Preferences to either customize the HTML/CSS used or to load a user-defined block of code.

Agreed.  Some kind of template.  There should be two, actually.  One which is the contents of the <head> section, and then one for each block of output.

**Comment by mrkwnzl** [comment] 2020-05-02 08:14
That definitely exceeds my abilities.

Just out of curiosity, what downsides would this change have? Maybe there’s another way which would circumvent the downsides, but also solves some of the odd behavior of line breaks and shifting left alignment in order to avoid all the white space on the left hand side of the chat window.

**Comment by Phergus** [comment] 2020-05-02 13:48
I mostly agree that it looks better.  Especially for walls of text with long names.

Here is a different situation.

**With output below name:**
![image](https://user-images.githubusercontent.com/34379254/80865431-b6299800-8c46-11ea-91c8-5cfe239a8b63.png)

**MT 1.6.1**
![image](https://user-images.githubusercontent.com/34379254/80865444-c3468700-8c46-11ea-9305-71cab85c429c.png)

So we don't want to just switch to a different way for one set of users making a different set of users unhappy. Instead we need to find a solution that gives sufficient flexibility for both.

**Comment by mrkwnzl** [comment] 2020-05-02 14:09
I don’t want to push this too hard, but honestly, I really don’t see the problem if the names are printed in bold.

<img width="334" alt="Screen Shot 2020-05-02 at 16 05 43" src="https://user-images.githubusercontent.com/40534855/80866426-ded58000-8c8e-11ea-99ac-5b719ddf2289.png">

You are right, without bolded names, it seems less clear. But I find my example still the best looking.

**Comment by JamzTheMan** [comment] 2020-05-02 14:09
I think you guys are close.  Suggestion: For no image like the GM, float the name and text over the same space anyway. So If we are showing, say, a 20x20 pick token image, always pad over 20px.

In other words, make it look like Discord chat.

Could also try adding a thin vertical light grey bar down the gutter between image and text to visually show blocks of text being to the one message, like how discord does when it explodes out a youtube like with the red line.

**Comment by Phergus** [comment] 2020-05-02 15:35
> I don’t want to push this too hard, but honestly, I really don’t see the problem if the names are printed in bold.
Other than it looking terrible when it jumps back and forth between with and without a token image.  
It also looks disconnected having just a name on one line followed by a line of text with the same indent not to mention taking up more vertical space.

Jamz suggestion of making it Discord like may work though the token image will need to be shrunk.

**Comment by mrkwnzl** [comment] 2020-05-02 15:57
> Other than it looking terrible when it jumps back and forth between with and without a token image.

To be honest, this bothers me as well, but it does in both options. Would a default image be a better solution? This way, there wouldn’t be a back and forth, and it distinguishes chat messages from system messages. Of course, there’s still the little issue that it takes up a bit more vertical space.

I’m not sure I understand Jamz’ suggestion fully. I thought my proposal already looked a lot like Discord.

**Comment by mrkwnzl** [comment] 2020-05-02 16:10
What do you think of this? It solves the issues I have, while not changing it for the people who like it to be in one line.

<img width="335" alt="Screen Shot 2020-05-02 at 18 09 19" src="https://user-images.githubusercontent.com/40534855/80869332-27496980-8ca0-11ea-95ac-d7d69c8826d8.png">

**Comment by JamzTheMan** [comment] 2020-05-02 17:24
I think `marko:` should just line up with `Elf` and `hero`

Pretend those have blank token images (we could try it as well using a default image if no token is impersonated but try without first.

Bonus points for a campaign option to choose a default image to use when no token is impersonated.

**Comment by JamzTheMan** [comment] 2020-05-02 17:28
Also, for another bonus that may help clearly show what text belongs to who... I was suggesting a vertical bar like this orange but grey, meant for quotes in discord but in maptool it would show/mark each block of text so it doesn't run together.

![Screenshot_20200502-122517](https://user-images.githubusercontent.com/8051654/80871071-31ec0a80-8c70-11ea-9fe1-86e643c1457a.png)

**Comment by mrkwnzl** [comment] 2020-05-02 19:51
You mean something like this?

<img width="384" alt="Screen Shot 2020-05-02 at 21 42 15" src="https://user-images.githubusercontent.com/40534855/80885820-f37d3c80-8cbd-11ea-9cc0-e4c14c024b74.png">

And again for comparison:

<img width="399" alt="Screen Shot 2020-05-02 at 21 47 06" src="https://user-images.githubusercontent.com/40534855/80887849-828a5480-8cbe-11ea-8de1-db47a1b422ce.png">

I have to say that I like it. It keeps the one-liners intact, solves my problem with longer names, and is very clean and consistent. It’s easy to spot where a new message begins. I’m not sure a default avatar is needed, as that would again defeat the one-liners.

What do you guys think?

**Comment by Azhrei** [comment] 2020-05-02 21:12
Jamz's original shoes the name above the line instead of beside it, but I think I like the cleaner look of the name to the right rather than on top.

**Comment by Phergus** [comment] 2020-05-03 12:44
I like it!  I think it is much cleaner.

I also like Jamz's suggestion of adding a generic token symbol for when there is no impersonated token?  Maybe two?  One for GM and one for Players.  Wouldn't necessarily have to be done on this issue.

**Comment by mrkwnzl** [comment] 2020-05-03 13:15
Would you have the generic token to be the same size as the others? I think it wouldn’t look good to have different sizes, but having a default image would effectively eliminate one-line messages.

**Comment by JamzTheMan** [comment] 2020-05-03 13:59
Looking good!

And agree, the default images could be done in a different issue. And there default could be black/none with option to add gm/pc images. And yes, they should all be the same size.

What would it look like to have the bar start under the name? Although i suspect you are right about one liners then. It may only make sense if we wanted to change it to something like `Name datetimestamp` 


BTW what does it look like with a broadcast message and macro output? I would think we probably don't want the grey bar in those cases when people are outputting html tables and such for attack macros and other stuff?

**Comment by JamzTheMan** [comment] 2020-05-03 14:01
@mrkwnzl btw thanks for being flexible and working with us on our collaborative design sessions lol

**Comment by mrkwnzl** [comment] 2020-05-03 14:12
@JamzTheMan Sure. I just hope I’m not too pushy. It’s a group effort, right?

I agree that a generic default image should be its own issue (and that has nothing to do with the fact that I wasn’t able to do it right now...). But I’m really not sure if it’s the best idea. It looks pretty good without it. And people might even like that there is no GM image.

It doesn’t affect broadcast messages, and, as far as I can tell, system messages. At least not the “Server started” message and error messages for faulty macros. I used the broadcast macro from @Phergus from some post above. 

Here’s how it looks. As expected, actually. It has the side benefit that it now distinguishes between those kinds of messages more clearly. I can now see quickly if it’s a chat message or a system message.

<img width="377" alt="Screen Shot 2020-05-03 at 16 09 42" src="https://user-images.githubusercontent.com/40534855/80916377-8a96d280-8d58-11ea-831c-123a49a837a9.png">

**Comment by mrkwnzl** [comment] 2020-05-03 14:14
I didn’t try putting the name above the text message, as I think it doesn’t make sense without a default image. The benefit of one-liners outweighs that, I believe.

**Comment by Phergus** [comment] 2020-05-03 14:22
It is a group effort and bouncing ideas around with some give and take is the way to get to what works for most users.

Broadcast messages an be made to look exactly like regular output if desired as you can apply all of the same HTML/CSS to that output in your macro.  So it can look different or the same depending on the goal.

Same for regular macro output depending on if there is an impersonated token.

For me, what you have now is pretty close to ideal and I think it will be a big improvement for most folks.

**Comment by mrkwnzl** [comment] 2020-05-03 14:25
Great! Since there weren’t any objections, I issue a pull request. Thanks!

**Comment by JamzTheMan** [comment] 2020-05-03 14:29
Cool, the framework coder can then add padding or not if they want it to line up or not. I like it.

For default images (to document for new issues later) we could default it to either a black image that doesn't take up space, eg no image, or a blank one that does take up space. And next to those preference options we could add a checkbox option that could force message to next lined under name (and maybe change the name font size a bit larger)

**Comment by JamzTheMan** [comment] 2020-05-03 14:32
@aliasmask since you are one of our big framework coders, see any issues with the above or any other suggestions before we close this issue out? (@Phergus as well?)

**Comment by JamzTheMan** [comment] 2020-05-03 14:34
Oh i got ninja posted lol, nevermind mr pherg :)

**Comment by aliasmask** [comment] 2020-05-03 15:02
More options is always nice. I've always used my own output macro with broadcast. The main thing is I put the player name as a tooltip over the image so you know which player is saying what.

I've been mulling over whether I want to do a forum-type chat and how to implement that. This could support multiple conversations and group them together. Essentially, you can either start a new conversation or hit reply to an existing one. It would have the token pictures next to the conversations to show who's in it. But that's neither here nor there. But it would be super cool if someone else can do all the work for me ;)

**Comment by aliasmask** [comment] 2020-05-03 15:04
I think people would really like an option to add timestamps to the chat as well. I've heard that several times before. If nothing else, maybe to the chat log?

**Comment by Phergus** [comment] 2020-05-03 17:09
Something a bit weird going on.
![image](https://user-images.githubusercontent.com/34379254/80920507-90c38980-8d2d-11ea-9034-2f4c51bb8ef5.png)

1. Started a server.
2. Typed in "Testing".  Came out as expected.
3. Ran macro for Orc hit.  Still good.
4. Selected Hero token and ran Evade macro. Still good.
5. Ran macro for howling.  No longer lined up.
6. Deselected all tokens and ran again.  Same.
7. Selected Elf and ran Perception macro - good.
8. Selected Hero and ran Hero hit macro - good.
9. No tokens selected and ran macro with critical output. Not lined up.
10. Impersonated Elf token and ran same macro.  Now it is lined up.
11. Turned off impersonation, ran macro again and now it is lined up.

**Comment by mrkwnzl** [comment] 2020-05-03 17:14
Could you provide me with the campaign file with your macros?

Have you been impersonating Hero while using the howl macro?

**Comment by Phergus** [comment] 2020-05-03 17:20
I wasn't impersonating anything until step 10.  Campaign incoming.

[ChatOutput.cmpgn.zip](https://github.com/RPTools/maptool/files/4571056/ChatOutput.cmpgn.zip)
(Remove `.zip`).

So the macros are numbered in order.  And where noted above the appropriate token has to be selected.

**Comment by mrkwnzl** [comment] 2020-05-03 17:22
Thanks! I’ll take a look!

**Comment by mrkwnzl** [comment] 2020-05-03 19:32
@Phergus Found a solution (or maybe workaround). Works now with your campaign as expected. Issuing a pull request shortly.

Here’s how it looks like if I do exactly as you did:

<img width="377" alt="Screen Shot 2020-05-03 at 21 30 23" src="https://user-images.githubusercontent.com/40534855/80923674-58e83080-8d85-11ea-9d87-f252cfb43003.png">

But I’m not sure if this isn’t a bug somewhere else (my Java isn’t good enough to determine that). After using a macro set to “Apply to Selected Token,” MapTool thinks I’m still impersonating a token until I actually impersonate a token and then de-impersonate that token.

So what happens is that the first condition in the if-statement is met after the use of that macro, but then token returns `null`, which results in skipping the `if (token != null)` statement. I would expect that MapTool skips the `if (MapTool.getFrame().getCommandPanel().isImpersonating() && AppPreferences.getShowAvatarInChat())` statement going straight to the else-if-statement below. But it doesn’t until I impersonate and de-impersonate a token.

Am I missing something here?

```
if (MapTool.getFrame().getCommandPanel().isImpersonating()
        && AppPreferences.getShowAvatarInChat()) {
      Token token;
      GUID guid = MapTool.getFrame().getCommandPanel().getIdentityGUID();
      if (guid != null)
        token = MapTool.getFrame().getCurrentZoneRenderer().getZone().getToken(guid);
      else token = MapTool.getFrame().getCurrentZoneRenderer().getZone().getTokenByName(identity);
      if (token != null) {
        MD5Key imageId = token.getPortraitImage();
        if (imageId == null) {
          imageId = token.getImageAssetId();
        }
        sb.append("<td valign='top' width='40' style=\"padding-right:5px\"><img src=\"asset://")
            .append(imageId)
            .append("-40\" ></td>");
      } else if (AppPreferences.getShowAvatarInChat()) {
      sb.append("<td valign='top' width='46' style=\"padding-right:5px\"></td>");
    }
```

**Comment by Phergus** [comment] 2020-05-03 20:49
I suspected that it was some kind of logic issue in the handling of the impersonate state.

Tested.  Appears to be working correctly with/without a server running.

**Closed** 2020-05-03 21:14 UTC
Labels: feature, tested
