### ISSUE TITLE
[Bug]: json.rolls returns same result for all rolls

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3292] opened 2021-12-20 01:22 UTC
### Describe the Bug

According to [wiki](https://wiki.rptools.info/index.php/json.rolls) 
_Rolls the dice expression the requested number of times and returns a JSON Array with the result._

Actual result, Rolls the die once and returns that value n times in an array.

### To Reproduce

1. go to chat window
2. enter `[json.rolls(1d52, 3)]`
3. result will look like `[45,45,45]`
4.  enter `[json.rolls(1d52, 3, 3)]`
5. result will look like `[[45,45,45],[45,45,45],[45,45,45]]`

### Expected Behaviour

Expected results like 
`[45,3,27]`

### MapTool Info

1.11.4

### Desktop

Win10

**Comment by Phergus** [comment] 2021-12-20 01:58
Try putting quotes around the dice expression per the documentation.

An interesting side-effect however.

**Comment by cwisniew** [comment] 2021-12-20 03:11
> Try putting quotes around the dice expression per the documentation.
> 
> An interesting side-effect however.

Its because the parser doesn't know what a dice roll is, dicelib translates the dice roll into a function call, that is 1d52 is actually roll(1, 52) which is passed to the parser to evaluate.  Because the parser doesn't know what a roll is it can't check what is supplied as an argument is a roll or not. So since the 1d52 is not in quotes dicelib hijacks that and turns it into roll(1, 52) which runs once, and returns 45 (in the above example).  The json.rolls() then uses that 45 all the time... 

json.rolls is creating a parser to run the argument X times. If the argument is a string "1d52" then dicelib will change it to roll(1, 52) each time and run it. But if it runs first time before the function (i.e. it is not in a string) then the same number just gets passed every time.

**Comment by Phergus** [comment] 2021-12-20 03:14
So classify it as _Won't Fix_?

**Comment by FullBleed** [comment] 2021-12-20 10:14
Just seems like a syntax error and working as intended... is there a RTFM tag?  ;)

Maybe the wiki could be updated to make the needed quotes be more obvious though.  I think I made this same mistake once.

**Comment by Phergus** [comment] 2021-12-20 13:36
The wiki says it takes a string for the first parameter but I'll make it more explicit.

Closing.

**Closed by Phergus** 2021-12-20 13:36 UTC
Labels: bug
